### ISSUE TITLE
画像ファイルの拡張子が大文字のとき，画像が見つけられない

### ISSUE THREAD

**Issue by zgtk-guri** [kmuto/review#1002]
画像ファイルの拡張子が大文字のとき，PDFの生成に失敗します。
JPEGファイルですが，`.jpg`であれば正しく読み込んでくれますが，`.JPG`とするとTeXのエラーが発生します。
エラーメッセージは以下の通りです。

```
[14] [15] (./book.aux
! Missing \endcsname inserted.
<to be read again>
                   \unhbox
l.52 ...あああああ}{subsection.2.2.1}{}}

?
```
`あああああ`は章のタイトルです。

よろしくお願いします。

**Comment by zgtk-guri** [comment]
環境はmacOS HighSierraです。vvakameさんのdockerイメージを使用しています。

ReVIEWのコンパイル時に以下のメッセージが出ているのに気がつきました。
これは大文字の拡張子には対応していないから画像が見つけられてないんでしょうか？
```
W, [2018-04-11T20:14:23.289250 #137]  WARN -- : 00-xxxxx.re:118: image not bound: image_id
```
`image_id`は画像のIDで，拡張子より前のファイル名です。

**Comment by kmuto** [comment]
はい、今は画像ファイルはcase sensitiveな探索をしており、拡張子は小文字前提となっています。

image_finder.rb
```
if @entries.include?("#{target}#{ext}")
    return "#{target}#{ext}"
```

大文字小文字違いで同じファイル名を共存させることはまずなさそうなので、case insensitiveなロジックに変更すべきかな…。

**Comment by zgtk-guri** [comment]
iOSから写真等を直接持ってくると，拡張子が大文字になっていることが多いので，case insensitiveであると不要なところで悩まなくて済むかと思います。
vvakameさんのAtomパッケージlanguage-reviewでのプレビューでは，画像が正しく出ていたので，余計悩んでしまいました。

とりあえずの解決策として，`config.yml`の`image_ext`に大文字の拡張子も追加する，という方法を思いつきましたが，有効でしょうか？
