### ISSUE TITLE
@<w>を取り込む?

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1007]
- #1005 
- https://twitter.com/kmuto/status/994058068341219328

- コマンド名はwでまぁいいかなと思います。
- csvファイルの指定をどうするか。また決めうちのファイル名ができるのは嫌だけれどもいちいち指定するのもダルい？
- 元々のkdmsnrさんのだとキーをsingularize.downcaseなどしているけれどもそこまで必要だろうか
- w+b相当のwbも入れないと困りそう?
- latex, html, idgxmlの場合はエスケープが必要

**Comment by kdmsnr** [comment]
- すべてのビルダーに `escape` がほしいですね
- singularizeは面倒なので、最近は使ってないです

**Comment by kmuto** [comment]
そういえばescapeほしいですね。
