### ISSUE TITLE
PDFMaker: default style should be for printing

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1032]
標準のPDFは印刷用に寄せます。

理由: PDFでの配布はやり直しがきく（こともある）けれど、印刷で失敗すると修正が手遅れになりダメージがでかいことが多いので。

related to: #808

**Comment by kmuto** [comment]
いいと思います。
できればクラスファイルオプションなどで切り替えたいですねー

**Comment by kmuto** [comment]
デフォルトは トンボ付き、ハイパーリンク装飾なし、にしておきたい

**Comment by kmuto** [comment]
twitterで見てると

- 大扉通しノンブルにしたい
- そうでなくてもドブに隠し通しノンブル入れたい

という希望がある模様。

**Comment by kmuto** [comment]
はい、こういうのを見かけたのでした。
https://qiita.com/ukyo/items/4a0f697c332343d77659

ノドに入れる、ほうがいいんですね。商業書籍だとやったことがない…

**Comment by kmuto** [comment]
#1117 にて対応
