### ISSUE TITLE
Re:VIEW 2.5.1 or 2.6?

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1054]
#936 のRe:VIEW 3.0はもうすぐリリースするつもりですが、まだpreview版なので、場合によっては2.5.1や2.6のリリースも考えた方がよいかもしれません。

**Comment by takahashim** [comment]
まあでも何か不具合があった場合の2.5.1くらいにしておくのが無難かも。
2.6を出すとすると、3.0への移行を促すためのバージョンになりそう。

**Comment by kmuto** [comment]
2つリリース維持はいろいろ辛そうな気がするのですが、そうでもない？

**Comment by kmuto** [comment]
2系はもう作業はしなさそうだし、3のリリースに注力しましょう
