### ISSUE TITLE
*.sty内での他*.sty読み込み

### ISSUE THREAD

**Issue by yuw** [kmuto/review#1056]
デフォルトで書き出されるLaTeXのスタイルファイル中で`\usepackage`が使われていますが，*.sty内で`\usepackage`はLaTeX的に変なので，`\RequirePackage`を使う方がよいと思います．
例えば`review-base.sty`の冒頭では次のような具合です：

```
\RequirePackage{ifthen}
\ifthenelse{\equal{\review@texcompiler}{uplatex}}{%
\RequirePackage[deluxe,uplatex]{otf}%
}{%
\RequirePackage[deluxe]{otf}%
}
```

対象は次のファイル達になると思います：

- review-base.sty 
- review-style.sty
- reviewmacro.sty

（すぐに問題があるわけではなかったりしますが）

**Comment by takahashim** [comment]
指摘ありがとうございます！　これって単純に置換してしまっても問題ないでしょうか？ (tex.stackexchangeで検索したところでは`\ RequirePackage `は`\documentclass`の前に書けるところが違ってあとは同様、みたいな雰囲気でしたが)
