### ISSUE TITLE
pdfmaker: 表紙はフルサイズにする?

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1064]
今はcenter+includegraphicsなのでダメだけど、フルサイズにすること自体はmunepiさんに教えてもらった手法でわりと簡単にできそう（縦書き判定をすると長くなる？）。

ただ互換性はなくなるのでそれがいいのかどうか。aspectはkeepするのかひきのばすのかとか利用者によってちょっと判断が割れそうではある。

**Comment by takahashim** [comment]
フルサイズじゃないことを期待するケースは少ないので互換性は気にしなくても良いかと思うのですが（いざとなったら上書きで逃げられれば可）、アスペクト比が変わるのはかなりまずいんではないかと思いました。
あとPDFで作ってそのまま使いたいケースがあって、その場合もフルサイズにできるとよさそうです。

**Comment by kmuto** [comment]
#1117 にて対応(\includefullpagegraphics)
