### ISSUE TITLE
move sample-book and syntax-book

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1073]
普通に考えてtestではないのでは…という気持ちです。
/samples/ でも作る？

**Comment by takahashim** [comment]
review-initで生成されるファイル群についても、もう少しやりようがある気がしております。

**Comment by kmuto** [comment]
せやなー。
もともとsample-bookがあって、docに入れるにはそれを読んでほしいというものでもないし…ということなので、samplesを作って移動するのは賛成です。

**Comment by kmuto** [comment]
とりあえず今のtest/sample-bookとtest/syntax-bookはstyの中身が2.0だけどconfig.ymlが3.0なのでビルドできないことに気付きました。
移動してから対処しますかね…。
