### ISSUE TITLE
ブロックの入れ子がほしい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#108]
(TODOとして)

noteなどの中にemlistを入れたり、箇条書を記述できるようにしたい。

パーサの大規模な見直しが必要。emlist,table,imageのような要素では入れ子解析はしないようにする必要もある。

**Comment by takahashim** [comment]
@kmuto 苦節3年（！）、ついにできるようになりそうです。

整理した結果、ブロックを2通りに分ける形を考えています。

* `//quote`などのように、ブロックの入れ子を許すもの。これはブロックの内部もブロックの集合として解釈するため、ブロックでも箇条書き等でもないテキストの場合はパラグラフとして解釈されます（改行が連結されたりします）。
* `//emlist`などのように、ブロックの入れ子を許さないもの。これはブロックの内部はテキスト行の集合として解釈されます。改行も保存されます。

前者はこれまで通り`defblock`で定義しますが、後者は`defcodeblock`という新たに用意したメソッドで定義します。どちらで定義されたかによって、パーサの解釈とビルダに渡される引数の作り方が異なります。

**Comment by kmuto** [comment]
:+1:  :+1: 

おつかれさまでした。ブロック2通りはたしかに妥当ですね。

**Comment by kmuto** [comment]
PRにないのですが、このdfcodeblockのって結局PEGでやろうとしていたものなんでしたっけ

**Comment by kmuto** [comment]
#1558 で対応されました
