### ISSUE TITLE
review-init bookで作った文章がビルドできない

### ISSUE THREAD

**Issue by tnishinaga** [kmuto/review#1080]
## 問題

`review-init book` でテンプレートから文章を作成すると `review-pdfmaker` でのビルドが失敗します。

## 確認バージョン

2.5, 3.0

## 再現方法

https://gist.github.com/tnishinaga/a445177a05c0f125093faa900e520294

` ./setup.sh ` 実行後に `./build.sh` を実行してください。

## エラーログ

https://gist.githubusercontent.com/tnishinaga/a445177a05c0f125093faa900e520294/raw/c3eed4ce5214c2d219162ebe3a957bcd98520815/errorlog.txt

## 原因予想

`review-pdfmaker` が実行されると、Re:VIEWはTeXマクロの書かれた `book.tex` を生成します。

`review-init book` コマンドより作成した文章をそのままビルドすると、 `book.tex` に書かれた `reviewchapterfiles` マクロは次のようになります。

```
\def\reviewchapterfiles{\input{book.tex}
}
```

このマクロが ` \begin{document} ` 内で使われているため ` ! LaTeX Error: Can be used only in preamble. ` が発生しているものと予想します。

実際に `review-init main` で生成した文章をビルドした際の `reviewchapterfiles` マクロの中身は以下のようになっており、ビルドに成功します。

```
\def\reviewchapterfiles{\input{main.tex}
}
```

**Comment by kmuto** [comment]
ご報告ありがとうございます、なるほど… 原因はご推察どおりですが、解決方法は悩ましいですね。

- 案1: 一時ファイルをbookではなくまず使われなそう・かつTeXやOSに安全な名前にする。普通に作っているようなドキュメントでは問題なさそうだが、フック処理などをしているもので障害が発生するかも。ただそういうのはフック側を直せという論もある。
- 案2: review-initで「book」という名前のプロジェクトを禁止する。対応としては簡単だがダサめ。

**Comment by kmuto** [comment]
プロジェクト名にかぎらずreファイルがあるだけでダメだから案1で実装するしかないですね。__あたりを付けた名前で大丈夫だろうか…。

**Comment by takahashim** [comment]
出遅れました、これはプロジェクト名というより`*.re`ファイルの衝突の問題かと思うのですが、catalog.ymlでファイル名は全部検出できるので、そこでバッティングしないようにする、みたいな感じでしょうか…。

**Comment by kmuto** [comment]
今はlayoutから生成したベースファイルがbook.texなので、reファイルに同じ名前のものがあるとサイクリックになっちゃうのです…

**Comment by kmuto** [comment]
なので、layoutから生成するときのは__REVIEW_BOOK__.texみたいな名前にしたほうがいいかなと。reファイルと競合しないほうがいいけれども、あまりランダムな名前にするとフックやmakeindexの処理のときにつらい。

**Comment by takahashim** [comment]
> 今はlayoutから生成したベースファイルがbook.texなので、reファイルに同じ名前のものがあるとサイクリックになっちゃうのです…

なので、catalog.ymlに同じ名前.reがないかどうかをチェックすればいいんでは、と思ったんですが、coverとかcolophonとかとかぶる可能性もありますね…。

基本的にはベースの名前(`__book_0`)みたいなのを決めて、`Dir.glob()`でファイルがかぶる可能性がないかを調べて、かぶりそうだったら`__book_1`にして…みたいなのを繰り返すことでファイル名を決める、というのが確実ではないでしょうか。

**Comment by kmuto** [comment]
とりあえず #1081 では__REVIEW_BOOK__という名前にしてみています。この名前に対してあえてぶつけてくるという可能性は相当レアで偏屈だと思いますので、これでいかがでしょうか。

**Comment by takahashim** [comment]
んー、ではいったん #1081 を取り込んでから、PR送りますね

**Comment by tnishinaga** [comment]
bookやmainのようによく使いそうな名前を外していれば、私も問題ないと思います。
ありがとうございました
