### ISSUE TITLE
太字になるidx命令が欲しい

### ISSUE THREAD

**Issue by uchan-nos** [kmuto/review#1082]
## 背景

`@<idx>{}` で索引を作成する際，初出の単語は太字にしたいことが（私の用途では）多い．そうしたい場合，インライン命令中にインライン命令を含むことができないので `@<b>{hoge}@<hidx>{hoge}` のようにせざるを得ない．とても冗長である．

## 解決案

`@<bidx>{}` という命令を追加する．これは，太字にしつつ索引生成も同時に行うインライン命令である．

## 議論

索引生成と太字にするのを同時にやりたい著者が多いか少ないかは調査できていない．太字ではなく斜体などが好きな著者もいるかもしれない．

もう少し汎用的な解決策としては `@<fmtidx>{}` のような命令を作っておき，設定ファイルで `index_format: b` や `index_format: i` などと指定できるようにする方法も考えられる．

**Comment by kmuto** [comment]
ありがとうございます。
うーん、ちと悩みますね……。

もともとのidx自体「表示とともに索引にもなる」というのはタグ名から直感的に判断しづらく、また挙動もわかりづらいような気がしています。実際、私が受け取るデータでもミスはたびたび目にしており、idxを廃棄してhidxのみの推奨にしようかと思っていたところでした。

「汎用フォーマット付きidx」はfmtidxでないにしてもタグ名がどうしても冗長になるのと、表示+索引の意図がますますわかりづらくなりそうなので避けたいところです。

なお、TeXの処理の気持ちになると、hidxはキーワードの「前」のほうがよいようです（なので、今のidxの実装もよくない）。

**Comment by munepi** [comment]
> なお、TeXの処理の気持ちになると、hidxはキーワードの「前」のほうがよいようです（なので、今のidxの実装もよくない）。

LaTeXの索引のマークアップの方法は、基本的に下記に2つだけ気をつけておけば大丈夫です！！
（※それ以外の挙動もありますが、ほぼ出てこないのと条件がアレなので、なかったことにしておいてOKです）

 1. 原則的に「\index{索引用語}索引用語」でマークアップします。
    * なぜならば、もし「索引用語\index{索引用語}」のようにマークアップしてしまうと、「索引用語」中のどこかでページが送られることがあれば、「索引用語」のページ参照は、+1 されてしまいます。
 2. 段落開始直後の索引用語のみ、「索引用語\index{索引用語}」とします。
    * なぜならば、もし「\index{索引用語}索引用語」のようにマークアップしてしまうと、「索引用語」がページ1行目であるとき、\index{索引用語}は前のページとなり、「索引用語」のページ参照は、 -1 されてしまいます。

**Comment by uchan-nos** [comment]
コメントありがとうございます．

> もともとのidx自体「表示とともに索引にもなる」というのはタグ名から直感的に判断しづらく、また挙動もわかりづらいような気がしています。

私はidxの使い方をドキュメント https://github.com/kmuto/review/blob/master/doc/makeindex.ja.md を読んで割とすんなり使いこなせました．今では便利に使っていて，hidxだけになっちゃったら不便すぎるなあと思います．たびたび目にするというミスが何であるか提示していただけると，解決案を議論できそうです．

idxのように，出力と索引登録を同時に行うタグがあれば，munepiさんが指摘している「場所によって `\index` を出力する場所を変えるべし」というのを自動化できます．原稿を書く人に「段落の先頭のときだけは語句の後ろにhidxを書きましょう」というルールを教えなくていいかもしれません．（hidxを使うときは依然として気を付けないといけないかもしれませんが，fmtidx（仮名）が追加されれば，hidxを使う機会がぐっと減るので．）

**Comment by kmuto** [comment]
uchan-nosさんに教えていただきましたreadthedocsを使って、https://review-knowledge-ja.readthedocs.io/ を立ててみました。
感謝を込めてbidxの追加方法を記事化しています。

ミスは、idxとhidxという名前の混同によるものが大半で、「紙面化すべきでないのにidxを使ったために紙面に出ちゃって語句が連なった文になった」「紙面化もすべきなのにhidxを使ったために語句が欠落した」のどちらもあり、そのまま刊行流通してしまって正誤行き＆増刷で修正、みたいなケースも……。少なくともidxはもうちょっと名前から判断しやすいようにすべきだったなと感じています。

**Comment by uchan-nos** [comment]
そういえばこのissueはkmutoさんから教えていただいた独自命令を定義する方法でばっちり解決したので、closeしておきます！
