### ISSUE TITLE
review-ext.rbなどの事例の置き場を作りたい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1087]
Re:VIEWの利用が増えてきてQiitaなどにも情報が上がってきていますが、若干「それはどうかな…」みたいなバッドノウハウが散見されたり、今検討中のbidxのようにコアの機能に含めるには悩む点が多く即決できないけれども実装自体は簡単にできそうだったり、という背景から、review-ext.rb事例集や、sty集の公式な置き場所を作りたいと考えています。

- reviewml.orgやwikiから事例集インデックスにリンクする
- 書き込み権限はあくまでもRe:VIEWコミッタのみ
- どこでどう管理するか、が悩み

- review.git masterにexamplesのようなフォルダだと邪魔か（syntax-book, sample-bookの移行兼ね合いもあり）
- かといって別ブランチ、別プロジェクトというのもおおげさな感じがする
- インデックスは自動生成にしたいがそのための情報をどう保持・生成するか
- とりあえず日本語だけでよいか

「gistで書いてリンクする」みたいなことはだいぶ手間で、数が多くなると辛いなと思いました。
Qiitaに公式で書く、というのもあるかもですがプロジェクトの置き場であるGitHubと分離したところになるのがちょっと嫌なところです。

**Comment by kmuto** [comment]
ざっと調べた限りだと、

リポジトリとしてはreviewml/review-samples-jaが使えそうですが、GitHubのcodeやwikiのページレベルだとナレッジベースまで作るのは難しいなぁという印象。

openkbとかrenatoあたりのナレッジベース用ソフトを使ってkmuto.jpかどっかにサーバを立てるのが妥当そうだけど、コンテンツ管理がDBベースなのでGitHubでコンテンツを管理する、というのがどの程度できるか不明。検索用のメタ情報を入れないといけない場合だとmdの書き方にも注意が必要そう？

**Comment by uchan-nos** [comment]
> 今検討中のbidxのようにコアの機能に含めるには悩む点が多く即決できないけれども実装自体は簡単にできそうだったり

コアに無くてもカスタマイズで全然良いなーと思ってます．review-ext.rb という仕組みがあるのですね．サンプル集があるととっても嬉しいです．


既に検討されているかもしれませんが，私は Read the Docs というサービスを使ってます．GitHub のリポジトリへの push をフックして自動ビルドまでしてくれるので，手間なく運用できて，良いですよ．広告が小さく出るだけで無料で使えますし． http://osdev-jp.readthedocs.io/ja/latest/2016/os-development-by-vscode/os-development-by-vscode.html

**Comment by znz** [comment]
github と簡単に連携できる静的サイトのホスティングだと netlify もあります。
もっと複雑な生成をするなら gitlab ci を使って gitlab pages にするという方法もありそうです。

**Comment by kmuto** [comment]
お二方、ありがとうございます。とりあえずRead the Docsを使って立ててみました。
https://review-knowledge-ja.readthedocs.io/

実質Sphinxのホスティングサイトなのでpush前に手元でビルドして試せるのはよいですね。
GitHubアカウント連携はそのままだとAdmin渡しで若干イヤげだったので、Hookは手動登録しました。

**Comment by kmuto** [comment]
とりあえず悪くなさそうな感じなのでこのまま充実をはかってみます。
ある程度質の均一化はしておきたいので、ひとまず個人作業かな…（そしてライセンスの話題でつまづき中）
