### ISSUE TITLE
rawの\n挙動をもう少しstrictにする？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1096]
実際どう表現できるのか、今後のパーサにますます負担をかけないか、という問題はあるのですが、
`//raw`、`@<raw>`ともに今は`gsub('\\n', "\n")`という文字列置換をかけています。

実際、生な命令中で改行文字を入れたいという場面は特にテキスト化やTeX（`\clearpage\n`など）で必要になるので、この機能自体は必要です。

しかし、TeXの命令がnから始まる（`\newpage`とか）と、今の素朴な置換ではTeX命令が壊されてしまいます。
embedを使えという話はありますが、たとえばrawの挙動を

- `\n`で終わったら改行
- `\n`の後ろが英字（a-zA-Z）でなかったら改行

とするのはどうでしょうか。とりあえず前者だけでも複数改行が必要ならrawを連続記述すればいちおう表現はできます。

**Comment by takahashim** [comment]
私としては`\embed`推し&&挙動を変えて混乱する方がマズそう、ということで、どう見てもおかしい場合は修正してもルールそのものを変更するのは後ろ向きですね…。

**Comment by kmuto** [comment]
なるほど。//embedは逆に必ず末尾改行が入る（ブロック内容の行群をそのまま出すので）けど、それが困るときには`@<embed>`と併用すればいいのかな。

**Comment by kmuto** [comment]
embedで対応ということで
