### ISSUE TITLE
Re:VIEW Meeting 2018 Autumn

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1101]
Agenda

- 3.0リリースへのTODOまとめ、ロードマップ策定
- TeXまわり展望？
- その他？

Date
- 平日夜がよさそう？ ゴハンが難点だが
- kmutoの都合は 9/12(水), 9/13(木), 9/14(金), 9/15(土), 9/19(水), 9/20(木), 9/21(金)
- @suzukin さんに会場依頼してもよいでしょうか…

**Comment by kmuto** [comment]
スタイルのサードパーティとして @mhidaka さんは同席いただいたほうがよさそう。

**Comment by mhidaka** [comment]
12,14,15,19,20,21オッケーす

**Comment by kdmsnr** [comment]
19,20,21だいじょうぶです

**Comment by suzukin** [comment]
https://connpass.com/event/100084/
@kmuto 管理者権限付与してますので内容のアップデートお願いします！

**Comment by kmuto** [comment]
助かります！ では20日よろしくお願いします＞ALL

**Comment by kmuto** [comment]
おつかれさまでした。議事録

https://github.com/kmuto/review/wiki/Re:VIEW-%E9%96%8B%E7%99%BA%E8%80%85%E4%BC%9A%E8%AD%B0-2018-Autumn
