### ISSUE TITLE
いわゆる隠しノンブルへの対応

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1131]
同人誌系だと意外と要求する印刷製本所は多いみたい。

https://www.marusho-ink.co.jp/howto/kakushi.html 
- ノド1mmの範囲に縦置き（さらにここはbleed 5mmなのか）

http://www.nikko-pc.com/q&a/yokuaru-shitsumon.html#3-1
- 技術書典でよく使われている日光企画。小さすぎるのはダメ

review-*.cls側では対応せず、生成されたPDFを再度TeXに通してノドに隠しノンブルを置くような支援ツールがあるとよさそう。しかし、回転ならともかく「縦置き」となるとちょっと面倒なような…。

**Comment by munepi** [comment]
いま、気付きましたが、Re:VIEW 3でいまのreview-*.clsのもとで隠しノンブルを2passで行うとすると、

 * cameraready=printでも、トンボがついて、トンボつき用紙サイズでまずいですし、
 * cameraready=ebookでも、PDF hyperrefが有効となっているので、（自前で PDF内の /anot を除いたりできないかぎり、）望ましくないです。

それから、隠しノンブルの付加を2pass にするのであれば、裁ち落としあり（裁ち落とし幅の設定も必要…）のPDFを1pass目に吐いておく必要がありますね…。
隠しノンブルを2 passで行うとすると、印刷仕様の cameraready=print にトンボアリを入れたことが裏目になりそうです…。

そこで…、
review-*.clsに `blindfolio=<preset>` オプションを用意して、「gentombowの\settombowbanner経由で適当にTeX実装」を実装するのが現実的！？

ちょっと頭を冷やしてきます。

**Comment by kmuto** [comment]
printから出したPDFに、digital tomboだけつけなおし・トリムマーク表現なし でやればいいかなーとぼんやり思っていましたが、digital tomboからサイズを取得する手段が面倒そうですね。

blindはいろいろアレな気がするので、hiddenfolio=<preset> ?

**Comment by munepi** [comment]
日光企画の隠しノンブルの仕様がよく分からないですが、何か仕様があるのでしょうか？

ほかのいんさつじょさんもたいおうしたほうがよければ…、（棒読み）

**Comment by munepi** [comment]
その「仕上がりの中に入れる」は、具体的にどのような仕様によいのでしょうか？

「全部「仕上がりの中に入れる」とか、んなの隠しノンブルでもなんでもねーじゃねーかよ！」ってツッコミを入れまくりたくなるんで、「綴じのギリギリの仕上がり内側に入れておけばOK？」って言いたくなるのですが…。

日光企画さんのほうに、

> 隠しノンブル（トジ側ギリギリ）

という言葉があるので、こちらでいい加減に実装してよければ、
`hiddenfolio=nikko-pc` と `hiddenfolio=shippo` （`nikko-pc` へのalias）は、ひとまず、同一仕様にしておいて、「ノドの仕上がり線ギリギリに天地中央で隠しノンブル」を入れておきます。

**Comment by kmuto** [comment]
そうなんです、見えづらいとREJECTしますくらいしかなくてよくわかんないんですよね…。
とりあえずその実装でよさそうに思います！

**Comment by kmuto** [comment]
丸正インキも隠しノンブル要求でしたね…。

**Comment by kmuto** [comment]
http://www.marusho-ink.co.jp/howto/kakushi.html わりと細かい

**Comment by munepi** [comment]
`hiddenfolio=marusho-ink` (丸正インキ)  にもすでに対応済です。

**Comment by kmuto** [comment]
marusho-inkはトンボ5mmにはなるけどノンブルが小口上トンボの外に置かれている？
（また環境のせいだったりするでしょうか…

**Comment by munepi** [comment]
TL16 frozen, 17 frozen, 18 currentいずれでも、問題なく、下記のスナップショットのようになります。

![2018-10-15 11 06 00](https://user-images.githubusercontent.com/583148/46926111-5a022180-d06a-11e8-9d20-f01ba15082dd.png)

**Comment by munepi** [comment]
こうします。

![2018-10-15 11 45 39](https://user-images.githubusercontent.com/583148/46927358-e3682280-d06f-11e8-9c3a-9e2986c14936.png)

**Comment by kmuto** [comment]
#1117 にて対応
