### ISSUE TITLE
review-jlreq.clsのクラスオプションstartpageは何の用途たちで利用しますか？

### ISSUE THREAD

**Issue by munepi** [kmuto/review#1134]
https://github.com/kmuto/review/blob/729231d412bd85c88688cb0052f30707e0992660/templates/latex/review-jlreq/review-jlreq.cls#L70

 * 表紙1頁に対するノンブルのためだけでしょうか？
 * 他の用途として、口絵（複数頁）も想定していますか？

Re:VIEWのためのロジックとして `startpage` を用意することであれば、それはそれで許容範囲内かなと思っています。

**Comment by kmuto** [comment]
今朝 \frontmatterを大扉（titlepage）の前に置く をマージしたのですが、実装の意図としては次のとおりです。

- 表1・表2はデフォルトのアラビア数字でいい（というかこれらはノンブルはどうでもいいし、printの場合は表1・2は出さない）。
- 本体である大扉のページが最初のページとなるが、そのページを1とするのか3とするのかは流儀分かれる。ので、これに対応するのが目的。デフォルトは1
- ローマ数字別ノンブルとするかアラビア数字通しノンブルとするかはserial_pagination=true/falseで指定

Re:VIEWのためのロジックかどうかでいえば、本来は書籍クラスは一般にこういう機能があってもいいのではとは思います。

- frontmatterの実行で\setcounter{page}するようにしています。
- 口絵はfrontmatterの前なので考えないです。通常用途で登場することはなさそうですし、必要ならlayout.tex.erbなり各マクロなりを差し替えで対応で。
- serial_pagination=false(デフォルト) + titlepageなし(非デフォルト) + PREDEFなし という条件が重なると、mainmatterで\pagenumberingが入ってstartpageは無視されることになってしまう。のはしょうがないかな。

**Comment by munepi** [comment]
`\frontmatter` 直後における `\setcounter{page}{1}`, `\setcounter{page}{2}`, `\setcounter{page}{3}` あたりの入力をユーザにやらせずに、オプションとして用意するということですね。

**Comment by kmuto** [comment]
ですです
