### ISSUE TITLE
gentombowをvendorに入れる？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1136]
利点
- review-jsbookのデフォルトcameraready=printで正しいデジタルトンボが入る（必須に準じる機能）。
- 利用したい機能を備えたgentombowの最新はtlmgrかGitHubから取ってくる必要が普通はあるがOS標準TeXやDocker系だといろいろ面倒。vendorフォルダからテンプレートフォルダにコピーするだけなのは簡便

欠点
- vendorに他者の「アクティブな」プロジェクトを混ぜるということは妥当か
- upstreamの最新版との同期問題。sty/にコピーしているとTeXLive側で修正があってもローカルのほうが使われてしまう
- git submoduleを使う手もあるかもだけど、あれわかりづらくて嫌い…

**Comment by munepi** [comment]
「欠点」をRe:VIEWプロジェクト側で補うのであれば、以下の対応でしのげそうです。

1. 基本的にTeX Live同梱のgentonbow.styを使うようにする。
2. もしTeX Liveにgentombow.styが同梱されていなければ（TLを更新するように促すorローカルなgentonbow09j.styが使われている旨をログに出す）、gentombow09j.styのような別名でvendorに保持しておいて、以下のようにしておけば良さそうでしょうか？
    ```tex
    \IfFileExists{gentonbow.sty}{(snip)}{%
      \IfFileExists{gentonbow09j.sty}{(snip)}{(snip)}}
    ```

**Comment by kmuto** [comment]
@munepi さんの方法で入れましょうか。

**Comment by kmuto** [comment]
#1140 と #1117 にて対応
