### ISSUE TITLE
review-jlreqにもhiddenfolio機能を入れる

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1147]
だいたいコピーすればいける？

**Comment by munepi** [comment]
`\maketombow` の実装から、まるごとコピーでいけるはずです！

**Comment by kmuto** [comment]
gentombowの\settombowbannerはjlreq-trimmarksには定義がなく、ただシンプルなマクロだったのでそのまま展開しました。挙動は変わらないはず。

`\@bannertoken{\hskip-5mm\smash{\hiddenfolio@font\@makehiddenfolio}}`
