### ISSUE TITLE
文字サイズは級数ではなくptで指定したい

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1151]
単に分かりにくくなっているだけのような気がするのですが…。
jsbookと比べて見出しの大きさも変わってしまっています。互換性を壊してまで導入するメリットが見えないです。

**Comment by kmuto** [comment]
ベース文字と行高にptを使えるとよい？

**Comment by takahashim** [comment]
行高はmmか、通常の（ベース文字に合わせた）相対(通常は1.0とか100とか)で表せると分かりやすそうです。

**Comment by takahashim** [comment]
私自身の感覚では、

* 「jsclassesもjclassesもクラスオプション XXpt」の XXpt：jsbook.cls の本文文字サイズクラスオプションを使えるようにする」

か

* 「実寸サイズのポイント：本文文字サイズを単位つきで与えられるクラスオプション」

のどちらかが指定できればそれで良いかと思いました。後者なら後者でも良いです。

見出しサイズも特にjsbookのままで困っていなかったので、大きさが変わってて驚いたのですが、特にjsbookだと問題があるということでなければjsbookから変えなくてよいかと思いました。
（ちなみに試してみたのはpaper=b5,twocolumnのもので、`\section{}`が大きくなっていて`\subsection{}`が相対的に小さくなってるのに違和感がありました。）

**Comment by kmuto** [comment]
#1166 でfontsize=とbaselineskip=による任意単位、
#1179 でjsbook互換サイズ の対応を試みています。

**Comment by kmuto** [comment]
#1200 で任意単位指定できるようになりました。
