### ISSUE TITLE
TeX: tombopaper=を指定するとhiddenfolioが無視される

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1158]
review-jsbookで確認。
設定順序の問題っぽい

**Comment by kmuto** [comment]
あ、たぶんわかった

**Comment by munepi** [comment]
クラスオプションの処理は、後ろに書かれたオプションたちが上書きされる形で、実行されます。
こちらでも確認してみます。（ついでに、与えられた値をデバグできるようにしときましょうかね。）
