### ISSUE TITLE
review-updateの実行前後で見た目が大幅に異なる

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1192]
Re:VIEW 2.5のreview-initで生成されたファイルをreview-updateで更新してみると、だいぶ見た目が変わるようですが、どのあたりまで意図的なんでしょうか？

review-update前
![page1](https://user-images.githubusercontent.com/10401/47932159-3c5f0400-df14-11e8-8b3f-077ebb950b61.png)

review-update後(小節見出しは次ページへ)
![page2](https://user-images.githubusercontent.com/10401/47932179-48e35c80-df14-11e8-955b-4468fbde4f7e.png)

**Comment by takahashim** [comment]
ソースは https://github.com/takahashim/review-sample-20181103 に置きました。

**Comment by kmuto** [comment]
ちょっと手当てしてみます

**Comment by kmuto** [comment]
現状はセンター合わせとあいまってW（行あたり文字数）とL（行数）を使うようになっています。
今のWとLの数値はA5サイズ用の適正値で、たとえばB5だと W=40,L=36 で同等になります。

A4はまだ調べていませんが、同様に調整は必要そうです。

- 対策a: 紙サイズによってデフォルトのWとLを変えるように定義しておく（せめてA4とB5について）
- 対策b: #1166 のうちまだやりきれてない「QWLHによる設計の代わりに、天ノドのほか地と小口も指定することで版面を設計する」のを実装する

とりあえずぱっとみわかりやすいのとして、aを実装しておいたほうがよさそうでしょうか。

**Comment by takahashim** [comment]
ああー、なるほど、そういう意味ではLaTeXのデフォルトがA4なところが、Re:VIEWを紙の本として使いたい人とのニーズとずれてるんですね。とはいえ印刷で出しやすいのはA4なのでこれはこれということか。

対策aでA4とB5があれば十分そうです。

**Comment by kmuto** [comment]
#1179 も絡むのでそっちのほうに入れてみました。b5, a4だけ特別扱いでWとLを再調整します。

**Comment by kmuto** [comment]
しかしまだけっこう違いますね。はて…

**Comment by kmuto** [comment]
要素間アキがまだ合わないのですが、 #1194 で行送りを合わせてみました。
しかし一貫性が感じられず、別段これが美しいというわけでもないのが…。

**Comment by kmuto** [comment]
#1200 で対応できているはずです
