### ISSUE TITLE
ReVIEW-Template を使ったサンプルを3.0で使えるようにする

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1193]
https://github.com/TechBooster/ReVIEW-Template

review-update＋αで動かせるようにするか、新しく作り直すかしないといけないと思うのですが、現状だと難しそう（少なくとも私には直せなさそう）です。
どうしたもんですかね。

**Comment by takahashim** [comment]
既存のサンプルソースとしては以下のvvakameさんのとてくぶのタイトルあたりを使うのが良さそうです

* https://github.com/vvakame/graphql-with-go-book
* https://github.com/vvakame/C92-Splatoon2Guide
* https://github.com/TechBooster/C89-FirstStepReVIEW-v2

**Comment by kmuto** [comment]
立場としてはサードパーティのスタイルなので、てくぶさんでこれをどうしたいのかという判断に委ねつつ、なるべく協力していくという形になりそうです。

既存のjsbookベースの「完全な再現」を望むのか、これを機会に一新していろいろモダンな見た目にしていくのか。外部パッケージを積極的に使っていくのかTeXLive最小限にするのか。

**Comment by kmuto** [comment]
なので、このissueはTechBooster側で立ててもらうことな気がする…

**Comment by takahashim** [comment]
なるほど。ではTechBooster/ReVIEW-Templateの方に立てておきます。

**Comment by kmuto** [comment]
https://github.com/TechBooster/ReVIEW-Template/pull/22

**Comment by kmuto** [comment]
TechBoosterのほうでマージされました
