### ISSUE TITLE
「部」の中で見出しを使いたい

### ISSUE THREAD

**Issue by doublemarket** [kmuto/review#1195]
[catalog.ymlの書き方によって「部」を実現できる](https://github.com/kmuto/review/blob/master/doc/catalog.ja.md#catalogyml-%E3%82%92%E7%94%A8%E3%81%84%E3%81%9F%E5%A0%B4%E5%90%88%E3%81%AE%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95)わけですが、「部」のファイル(例えばpt01.re)内で `==` より深い見出しを使うと、`==`が次の「部」の見出しになってしまいます。

例えば以下のような構成にし、`= ほげ`から始まりその後`== ほげの次`という流れをpt01.reが含んでいる場合、

```
CHAPS:
  - ch01.re
  - pt01.re:
    - ch02.re
  - pt02.re
    - ch03.re
```

第1部が「ほげ」、第2部が「ほげの次」、第3部がpt02.reの`=`に書いた見出しと言うように、「部」の番号がずれてしまいます。ちなみに、`== ほげの次`の後に続けた本文が第2部の本文のようになります。

部の中に見出しを書く機会がそんなにあるのあるのかと言う気もしますが、実際そういう本を翻訳していて困った次第です。

**Comment by kmuto** [comment]
#1196 を作ってみました。master先端にはなりますが、可能でしたら試してみていただけますでしょうか。

**Comment by doublemarket** [comment]
@kmuto 早速ありがとうございます！ #1196 を手元で試して、意図したように部の中に見出しが来るようになりました。

**Comment by kmuto** [comment]
確認ありがとうございます！
ではmasterに入れちゃおうかな…
