### ISSUE TITLE
ブロック内等の「===」が見出し行としてHeadlineIndex.parseで処理される

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#121]
```
//emlist{
==============
test
==============
//}
```

といった記述の「==============」がHeadlineIndex.parseでは見出し行として認識され、しかもduplicate IDの警告が出ます（同じ見出しにみえるので）。

そうは言っても直すのは大変なのでwontfixですかねえ…

**Comment by kmuto** [comment]
今は別の、より妙な状況になりますね。

- 上記のemlistだけではエラー・警告にならず、正常に生成される。
- hdタグをどこかで使ったときに顕在化し、エラーも`ERROR -- : r.re:3: error: private method `warn' called for nil:NilClass`という助けにならないものしか出ない。

```
= section

//footnote[footnote_id][@<hd>{unknown}]

== subsection

//emlist[][rst]{
======
見出し
======
//}

=={unknown} hoge
```

unknown見出しの有無や、見出しの位置は関係なし。emlistの`======`を取ったり先頭スペースを入れたりすると正常になる。

**Comment by tk0miya** [comment]
https://gist.github.com/tk0miya/ca9ca030d50b4c9ae67d6bb6ed8aad71
の内容を vvakame/review docker イメージで処理すると、以下の warning が出ます。
`@<hd>` を削除すると warning はでなくなります。
```
docker run -it --rm -v `pwd`:/work vvakame/review bash -c "cd /work; review-webmaker config.yml"
warning: duplicate ID: subsection||||
content.re:3: error: unknown hd: unknown
```

**Comment by kmuto** [comment]
これ、HeadlineIndexでblockかどうかを判断してないのがまずいだけですね。手元で修正して今テスト中。

**Comment by kmuto** [comment]
#871にて修正
