### ISSUE TITLE
TeX: bouがエラーになる

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1220]
pxrubricaだと
```
! Argument of \pxrr@inter has an extra }.
```
という変なエラーになる。

`\textgt{・}`としているとダメで、たとえば（正しくはないけど）`{\bf ・}`などだといける。

`@<bou>`はもともとTeX用では使えるとはしていないものなので、3.1にて対処したいです。

**Comment by takahashim** [comment]
#1306 でLATEXBuilderの修正を入れました。
