### ISSUE TITLE
TeX: amssymbもデフォルトロードする?

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1224]
review-jsbook/review-base.styで amsmath のみを読み込んでいるが、amssymb も読んでも罰は当たらない気がする。

**Comment by munepi** [comment]
はい、amsmathを使うならば、amssymb も合わせて読み込んでおいてかまわないと思います。

``` latex
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsthm}
\RequirePackage{bm}
```

独り言：数式番号を左側に表示したり、数式インデントを中央寄せから左寄せにする場合は、できればクラスファイル側から統一的な変更ができるようにするのが望ましいです。さらに、amsmath を内部で読み込む newtx パッケージと組合せたいとかなると、なおさら、クラスファイル側から制御できるほうがよいです。（これを、Re:VIEW プロジェクト側で面倒見るか見ないかは、また別の話です。ここは、耳が聞こえないことにしておきたいです。）

**Comment by kmuto** [comment]
あ、review-jlreqだと入れてた（自分では特に理由はなくて、クラスファイル作りの練習だった…）。
