### ISSUE TITLE
#@mapfileによる分割ファイルの結合

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1247]
# 分割ファイルの結合問題
[Re:VIEW knowledge](https://review-knowledge-ja.readthedocs.io/ja/latest/faq/faq-usage.html#31ceaf88a38dd408528ffa99a1b48e1c)で、節単位にファイルを分割する例がありますが、2つの問題があります。

#@mapfileは、ソースコードなどの取り込みを目的としたもので、Re:VIEW原稿の取り込みを意図していないのではないでしょうか？上記サイトの説明に注意書きが必要と思います。

また、回避する方法はあるでしょうか？

# 問題が発生するサンプルコード
章ファイル（chap.re）の定義を次のようにします。
~~~
= 章見出し
#@mapfile(section1.re)
#@end
テスト終了
~~~

参照する節ファイル（section1.re）を次のようにします。
~~~
== TABLE

//table[id][テスト]{
年度	売上げ
---------------------
2017	1,000
2018	1,500
//}
~~~

# 問題1 : タブが消える

`review-preproc --replace chap.re` とするとchar.reにsection1.reを挿入しますが、タブコードがスペースコードに置換されるため、表定義のセル区切りが働かなくなります。その結果、意図した表にはなりません。

# 問題2 : 2回目のプリプロセッサでエラー発生

char.reにsection1.reを挿入した状態で、もう一度（最新の内容を取り込むため）`review-preproc --replace chap.re` とするとエラーが発生します。

> ERROR: chap.re:12: unbaranced #@end　

chap.reは、次のようになっています。
~~~
= 章見出し

#@mapfile(section1.re)
== テーブル

//table[id][テスト]{
年度      売上げ
---------------------
2017    1,000
2018    1,500
//}
#@end
~~~

#@mapfileで挿入する内容にブロック命令は想定していないのではないでしょうか？

**Comment by kmuto** [comment]
お返事遅くなりました。

> 問題1 : タブが消える

なるほど…これは厄介ですね。もともとmap系命令はコード挿入しか想定していない設計で作られたもののようなので、タブが消されてしまいます。でそうなると表が困るのは確かですね。

うーん。泥縄かもだけど拡張子を見て判定するか、オプションを新設するか、新命令にするか……
とりあえず拡張子を見る方法で実装してみようかと思います。

> 問題2 : 2回目のプリプロセッサでエラー発生

おっと、確かに再現しますね。`#@`はプリプロセスでのみ判定が正しいはずで、review-compileが変な解釈をしているのはバグと考えます。修正にトライしてみます。

**Comment by kmuto** [comment]
はい、まだリリース前なので、git cloneして実行してみる、ということになりますね。

macOSかLinuxで「ひとまず試してみる」という例を示すと…
```
$ cd 作業フォルダ (上記のchap.reなどがある場所へ移動)
$ git clone https://github.com/kmuto/review.git   (reviewフォルダができ、その時点の最先端が展開される)
$ review/bin/review-preproc --replace chap.re   (reviewフォルダのbin/review-preprocのほうを使ってみる)
```

**Comment by goto-yuki** [comment]
情報をありがとうございます。
fix-preproc ブランチをgit cloneして確認しました。
~~~
$ git clone -b fix-preproc https://github.com/kmuto/review.git
~~~

問題なく正しく動作することを確認しました。
ありがとうございました。

**Comment by goto-yuki** [comment]
#  2回目のプリプロセッサでエラー発生 (.re以外)
#@mapfile(XXX.re)はOKでしたが、
#@mapfile(XXX.c)はNGです。

対応前と同じエラーが発生します。

**Comment by kmuto** [comment]
はい、今回の措置は.reだけとしています。ただ*.cだとしても「入れ子になっている＝mapfileしたものの中にさらにmapfileがある」とか「*.cの中になぜかブロック記法がある」とかでなければ、こちらでは問題は生じていないのですが…。
全体でどのような構成になっているでしょうか。入れ子だとすると、それに対処するのは新規に作り直さないと難しそうです。

**Comment by goto-yuki** [comment]
失礼しました。

タブが消える問題の確認のために、XXX.reをXXX.cにリネームしてテストしてました。
「*.cの中になぜかブロック記法がある」状態でした。

従って、問題なく正しく動作しています。

**Comment by kmuto** [comment]
確認ありがとうございました、ではadhoc感はありますがこれで次バージョン（2月）に入れておきます。
