### ISSUE TITLE
LATEXビルダで奥付デザインが崩れる（Re:VIEW2.5はOK）

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1252]
# 奥付デザインの崩れ

Re:VIEW3において、LATEXビルダでPDFを作成したとき奥付デザインが崩れてしまいます。
Re:VIEW2.5では大丈夫でした。

## Re:VIEW３日本語の時

デザイン、イラストが途中で改行する

![r3-j](https://user-images.githubusercontent.com/46343265/51370727-63080080-1b3b-11e9-96a1-3aef95ad094d.jpg)

## Re:VIEW2.5 日本語の時（正常）
![r25-j](https://user-images.githubusercontent.com/46343265/51370754-85018300-1b3b-11e9-8a64-d9787a122636.jpg)

## Re:VIEW３英語の時
Illustratorなどフォントが重なる

![r3-e](https://user-images.githubusercontent.com/46343265/51370779-99de1680-1b3b-11e9-970a-33fd2dc5ef8d.jpg)

## Re:VIEW2.5 英語の時（正常）
![r25-e](https://user-images.githubusercontent.com/46343265/51370813-acf0e680-1b3b-11e9-8300-b4baaa6b392e.jpg)

**Comment by kmuto** [comment]
あぁ英語やほかの場合を考えていなかったですね…。
sty/review-base.sty 421行付近に
```
\begin{tabular}{p{3em}p{\dimexpr\textwidth-6em}}
```
というところがあると思います。`\begin{tabular}{ll}`とすれば2.5同様の動作になります。
ただしこの場合は右が長くても折り返されず、はみ出します。

tabularxを導入すれば両方を解決できるだろうか…。

**Comment by goto-yuki** [comment]
対応ありがとうございます。

colophon-widthブランチのreview-initで生成するsty/*を使用して問題が解決していることを確認しました。
