### ISSUE TITLE
[latex] \reviewimagecaption を用意してほしい

### ISSUE THREAD

**Issue by kauplan** [kmuto/review#1254]
### 概要

LaTeX Builderにおいて、`\reviewtablecaption` や `\reviewindepimagecaption` は定義されてるのに、`\reviewimagecaption` は定義されてないように見えます。
特に理由がないのであれば、`\reviewimagecaption` を定義して、`\begin{reviewimage} ... \end{reviewimage}` の中で `\caption` のかわりに使ってほしいです。
（動作確認バージョン：2.5、3.0）

### サンプル

入力例：

```
//image[example1][テスト用画像][scale=1.0]
```

変換例：

```
\begin{reviewimage}%%example1
\includegraphics[width=1.0\maxwidth]{./images/example1.png}
\caption{テスト用画像}  % ← これを \reviewimagecaption{} にしてほしい
\label{image:mybook:example1}
\end{reviewimage}
```

### 実例

たとえばtechboosterのテンプレートでは、ソースコードや表のキャプションには「▼」が使われ、図のキャプションにだけ「▲」が使われています。
このような場合、`\reviewimagecaption` があると素直に実現できます。

```
%% すべてのキャプションにつける、デフォルトの接頭辞
\def\capturesymbol{▼}

%% 図のキャプションだけ、接頭辞を切り替える
\renewcommand{\reviewimagecaption}[1]{
  {\def\capturesymbol{▲}\caption{#1}}   %% とても素直！
}
```

今は `\reviewimagecaption` がないので、かなり面倒な方法になってしまいます。

**Comment by kmuto** [comment]
なるほどたしかに。
なお、jlreqのほうではcaption装飾をクラスレベルでもっと簡単に宣言できるようになっているので、こちらに移行が進むといいですね…。
