### ISSUE TITLE
「#@warnタグ」 プリプロセッサで警告メッセージがでない

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1258]
# 「#@warnタグ」の用途？

フォーマットガイドより

> #@warn(〜) : 警告メッセージ。プリプロセス時にメッセージが出力されます。

原稿を書くとき、未完成の部分に#@warnタグでTBD.を書いています。

[testwarm.re]

```
#@# コメント

#@warn{TBD. 後で確認}

```

# プリプロセッサで警告とならない

プリプロセッサを実行しても、警告メッセージは表示されません。

コメントと#@warnは、同じ結果となります。

```
$ review-preproc testwarn.re
#@# コメント

#@warn{TBD. 後で確認}
$
```

EPUBビルドもPDFビルドでも警告は出ません。

# 改善（案）

プリプロセッサで警告メッセージを表示してくれれば、まだ原稿が完成していないことがわかります。

コードをみると#@warnタグをチェックしていますが、警告メッセージを表示していません。
異常なプリプロセッサタグは、警告メッセージを表示しています。
これでは、コメントと#@warnタグは同じだと思います。

[lib/review/preprocessor.rb]
```
        when /\A\#@/
          op = line.slice(/@(\w+)/, 1)
          warn "unknown directive: #{line.strip}" unless known_directive?(op)
          @f.print line
```

修正(案)
```
        when /\A\#@/
          op = line.slice(/@(\w+)/, 1)
          warnmsg = known_directive?(op) ? "preproc:" : "unknown directive:"
          warn warnmsg+" #{line.strip}" 
          @f.print line
```
プリプロセッサを --replaceオプションで使用すると、警告メッセージのみが表示されるので便利です。

**Comment by kmuto** [comment]
たしかに。
これも初期からあることになってるディレクティブで、gitログをおっかけてみたのですが、一度も実装されていた気配がないですね…。

**Comment by kmuto** [comment]
どう出力させるのが妥当そうに思います？＞ @takahashim

**Comment by takahashim** [comment]
確かにSVNから移行した（最古の）バージョンでも、format.txtで、

```
#@warn(...)
    警告メッセージ。プリプロセス時にメッセージが出力される。
```

という記載がありましたが、使われている気配がないですね…。

とりあえずreview-preprocでメッセージを出させるようにするのは悪くなさそうですが、それで十分かと言われるとあまり自信ないです（review-preprocはたまにしか使わないので）。

**Comment by kmuto** [comment]
require/provideも実は実装はないですね（たぶん青木さんの手元ツールのほうで何かやってたのだと思われる…）。こちらは今のpreprocのやり方では無理な気がしますし、単純にマニュアルから削除かな…。

**Comment by takahashim** [comment]
require/provideの方はreview-checkdepで使っているかと。

**Comment by kmuto** [comment]
む、そっちか。では削除のは戻しておきます
