### ISSUE TITLE
HTMLのdraftモードのとき、//comment{複数行}に＜br /＞が文字として入る 

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1264]
# 「//comment{複数行}」に&lt;br /&gt;が文字として入る

//comment{複数行}を書いたとき、draftモードでHTMLを生成すると&lt;br /&gt;タグが文字としてコメントの中に入ってしまいます。Re:VIEW3.0.0です。

[comment.re]
```
Ruby@<comment>{（？最新バージョンを確認）}をインストールします。

Re:VIEWの実行には、Rubyが必要です。
//comment{
？Rubyのバージョン
？Re:VIEWのバージョン
//}
Rubyは、オブジェクト指向スクリプト言語です。
```

draftモードでHTMLを生成します。
```
review-compile --draft --target html
```

---
[comment.htmlの内容]
![a](https://user-images.githubusercontent.com/46343265/52024104-e580bf00-2542-11e9-9414-1cbb599bb1ec.jpg)
---

## 期待する動作
下記のどちらかの動作を期待していました。

- ソースコードのように 書いた行がそのまま現れる
- 本文のように空行までがひとつの段落となる

**Comment by kmuto** [comment]
再現しました。

`//comment`の記法は本来1行想定の
```
//comment[〜]
```
なのをどこかで拡張したんだっけか…
重複エスケープになってしまっているところはわかったので対処します。

＃なお、個人的には、commentは見落としにつながりかねないので使用を推奨しないです。エディタハイライトで#@#を見たほうがよい。

**Comment by kmuto** [comment]
PR #1266 で修正を試みます。

**Comment by goto-yuki** [comment]
対応ありがとうございます。
comment-escブランチにて、//commentは「ソースコードのように 書いた行がそのまま現れる」ことを確認しました。

---

> commentは見落としにつながりかねないので使用を推奨しないです

* そうなんですね。私は、#@#と//commentを使い分けたいと思っています。
---

Re:VIEWの便利な使い方を求めて、いろいろ試しています。
