### ISSUE TITLE
epubmaker config.yml継承でback_footnote:が有効にならない

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1279]
# 脚注に「戻る」リンクが有効にならない

## 発生条件
- Re:VIEW3.1
- EPUBMaker
- config.ymlを継承

## 具体的な例

[config_new.yml]
```
inherit: ["config.yml"]
back_footnote: true
```

```
review-epubmaker config_new.yml
```

book.epubの脚注に戻るリンクが付きません。

config.ymlに直接「back_footnote: true」を記述すると戻るリンクが付きますので、config.ymlの継承の問題かと思います。

**Comment by kmuto** [comment]
back_footnoteはepubmakerセクション下のパラメータなので、継承するには

```
inherit: ["config.yml"]
epubmaker:
  back_footnote: true
```

となります。

**Comment by goto-yuki** [comment]
どうもありがとうございました。私のミスだったんですね。
「epubmakerセクション」を入れると正常に動作しました。
