### ISSUE TITLE
タイトルを指定した場所で改行したい

### ISSUE THREAD

**Issue by ryuzee** [kmuto/review#128]
yamlファイルでbooktitleを指定すると、それが文書のタイトルとして使われますが、特にreview-pdfmakerを使ってPDF出力をする際に、長いタイトルの場合に任意の場所でタイトルを改行したいのですが可能でしょうか？

たとえば、「Clean Coder プロフェッショナルプログラマへの道」というタイトルの場合、PDFの表紙では

Clean Coder
プロフェッショナルプログラマへの道

のように２行に渡って表示されるとうれしいのですが。

**Comment by seven0525** [comment]
【今後見る人用】
（自分が上の説明だけでは分からなかったので）

style/review-base.styの

```
\begin{titlepage}
       \thispagestyle{empty}
       \begin{center}%
       \mbox{} \vskip5zw
       \reviewtitlefont%
       {\Huge\review@booktitlename\par}%
       \ifdefined\review@subtitlename
         \vskip 1em%
         {\Large\review@subtitlename\par}%
       \fi
       \vskip 15em%
       {\huge
       \lineskip .75em
       \begin{tabular}[t]{p{\textwidth}}%
       \centering\review@titlepageauthors
       \end{tabular}\par}%
       \vfill
       {\large\review@date \review@intn@edition\hspace{2zw}\review@intn@publishedby\par}%
       \vskip4zw\mbox{}
       \end{center}%
       \end{titlepage}\clearpage
```

部分をコピーして、config.ymlと同じ階層に、「title.tex」ファイルを作って、そこに上の部分をコピペ。
６行目の部分を

```
{\1行目タイトル\\2行目タイトル\par}%
```

という風に変えて（\\が改行という意味）

あとは、config.ymlの133行目らへんのtitlefileに今編集した「title.tex」と書き込めば、OKですy。

**Comment by yam022** [comment]
pass:q[<br>] 　でタイトルを改行できるようです。
https://geekmusthave.com/?p=3160

**Comment by Mutsumix** [comment]
{\Huge 1行目タイトル\\2行目タイトル\par}%
でうまくいきました！ありがとうございます。

> ```
> {\1行目タイトル\\2行目タイトル\par}%
> ```
