### ISSUE TITLE
@＜hd＞で[notoc]見出しを参照すると番号が付く

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1294]
# @＜hd＞による見出し参照

次のようなtest.reでEPUBを作成すると、[notoc]の見出しにも番号が付いてしまいます。(Re:VIEW3.1.0)

## test.re
```
= 見出し参照

@<hd>{Lable1}と
@<hd>{Lable2}と
@<hd>{Lable3}に記載します。

=={Lable1} 見出しA

 
==[notoc]{Lable2} 見出しB

=={Lable3} 見出しC


```

## EPUBの結果

![hd](https://user-images.githubusercontent.com/46343265/56201266-7dd70c00-607b-11e9-8c87-4393e4a63c08.jpg)

## 期待した動作

@<hd>{Lable2}は、「見出しB」というように番号が付かないで欲しい。

**Comment by kmuto** [comment]
#1295 を作ってみました。お試しいただけますでしょうか。

**Comment by goto-yuki** [comment]
対応ありがとうございます。
$ git clone -b skip_notoc http://github.com/kmuto/review.git で、期待通りに動作することを確認しました。


* 仕様について
「headline解析でnotoc, nodispを飛ばす #1295」に書いてある「notocの下位にnotocではない見出しを付けたときの仕様」は、記載事項と異なる結果となりました。


```
【仕様】 Aは「1.1 A」、Bは「B」、Cは「1.1.1 C」、Dは「1.2 D」
        ↓  ↓  ↓  ↓
【実行】 Aは「1.1 A」、Bは「B」、Cは「 C」、Dは「1.2 D」
```
見出しの出力が「1.1 A」、「B」、「 C」、「1.2 D」となっているので、【実行】で良いと思います。

**Comment by kdmsnr** [comment]
nonum等のサブレベルの問題ですが、htmlの出力結果とhdの結果が違っちゃいますね。別イシューにするか、放置するか。。。ひとまずリオープンします。

```
= 見出し参照

@<hd>{B2}

== A

=== A2

==[nonum] B

=== B2

== C

=== C2
```

<img width="296" alt="Screen Shot 2019-04-18 at 0 35 33" src="https://user-images.githubusercontent.com/23315/56300994-e6081980-6171-11e9-822b-b3f2ecf00a75.png">

**Comment by kdmsnr** [comment]
これでいけそうですが、なんともいえない感じになりますね。

```diff
           next unless index >= 0
           if indexs.size > (index + 1)
-            indexs = indexs.take(index + 1)
+            unless %w[nonum notoc nodisp].include?(m[2])
+              indexs = indexs.take(index + 1)
+            end
             headlines = headlines.take(index + 1)
           end
           if indexs[index].nil?
```

**Comment by kdmsnr** [comment]
ひとまずPRです #1296

**Comment by kmuto** [comment]
#1296 とりこみました
