### ISSUE TITLE
`#@`を使うと段落が分割されてしまう

### ISSUE THREAD

**Issue by kauplan** [kmuto/review#1310]
段落の途中で `#@` を使ってコメントアウトすると、そこで段落が分かれてしまいます。

たとえば次の例では、本来なら1つの段落のはずなのに、2行目に `#@` をつかったため、段落が1行目と3行目で分かれてしまいます。

```
AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA
#@BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB
CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC
```

PDFへの変換結果（Re:VIEW 3.1）
https://imgur.com/e6b6bAJ

直感的には、`#@` を使って途中の行をコメントアウトしても段落が分かれない（上下の行がくっついたのと同じ動作になる）のが自然だと思いましたが、違うようです。

この動作はRe:VIEWの仕様でしょうか。
（バグ報告というより仕様の確認です。）

**Comment by kmuto** [comment]
はい、記録をたどったところ、compile_paragraph内であえて#@で分割するようにしており、仕様です。

```
段落
#@#
== 見出し
```

のような空行ナシデータのための対処ですね。

**Comment by kauplan** [comment]
Re:VIEWの仕様ということで、了解しました。

個人的には、これは仕様バグだという意見を表明しておきます。上に挙げられている例なら`== 見出し`の前に空行を入れればいいだけですが、段落を分割せずに途中の行だけをコメントアウトする方法が今のRe:VIEWには存在しないので。

なおご存知とは思いますが、LaTeXだと途中でコメント行があっても段落が分かれません。

```latex
AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA AAAA
%BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB BBBB
CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC CCCC
```

表示結果：
https://imgur.com/D0Qa7H4

またAsciiDocでも段落が分かれません。

```asciidoc
AAAA AAAA AAAA AAAA
//BBBB BBBB BBBB BBBB
CCCC CCCC CCCC CCCC
```

HTML変換結果(AsciiDoc 8.6.9)：
```html
<div class="paragraph">
    <p>AAAA AAAA AAAA AAAA CCCC CCCC CCCC CCCC</p>
</div>
```

ご参考までに。

**Comment by takahashim** [comment]
この件、現状のバージョンでは変化させない方が良さそうですが、次期バージョンでは再検討しても良いかもと思いました。
