### ISSUE TITLE
[bug] 箇条書きが`*`ではなく`**`や`***`で始められてしまう

### ISSUE THREAD

**Issue by kauplan** [kmuto/review#1313]
箇条書きは、通常は `*` で始めるが、`**` や `***` でも始められてしまう。
その場合、表示結果がおかしくなる。

例：
```
 *** foo
 *** bar
 *** baz
```

LaTeX変換結果（Re:VIEW 3.1）：
```latex
\begin{itemize}
\item

\begin{itemize}
\item

\begin{itemize}
\item foo
\item bar
\item baz
\end{itemize}

\end{itemize}

\end{itemize}
```

PDF表示結果：
https://imgur.com/SKRye6B

こんな表示になっても意味がないので、箇条書きが `**` や `***` で始まっていたらエラーにするのが望ましい。
（もちろん入れ子の箇条書きが `**` や `***` で始まるのは問題ない。今問題にしているのはトップレベルのこと。）

環境：Re:VIEW 3.1、Ruby	2.5、macOS Mojave (10.14.5)

**Comment by kmuto** [comment]
#1314 で対処予定です
