### ISSUE TITLE
キャプションの上・下の設定

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1320]
図・表・リスト（は各種）・式 にはキャプションが付きますが、内容に対して上か下かの指定ができないのが少々不便で、現状ではreview-extで無理矢理切り替えている状態です。

locale.ymlにはそぐわないので、config.ymlで設定することになりますが、どういうパラメータがよいのかという点で悩んでいます。

縦書きになると上・下じゃないので、before after みたいな名前がいいのかも？

**Comment by takahashim** [comment]
CSS的にはtop / bottomだそうです。

https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side
https://css-tricks.com/almanac/properties/c/caption-side/

**Comment by kmuto** [comment]
YAML側は
```
caption: {list: top, cmd: top, table: top, image: bottom}
```
だとどうでしょう。

`@book.config`ではこう見えるようになります。
```
"caption"=>{{"list"=>"top"}, {"cmd"=>"top"}, {"table"=>"top"}, {"image"=>"bottom"}}
```

**Comment by takahashim** [comment]
`@book.config`では、

```ruby
"caption_position"=>{"list"=>"top", "cmd"=>"top", "table"=>"top", "image"=>"bottom"}
```

となるのが良さそうですが、こうはならないんでしたっけ…？

**Comment by kmuto** [comment]
あ、
```
"caption_position"=>{"list"=>"top", "cmd"=>"top", "table"=>"top", "image"=>"bottom"}
```
になりました（コピペしたときに古いほうの結果を出してた）。

ではこの方向で実装してみますかね（キャプション自体がスペース空けてるスタイルあったかな…）。

**Comment by kmuto** [comment]
#1322 を作りました。

**Comment by kmuto** [comment]
#1361 で対応
