### ISSUE TITLE
PDFMaker: includeonlyが効かない

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1333]
Re:VIEWの問題ではないんですが、

時間のかかる大規模ドキュメントに対しTeXの\includeonlyで一部章だけのPDFを作りたいときに

```
\def\reviewprefacefiles{\input{maegaki.tex}
\input{yomikata.tex}
}
```
のようになっているのを
```
\def\reviewprefacefiles{\include{maegaki.tex}
\include{yomikata.tex}
}
```

と置換したところ、includeの内容が無視されて空になってしまいます。
includeはdocument環境内でないとダメ、ということかな…

**Comment by munepi** [comment]
@kmuto `\input` と `\include` の仕様と使い方異なります。

\input は、任意のファイルを挿入するのに対して、 `\include` は、（一般的に「章」の塊のある）LaTeX 文章を挿入します。

``` latex
%#!ptex2pdf -l -u
\documentclass[uplatex]{jsbook}
\def\reviewprefacefiles{%
\include{test-include1}%%\input{test-include1.tex}%
\include{test-include2}%%\input{test-include2.tex}%
}
\begin{document}

% \input{test-include1.tex}
% \input{test-include2.tex}

% \include{test-include1.tex}%%=> No file test-include1.tex.tex.
% \include{test-include2.tex}%%=> No file test-include2.tex.tex.

\reviewprefacefiles

\end{document}
```

`test-include1.tex` を `\input{test-include1.tex}` すると、 `test-include1.tex` を `\input` するだけです。

一方、`\include{test-include}` とすると、おおよそ以下のような動作をします。

1. `\clearpage` する。
2. `test-include1.aux` に書き込むためのファイル書込みオープンをします。
3. もし前回のタイプセットで生成された `test-include1.aux` が存在したら、 `\input test-include1.aux` します。
4. `\input test-include1.tex` します。
5. `\clearpage` します。

`\include` 内で与えられたLaTeX文章ファイルの拡張子 `.tex` を削る処理を要らられる余地があるかもしれませんが、現時点の仕様ではそうなっていないですね。
（ `\includegraphics{画像ファイル名}` の画像ファイル名の処理をみると、ファイル名と拡張子との区切りが `.` となっているのも厄介だなーと思ったり思わなかったり…。）

**Comment by kmuto** [comment]
おぉ!! ありがとうございます。たしかに拡張子取るのを忘れていました。
フツーのユーザ向けにincludeを使わせる意図はない(業務で時間のかかるビルド&確認作業をなんとかしたい)ので、フックで書き換えるので十分です。

汎用化するにはpdfmaker.rbのmake_input_filesを細工すればいちおういけなくはなさそうですが、includeonlyを挟み込むのをどうするかという問題がありますし。
