### ISSUE TITLE
common_code_block_lst の引数 id について

### ISSUE THREAD

**Issue by shishi** [kmuto/review#1343]
https://github.com/kmuto/review/commit/b8f682f1e591c3bea587cc5a3d70d492de504f6c#diff-44d680dbf9593fe8298ad27440a86d33R316

Re:VIEW 1.7に review-ext.rb 経由でモンキーパッチを当てて使用しているもののアップデートを行なおうとしている途中、`common_code_block_lst`にモンキーパッチを当てており、引数の変更に気がつきました。
現在のmasterでも`_id`となっており、引数の変更以来`id`は使われていないように見えるのですが、どのように使われるものなのでしょうか。

コード中で使われているように `nil` を入れてしまえば済むのかよくわからず、自家モンキーパッチについてのことで申し訳ないのですが教えていただければと…

**Comment by kmuto** [comment]
@takahashim さん修正の箇所なので私も記憶があいまいなのですが、

- make_code_blockと引数を合わせたいのがまずある
- ただ、common_code_block_lstに対応するLaTeXスタイル実装は今はidをまったく参照しない(自前で番号付けもする)形なので、結果的にidは使っていない
- ただ、common_code_block_lstをidベースで何か使うようにモンキーパッチするなら、idを使うようになるかもしれない
- とはいえ、この実装だと、むしろmake_code_block_argsまでidを引き継いだほうがいいのではという気はしている(キャプションをとっているのはここなので)

**Comment by shishi** [comment]
詳しくありがとうございます！ひとまず`nil`をいれても安心そうだと分かりました！
