### ISSUE TITLE
PDFMaker: @<code>, @<tt>などのコード系命令を使うと、空白が消えてしまう

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1348]
前にちょっと話題にしてたけど、結局Re:VIEW側ではちゃんと解決していなかったことに気づきました。

textttをマクロで包むと、スペース処理がなくなってしまい、潰れてしまいます。

案A
#1347 reviewtt, reviewcodeのみ、\RobustNewCommandではなく\letで\textttをコピーする形にして、包まない。○シンプル。× reviewtti,reviewttbが問題なまま。

案B
https://github.com/TechBooster/ReVIEW-Template/pull/36
をreview-base.styでも採用する。○reviewtti,reviewttbもOKに。途中改行もされて普通の人にはハッピー? ×途中改行が導入されることで後方互換性がなくなる。

実際のところ、手元の業務案件についてはjsbook+review-baseを使っていないので、どちらでもさして問題はないです。

**Comment by takahashim** [comment]
これは案Bでもいいかな…と思いました（どちらでもあまりこだわりはないです）。

**Comment by kmuto** [comment]
ではB案で。
