### ISSUE TITLE
メソッドの引数カッコ付け

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1357]
ところどころに
```
      source_header caption
      source_body lines, lang
```
というところがあるのですが、個人的にはメソッドは

```
      source_header(caption)
      source_body(lines, lang)
```

のように囲んでいるほうが、メソッドであることが明確で好みです。文法上カッコがなければエラーなりRubocopが怒るなりの場面もありますし、基本カッコ書きにしたいのですがいかがでしょう。

**Comment by takahashim** [comment]
Rubyのメソッド呼び出しのカッコについて、よく使われる規約は以下の4つくらいかと思います。

* a) 引数の個数に関わらず（0個でも）、あらゆるカッコをつける
* b) 引数がある場合はカッコをつける
* c) 引数が2個以上ある場合はカッコをつける
* d) 極力省略する

aとdは避けたいところです。
kmutoさんの提案はbですよね。
原則引数があればカッコをつける、で良いように思いますが、bはたまに不自然なところがあるかも。

**Comment by takahashim** [comment]
#1360 でrubocopによる変更を行ってみました。

省略を許しているのは https://github.com/kmuto/review/pull/1360/files#diff-11a0d7906801d9dea0eccb85667ad811R196-R214 の辺りです。

**Comment by kmuto** [comment]
お、bであってます。ありがとうございます。

**Comment by kmuto** [comment]
#1360  マージしました
