### ISSUE TITLE
Re:VIEW 3.2 + jlreqでcmdの2ページ目以降が黒塗りになる

### ISSUE THREAD

**Issue by m-shibata** [kmuto/review#1363]
Re:VIEW 3.2 + jlreqの環境で、ページをまたぐ大きなcmdブロックを作ったとき、2P目以降のcmdブロックの文字色が白から黒に変わってしまうようです。

## 再現手順

```
review-init --latex-template=review-jlreq test
cd test
echo -e "= テスト\n\n//cmd{" >test.re
for i in `seq 50`; do echo "line $i" >> test.re; done
echo -e "//}" >>test.re
rake pdf
```

## 補足情報

* 使用しているTeX LiveはUbuntu 19.04の2018.20190227-1です
* uplatex/lualatex双方で再現しました
* jlreqはabenori_devの最新でも、20190507、20190401いずれでも再現しました
* jsbookで再現するかどうかは未確認です
* cmdブロック以外でも発生するかどうかは未確認です

**Comment by m-shibata** [comment]
再現手順で作成したPDFを添付しておきます。

[book.pdf](https://github.com/kmuto/review/files/3499959/book.pdf)

**Comment by kmuto** [comment]
はいはい。これtcolorboxの厄介めなヤツですね。調査して対策を考えます。

**Comment by m-shibata** [comment]
tcolobxの中で`\color`を使うと、Re:VIEWのスタイルに関係なく起きるようです。

たとえばreview-base.styの中では次のようになっていました。

https://github.com/kmuto/review/blob/master/templates/latex/review-jlreq/review-base.sty#L34

```
\newenvironment{reviewcmd}{%
  \begin{tcolorbox}[skin=enhanced jigsaw,breakable,colback=black!99,colframe=black!99,boxrule=0mm,arc=0mm]\begin{alltt}\begingroup\color{white}\ignorespaces}%
 {\endgroup\end{alltt}\end{tcolorbox}}
```

これをcoltextを使うようにすると、とりあえず表題の問題は発生しなくなるようです。

```
\newenvironment{reviewcmd}{%
  \begin{tcolorbox}[skin=enhanced jigsaw,breakable,colback=black!99,cotext=white,colframe=black!99,boxrule=0mm,arc=0mm]\begin{alltt}\begingroup\ignorespaces}%
 {\endgroup\end{alltt}\end{tcolorbox}}
```

**Comment by kmuto** [comment]
ですね!

**Comment by m-shibata** [comment]
テスト用に使ったTeXファイルも拡張子を変えて添付しておきます。

[tcolbox.txt](https://github.com/kmuto/review/files/3500109/tcolbox.txt)
