### ISSUE TITLE
@<column>{}を使うとPDFでは"コラムコラム「タイトル」"になってしまう

### ISSUE THREAD

**Issue by m-shibata** [kmuto/review#1367]
`@<column>{}`でコラムを参照した際、PDFでは"コラムコラム「タイトル」"と出力されてしまいます。

## 再現手順

```
review-init --latex-template=review-jlreq test
cd test
echo -e "= テスト\n\n@<column>{test}\n\n" > test.re
echo -e "==[column]{test} テスト\n\nコラム\n\n==[/column]\n" >> test.re
rake pdf
```

手順ではreview-jlreqを使っていますがreview-jsbookでも結果は同じでした。

## 出力結果

![Screenshot from 2019-08-15 21-28-57](https://user-images.githubusercontent.com/998856/63094574-ceb42e00-bfa3-11e9-987b-4d6e8eb1935c.png)

## 考察

出力されたTeXは以下のとおりです。

```
\reviewcolumnref{コラム「テスト」}{column:test:1}

\begin{reviewcolumn}[テスト\hypertarget{column:test:1}{}]
\addcontentsline{toc}{section}{テスト}
```

これはLaTeXBuilderの以下の部分で生成しているようです。

https://github.com/kmuto/review/blob/b4c3da9e45e2b4150167fba5f41df9c8ece40155/lib/review/latexbuilder.rb#L1138-L1140

またreviewcolumnrefはreview-base.styで次のようになっています。

https://github.com/kmuto/review/blob/68737e92d4d8da763515e320147bd45511e744d8/templates/latex/review-jsbook/review-base.sty#L208
https://github.com/kmuto/review/blob/3e025de8161a6d9f31647cf13fe50ccee06855c4/templates/latex/review-jlreq/review-base.sty#L118

これらで使われているcolumnとcolumnnameはi18n.ymlからやってきています。
https://github.com/kmuto/review/blob/dea5020e8fe23c942d182e9e0ff44e1b0bc2a549/lib/review/i18n.yml#L6-L7

結果、"コラムコラム「タイトル」"な出力になっているようです。

他のビルダーと合わせるなら、review-jsbookとreview-jlreqのreview-base.styからcolumnnameをなくしてしまえば良いように思うのですが、いかがでしょうか？

**Comment by kmuto** [comment]
そのとおりですね。そうします。
