### ISSUE TITLE
PDFMaker:コラム内のfnに対する//footnote位置がコラムの中にあると採番がおかしくなる

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1379]
実際できるかどうかというと木構造を作らない限り厳しそうなのと、うっかりかそうでないかでの判断がしづらいところはある。

- Re:VIEW3では、コラム内で`@<fn>`を使ったとして、その脚注本体である`//footnote`はコラムの「後」にあることを想定し、展開すると、`\footnotemark`と`\footnotetext`になるようにしている。これは表などと同様に採番を本文から通すための措置であるとともに、囲み系(およびキャプションや表)の脚注に伴うさまざまな問題から避けるため。
- しかし、これに気付かずに`//footnote`をコラムブロックの中に入れてしまうと、a,b,c採番になる。悪いことに、かつ `\footnotetext` 化もされているため、たとえば本文で3まで進んでいたならコラム内脚注は4→英字化されてd、次の本文のほうはアラビア数字5というふうになってしまう。そして28まで進んでいるとzの先になって奇妙なエラーになる。
- コラム内の場合に採番が変わるというのはTeX固有の問題であり、ほかのビルダではすべて通し番号。

対策

- A: PDFMakerでコラムの中に//footnoteがあったら警告かエラーにする。
- B: コラムの中に//footnoteがあったら本文とは別個にしてa始まりにする。できるかは不明。あと、囲みの作り方によっては脚注が表示されずに消えそう。ほかのビルダと挙動が違う。
- C: コラムの中にあったらコラムの外に移動する。できるかは不明。囲みスタイル実装側のことなので、Re:VIEW側でTeXソースをごちゃごちゃいじるというのはスタイルに縛られて嫌め。

と考えるとAでlatexbuilderのみWARNするくらいがよいのだろうか。

**Comment by kmuto** [comment]
これ、Re:VIEWのreview-jsbookのコラムだとframed環境だからカウントに何も影響しないんだけど、techboosterスタイルみたいにtcolorboxだと顕在化する問題ですね。

**Comment by m-shibata** [comment]
review-jlreqのコラムもtcolorboxなので、警告だけでもあるとうれしいです。
