### ISSUE TITLE
review-jlreqにおけるgentombow.sty/jsbook.cls

### ISSUE THREAD

**Issue by m-shibata** [kmuto/review#1381]
`review-init --latex-template=review-jlreq`でビルドすると、styディレクトリに「gentombow.sty」と「jsbook.cls」がコピーされますがこれは必要でしょうか？

  A. 不要なもので、コピーしないようにするのが望ましい。
  B. 不要ではあるが、何らかの理由によりわざとreview-jsbookと同様にコピーしている。
  C. 必要なもの。

あって困るものでもないので、今のままでも特に問題となるわけではないのですが、A.のように不要なら削除してしまったほうが混乱がないかなと思い、報告させていただきました。

https://github.com/kmuto/review/blob/c6a103cea47f68001f05551b62a209ff3ecaf1c7/lib/review/init.rb#L163-L173

もし修正するとなると、上記において`if @template == 'review-jsbook'`のとき（もしくは`if @template != 'review-jlreq`のとき）にのみ、`FileUtils.cp`を呼ぶ形の変更になるかと思います。

**Comment by kmuto** [comment]
そうですね、==のときにcp、は自然なのでそうします。
