### ISSUE TITLE
review-jlreqだと偶数ページに隠しノンブルが入らない

### ISSUE THREAD

**Issue by m-shibata** [kmuto/review#1395]
review-jlreqでhiddenfolioを指定すると、偶数ページにのみ隠しノンブルが挿入されないようです。
uplatex/lualatexどちらでも発生しました。review-jsbookだと問題ありません。

## 再現手順

```
review-init --latex-template=review-jlreq test
cd test
sed -i 's/^\(texdocumentclass.*\)"]$/\1,hiddenfolio=nikko-pc"]/' config.yml
rake pdf
```

## 備考

たとえばreview-jlreq.clsの`\@bannertoken`を次のように変更しても、奇数ページにのみtestが表示される状態でした。

```
\@bannertoken{test}%
```

そのためjlreq-trimmarks.sty側かその使い方の問題かもしれません。

試しにhiddenfolioは指定せずに、review-custom.styで以下のように記述すると、偶数ページにも隠しノンブルが表示されました。

```
\if@pdftombo
\jlreqtrimmarkssetup{
  banner={
    bottom-left={
      in-yoko={
        odd={\thepage}
      }
    },
    bottom-right={
      in-yoko={
        even={\thepage}
      }
    }
  }
}
\fi
```

**Comment by m-shibata** [comment]
環境が抜けていました。

* Re:VIEW: masterのHEAD
* TeX Live: Ubuntuパッケージ版のTeX Live 2018
* jlreq: abenori_devブランチの最新

**Comment by kmuto** [comment]
confirmed. はてさて…

**Comment by kmuto** [comment]
なるほど、jlreq-trimmarks.styの仕様が変わって、だいぶ複雑になっていますね。
これまでのbannerマクロ定義だとoddページにしか配置されなくなっている、と。

sty/review-jlreq.cls の70行目に以下のように`\jlreq@trimmarks@banner@even@yoko@top@left`を入れるとどうでしょう？(いささか泥縄ですがjlreq-trimmarks.styを見るかぎりではこれでいいはず…)

```
  %% redefine to output \@makehiddenfolio for every page
  \@bannertoken{\hskip-5mm\smash{\hiddenfolio@font\@makehiddenfolio}}%
  \def\jlreq@trimmarks@banner@even@yoko@top@left{\hskip-5mm\smash{\hiddenfolio@font\@makehiddenfolio}}%
```

**Comment by kmuto** [comment]
順序が逆で、

1. review-jsbookでhiddenfolioを実装。review-jlreq+当時のjlreq-trimmarksも同じ実装で動いていた
2. それからしばらくしてjlreq.cls開発者のabenoriさんと「隠しノンブルなにそれ怖い」という話をした結果、「こんなのどうよ」とjlreq-trimmarksのbannerが書き直された
3. これにより1.の実装が動かなくなった

なのです。
jreq-trimmarksに合わせるのがいいんですが、だいぶ実装と設定方法が違うので、新実装は今はすぐにはできないです(patch welcome)。とりあえず暫定対処で上記のを入れておこうかと思います。

**Comment by m-shibata** [comment]
> 「こんなのどうよ」とjlreq-trimmarksのbannerが書き直された

なるほど、bannerの登場があとだったんですね。

> とりあえず暫定対処で上記のを入れておこうかと思います。

よろしくお願いいたします。banner版は、自分でできそうだったら折りを見て別途PRを立ててみます。

**Comment by munepi** [comment]
`hiddenfolio=<profile>` を書くと、 `jlreq-trimmarks` に合わせた `<profile>` を与えるようにする必要がありそうですね。
