### ISSUE TITLE
後方互換処理がうまく動いていない

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1414]
config.erbで

```
\def\reviewbackcompatibilityhook{
  \@ifundefined{reviewimagecaption}{% for 3.0.0 compatibility
    \newcommand{\reviewimagecaption}[1]{\caption{##1}}
  }
  \@ifundefined{reviewincludegraphics}{% for 3.2.0 compatibility
    \DeclareRobustCommand{\reviewincludegraphics}[2][]{%
      \includegraphics[##1]{##2}}
  }
  \@ifundefined{covermatter}{% for 4.0.0 compatibility
    \def\covermatter{}
  }
}
```

という処理をして不足マクロを補っているつもりだが、ifundefinedのブロックの3つのうち

- 3つ全部だとこのマクロの途中になってしまうようで `./__REVIEW_BOOK__.tex:79: LaTeX Error: Missing \begin{document}.`になってしまう。
- 3つコメントアウト→OK
- reviewimagecaptionのみ→OK
- reviewincludegraphicsのみ→OK
- covermakerのみ→OK
- reviewimagecaptionとreviewincludegraphics→OK
- reviewincludegraphicsとcovermatter→Missing begin documentエラー
- reviewimagecaptionとcovermatter→OK
- reviewincludegraphicsの内部2行をコメントアウト→Missing begin documentエラー

というよくわからない現象が発生する。

`\@ifundefined`の挙動を私が理解していないせいだと思うけれども、とりあえずifdefinedのelse句のほうで対処すれば希望動作にはなりそう。

**Comment by munepi** [comment]
@kmuto ちょっと追いきれていなくて、 `\reviewbackcompatibilityhook` だけ見ただけで申し訳あにですが、
`\@ifundefined{<comand name>}{未定義のときの処理}{定義済のときの処理}` なので、以下のようにしたら、武藤さんが試されたケースのうち、エラーになったケースが正しく通ったりしませんか？

``` tex
\def\reviewbackcompatibilityhook{
  \@ifundefined{reviewimagecaption}{% for 3.0.0 compatibility
    \newcommand{\reviewimagecaption}[1]{\caption{##1}}
  }\relax
  \@ifundefined{reviewincludegraphics}{% for 3.2.0 compatibility
    \DeclareRobustCommand{\reviewincludegraphics}[2][]{%
      \includegraphics[##1]{##2}}
  }\relax
  \@ifundefined{covermatter}{% for 4.0.0 compatibility
    \def\covermatter{}
  }\relax
}
```

**Comment by kmuto** [comment]
あーなるほど、ifundefinedはelseもとるんですね…。relaxでいったん切っちゃえばいいのか、ありがとうございます。
とりあえず変更済み #1415 のifdefined-elseにしたほうが可読理解性はよさそうなので、それでいこうと思います。
