### ISSUE TITLE
表のセル区切り文字(正規表現)の任意指定

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1420]
表のセル区切り文字を用途に応じてカスタム化できる(たとえば\s+にする)ようなパラメータを入れるのはどうか、と考えています。

splitのところに入れるRegexp文字列を指定するイメージ。
https://review-knowledge-ja.readthedocs.io/ja/latest/faq/faq-usage.html#02eab96e754cf82ccc15cb2a50e9efa0

**Comment by kmuto** [comment]
@takahashim 
こちら入れちゃっていいですかね。

**Comment by takahashim** [comment]
どちらかというと正規表現で指定するよりは文字で指定する方が安全な気がしますね…。でも、強い意見はないです。

**Comment by kmuto** [comment]
文字指定だと任意個数とか空白有無無視とかが難しいんですよね…。

**Comment by takahashim** [comment]
構文要素として自由な正規表現をユーザが与えられるようにすると、parserを書き直すのにハードルがだいぶ上がってしまいそう（少なくともふつうのPEGとかでは記述できなくなる）なのが気になっております。
とはいえparser書き直しがいつになるか分からないのがアレなわけなんですが…その時に考え直す感じでしょうか。

**Comment by kmuto** [comment]
そうですねぇ… 使えなくする可能性があるという前提でのexperimental featureということで。
現状ではescape済み文字列に対しての区切りにしないといけないなど、いろいろ辛いところがあるので、あくまでも「わかった上で使う」ということにしたいと思っています。

**Comment by kmuto** [comment]
実際のところやりたいこととしては \t+ と \s+ を切り替えられるようにしたい(あと本当はできれば\s*\|\s*)ということなので、このパターン切り替えを指定できればいいのかな。
できれば表ごとに指定できるといいんですが、それには表オプション指定方法の問題があります。

**Comment by kmuto** [comment]
複数からの選択でもPEGには厳しいでしょうか。それとも有限個に収まってくれればOKでしょうか。

**Comment by takahashim** [comment]
`'a'`とか`'abc'`とか`'ab' | 'ac'`みたいなのは大丈夫です。

**Comment by kmuto** [comment]
もともとデフォルトは「\t+」だったみたいなんですが、実は困る…？

**Comment by takahashim** [comment]
あらかじめ決め打ちのパターンであれば、それにあった文法を事前に（手で）書けるので、ふつうの正規表現くらいであれば問題なさそうです。
ユーザが与えられるようにすると、そういうこともできないので厳しくなるのでした…。

**Comment by kmuto** [comment]
なるほど、では決めうちパターンから選ぶ、で実装し直してみますね。
