### ISSUE TITLE
media=ebook のときにヘッダで @<code> を使うと PDF ビルドが失敗する

### ISSUE THREAD

**Issue by uchan-nos** [kmuto/review#1432]
Re:VIEW 4.0.0 を使っています。

`review-init code-build-error` で生成したまっさらなディレクトリで再現しました。
次のようにヘッダに `@<code>` を入れたシンプルなファイルを書きます。

    $ cat code-build-error.re 
    = @<code>{a}
    $

`config.yml` の `texdocumentclass` 設定を `media=ebook` と変更して `rake pdf` するとエラーが発生します（エラーログは別ファイルとして添付）。 `media=print` のままならエラーになりません。
Re:VIEW 3.2.0 ではエラー無くビルドできていましたので，4.0.0 で挙動が変更されてしまったのだと思っています。直ると嬉しいです。

[build-error.log](https://github.com/kmuto/review/files/3965623/build-error.log)

**Comment by kmuto** [comment]
あぁ、これまた厄介ですね。reviewcode/reviewttで内部の空白保持と文中折り返しができるようにしているのですが、hyperrefの中になると展開に失敗してエラーになってしまう、と…。

**Comment by uchan-nos** [comment]
なるほど… #1348 の修正によって発生してしまった症状ということですね。

とりあえず，手元で sty/review-base.sty を次のように修正して回避できることは確認しました。（reviewcode 命令を3.2.0 時代の定義に戻してみた）

    %\DeclareRobustCommand{\reviewcode}[1]{{\ttfamily\reviewbreakall{#1}}}          
    \DeclareRobustCommand{\reviewcode}[1]{\texttt{#1}}

**Comment by kmuto** [comment]
はい、もしreview-custom.styで上書きとするなら
```
\renewcommand{\reviewcode}[1]{\texttt{#1}}
```
ですね。さて困りました…

**Comment by kmuto** [comment]
ひとまずrevertぎみにしたものを #1434 としてマージしました。
リリースまでにもう少し粘ってみようとは思いますが、そのときまでにダメなようなら #1434 で対処したものとしてこのissueはcloseしますね。

**Comment by kmuto** [comment]
#1435 でbreakallの機能を保ったまま解決されました!

**Comment by uchan-nos** [comment]
素早いご対応ありがとうございました！

**Comment by kmuto** [comment]
なんか命令によって再発している気がする…

**Comment by kmuto** [comment]
`@<u>`がダメだった。これは見出しに登場することはないだろうから仕様として無視することに。

**Comment by munepi** [comment]
@kmuto 
推測ですが…、Re:VIEW の標準における `@<u>` は、`jumoline` 経由の下線だったはずです。

> @<u>がダメだった。これは見出しに登場することはないだろうから仕様として無視することに。

`jumoline` などを使おうが使わまいが、特別な意味で下線付きの記法を必要とする見出しは皆無であるはずだと思いますので、`hyperref` のhook自体に、 `\<underline-like csname>{#1}` を `#1` だけにするとかやっておいても良いかもしれませんね。

**Comment by kmuto** [comment]
@munepi 
はい、\reviewunderline→\Underlineと展開していますね。

うーんそうですね、\pdfstringdefPreHookに危なそうなものを入れていけばいいのかな。
