### ISSUE TITLE
appveyorを少し削る？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1437]
@takahashim 

- 実行見てると、rubocopの実行に少し詰まるところがある。actionsでrubocopは済んでいるので、rubocopでWindows上でしか動かない何かがあるのでなければ実行不要？
- バージョン固有の検出はactionsで済んでいると思われるので、ruby_versionは最新だけでもよさそう？

**Comment by kmuto** [comment]
2.7が出たので、2.6・2.7くらいでいいかも

**Comment by takahashim** [comment]
これはGitHub ActionsをWindowsで動かして解決したいところなのですが…。もう少し試してみますか。

**Comment by takahashim** [comment]
これですが、GitHub ActionsでWindowsが動かなかった原因としては、

* パスの比較時に短縮名(`runneradmin`を`RUNNER~1`みたいにするやつ)が使われると正しいはずのときに失敗する
* 標準のpowershellだと終了時の成功・失敗の状態取得が微妙で、bashにすると安定する(powershellだとexit(true)だと失敗になるぽい？)
* ファイルサイズの比較時に行末等の変換が起きるとサイズが変わる

などが問題になっていたようでした。これらを修正・回避したものが #1460 です。

**Comment by kmuto** [comment]
#1460 をもってOKそうです。ありがとうございました。
