### ISSUE TITLE
バッククォートを表示する

### ISSUE THREAD

**Issue by sugi2000** [kmuto/review#1480]
TeXの問題だとおもいますが、本文中に「バッククォート」（`）をそのまま表示したいときはどのようにすれば書けるのでしょうか。

``` @<tt>{html``} ```

**Comment by sugi2000** [comment]
一応解決できました。
全角スペースをつづけているので上に表示されてしまいますが。

@<raw>{|latex,html|\`　\`　}

**Comment by kmuto** [comment]
https://review-knowledge-ja.readthedocs.io/ja/latest/faq/faq-tex.html#94b40797bbe5b0b87c28b5c8c7fb5e8d が対処に相当しそうです。

**Comment by sugi2000** [comment]
ありがとうございます。コードリストではなくインラインで表示する方法をさがしていました。
以下でやりたいことができました。

@<raw>{\`{ \}}
