### ISSUE TITLE
review-index, review-volの再構築

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1485]
- review-index, review-volともにインライン命令・特に参照系があるときにエラーになったり変な結果になったりする
- TOCParserが本文のパーサとは別になっていて簡略化版になっているのが原因
- review-indexの「見出し目次一覧」がわかりづらいので全部書き換えても
- 章のボリュームをはかるreview-vol、各節までブレイクダウンして見せるreview-indexというコマンドの目的自体は変えたくない

review-vol はこれでいけそうです。

```diff
 def print_chapter_volume(chap)
+  printer = ReVIEW::TextTOCPrinter.new(0, @config)
   vol = chap.volume
-  title = chap.title
-  printf("%s %3dKB %6dC %5dL %3dP %s %-s\n",
-         chapnumstr(chap.number), vol.kbytes, vol.chars, vol.lines, vol.page,
-         "#{chap.name} ".ljust(25, '.'), title)
+  title = printer.print_chapter(chap)
 end
```
肝心のページ数表記がなくなりましたが…… ``TOCPrinter`` の ``printf`` に ``vol.page`` を追加すればいいので、いっそのこと review-index と統合してもよいかもしれません。

_Originally posted by @kdmsnr in https://github.com/kmuto/review/pull/1484#issuecomment-590675576_

**Comment by kmuto** [comment]
@kdmsnr 
review-indexで苦戦しているんですが、使い方として、

- A. 節・項の一覧を出したい
- B. 各節・各項のバイト数・行数を知りたい

を現在機能提供しているけれども、Bについてはどの程度の利用があるでしょうか(私自身はA.の機能しか使ってない)。

A.だけなら実装はそう複雑にならずに済むんですが、B.はロジックみるにかなりバグが多く(//ブロック命令内の処理など)そもそもが当てになる数字を出せてない気がしています。で、まじめに出そうとするとパーサ部分を全部本物のほうに寄せないといけなくてかなり大掛かりになりそう。

あとIndexという名前が適切なのか、という気もしますね。クラス名と同じくreview-tocにして目次情報を出すんだ、という意図にしたほうがよいかも？

**Comment by kdmsnr** [comment]
* 私もAだけでよいと思います。
* ただ、セクション単位の行数を知りたいという需要がないとも言い切れません。review-volだと章単位だけですし。現状の値で納得しているなら、参考値として現状のままでもよさそうですけども。
* 名前は review-toc がよさそうです。

**Comment by takahashim** [comment]
（review-indexもreview-volもほとんど使ってないので、仕様についてはあまり意見がないです…）

**Comment by kmuto** [comment]
review-tocができました。#1487

- デフォルトは見出し一覧
- -dオプションを付けると詳細ボリュームなど表示

今週中にマージ予定です。

**Comment by kmuto** [comment]
#1487 で対処
