### ISSUE TITLE
==[note]とか追加する?

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1493]
デフォルトでの見出し拡張はあまり増やしたくはなかったのですが、
//note{などが複雑なものに対処できないのを手元でいろいろ小手先でいじるのもよくないので、記法として許容したほうがいいかなという気にはなってきました。

まだ実装はしていないですが、review-indexやhdあたりの解析に影響を及ぼすかもしれないのには注意が必要そうです。
これも構文木には何か影響しそうでしょうか。

あと、ほぼ同じロジックをコピペすることになりそうなのは何かトリックを使ったほうがいいですかね。

**Comment by takahashim** [comment]
#1495 で、

```
==[note] bbb

//note{
n1
//}
 
===[note] ccc

//note[ddd]{
n2
//}
```

とかをビルドすると以下のようになるのですが、こういうのは許容しない方がよいですか？

![nested-memo](https://user-images.githubusercontent.com/10401/79067728-7a14ae80-7cfc-11ea-869d-7f75f17ef468.png)

**Comment by kmuto** [comment]
うーん、その形は許容はしたくないですが、「今どの階層にいる」という情報は現状の仕組みだと持っていなくて、前に考えたとき(キャプションまわりだっけかな)も現状のに何か無理矢理階層情報を入れるのはやめようということになりましたよね。
構文木を使った構造にできれば対処できるのでしょうが…。

**Comment by kmuto** [comment]
ネストを禁止するようにしてみました。

**Comment by kmuto** [comment]
https://github.com/kmuto/review/issues/1502#issuecomment-650522414

> 現状のブロック記法の入れ子を許す（ように頑張る）
> 違うブロック用記法を導入する
> の方が良いかと思うのですが、どっちが現実的なんでしょうかね…。
