### ISSUE TITLE
固有のYAML設定のLaTeXへの引き渡し

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1505]
## やりたいこと
任意のYAMLパラメータをPDFMakerにもうちょっと渡しやすくしたい。

## 背景
現在、config.ymlからPDFMakerへの引き渡しは templates/latex/config.erb で特定の範囲の設定のみを取り込んでTeXマクロに変換し、pdfmaker#latex_config を通して layout.tex.erb 内に貼り付ける という構成にしている。
そのため、任意のYAML設定を使いたいときには、

- layout.tex.erbごと差し替える
- pdfmaker#latex_config をreview-extでオーバライドする
- hookで__REVIEW_BOOK__.texを書き換える
- hookでYAMLパラメータを取り込んで sty/review-custom.sty などに書き出す

といった、いささか大袈裟 or トリッキー な処理が必要となる。
(YAMLの設定名およびデータ構造とTeXのマクロとで一対一対応にさせるのはほぼ不可能。)

## 解決案
- layouts/config-local.tex.erb というファイルがあったらそれも取り込むようにする。中身はconfig.erb同様で任意にマクロ対応を記述する。記述およびエラーの責任はユーザが持つ。

## 考えられる問題
- erb通してなんでもできることになるので、セキュリティ的にはよろしくない(が、フックとか-shell-escapeとか穴はいくらでもあるので…)。
- config-local.tex.erb という名前はダサイ？
- review-init実行後では存在せず、ドキュメント化はするにしても気付かれなさそう。(自分が使えればいいので別に構わないが)

**Comment by takahashim** [comment]
具体的なユースケースは分かってないのですが、結局review-ext.rbと同程度にポータビリティの低いしくみにしかならなさそうなので、review-ext.rb＋α（独自のYAMLやJSONの設定ファイル等）でもいいかも？とは思いました。

それともconfig.erbのマッピングルールを整理して、もうちょっと柔軟にするべきでしょうか（そのくらいの拡張性で間に合うのであれば）。

**Comment by takahashim** [comment]
でもあんまり変なマッピングルール＋命名規則を作っても使いにくそう…という気もしますね…。

**Comment by kmuto** [comment]
はい、マッピングルール作るといろいろ辛そうだなぁという感じです。
目的としては、今のreview-jsbook, review-jlreqとは別にYAMLでカスタマイズできるclsを作ろうと考えています(Re:VIEWコアに入れるかというと微妙なところで、拡張的な位置付けのプロジェクトにしようかなとは思っています)。そのときにreview-ext.rbだとだいぶゴチャゴチャしそうなのでした。

**Comment by kmuto** [comment]
最近review-ext.rbでなんでもやれるだけに魔改造してしまって後々困るようなケースが見受けられるので、パラメータのバインディングなどのありきたりなところはなるべくインタフェースを設けたほうがよいのではという方向を考えつつあります。layout.tex.erb差し替えは無駄すぎるし、コア側で変えたときの追従がしづらい。

**Comment by takahashim** [comment]
ちなみにそのYAMLは、PDFMaker以外ではどうハンドリングするんでしょうか？

**Comment by kmuto** [comment]
ほかのMakerだと今のところ、独自のYAML設定で何か挙動を変えたいというシチュエーションがほとんどないんですよね…。とりあえず今のRe:VIEWでは知らないYAML設定は単に無視するんで、あまり困らなそう。

クラスファイル側はまだ全然詰めてないですが

```
fooclass:
  font:
    bold: ["SourceHanCodeJP-Medium.otf", "Helvetica.otf"]
  style:
    note: doubleround
```

みたいな想定です。

**Comment by takahashim** [comment]
うーん、共用しないでLaTeXからしか使わないのであれば、(La)TeXのマクロをそのまま*.styに書いて読み込んだ方が、Re:VIEWのバージョンにも依存しなくて確実だったりするんではないでしょうか？
あるいは実行タイミング等に問題があったりするんでしょうか。

**Comment by kmuto** [comment]
出力結果としてはsty相当にはなるんですが、
エスケープやパラメータ分解・解析などを全部TeX言語で組むのは困難なので、Ruby言語で記述したいと思っています。
sty/*.sty.erb を許容するならそれでも済みますが、前に考えたときはこれは避けたいということになってましたっけ。

**Comment by kmuto** [comment]
どうしましょうかね。

**Comment by takahashim** [comment]
あっとすみません。
まだ必要性について理解できてないんですが、使うんだったら入れざるを得ないと思うので、実際に近いテストケースと一緒に入れてもらえればいいのかな…と思いました。

それはそれとして、使用していることがconfig.ymlで分かるといいかなとも思いましたが、これ以上設定項目増やすのもうれしくなさそうなので、設定はなくてもいいかも（でも暗黙的な機能が増えるのも良くないかも…とはいえ明示的にしたところで大してうれしくなさそうだし…）というところです。

**Comment by kmuto** [comment]
はい、ではテストケースを作っておきます。
ymlの追加は、うーん、なくていいような気はします。

#1502 にほかのPR候補をまとめてみてるんで、ご意見いただければ。
