### ISSUE TITLE
Index系の見直し

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1515]
#1384 に関連して、ChapterだけIndex::Itemの使い方がおかしい（captionにchapter本体を突っ込んでる等）ので統一的に扱おうとすると破綻するようでした。
そのためここを修正する必要があるのですが、影響が大きそうなのでメジャーバージョンアップの際にやるのが良さそう（それ以外ではやれなさそう）です。

**Comment by kmuto** [comment]
はい、10月を目指したいです。

**Comment by takahashim** [comment]
#1384 で `IndexBuilder` を導入しました。
個別のファイルに対して`Compiler#compile`する前に、catalog.ymlにあるファイルに対してindexを作成するように変更しています。
