### ISSUE TITLE
著者名を省略できない

### ISSUE THREAD

**Issue by uyumyuuy** [kmuto/review#1517]
config.ymlで著者名aut:を省略すると['anonymous']に、aut: nullとするとコンパイルエラーになります。
ver2.5の頃は省略できていたと思います。
組織で配るドキュメントなど個人名を表示する必要のない文書では著者名を省略したいです。

**Comment by kmuto** [comment]
ご報告ありがとうございます、 #1519 にて対応しました。

また、autを省略したときにはanonymousではなく空になるようにしました。
