### ISSUE TITLE
章見出しにfootnoteをつけるとページごとにヘッダ章見出しでも採番されてしまう

### ISSUE THREAD

**Issue by uyumyuuy** [kmuto/review#1518]
章見出しにfootnoteがついている論文があって、真似してみたのですが、

```
= BRAH BRAH BRAH@<fn>{foo}
BARBARBAR

//footnote[foo][FOO FOO FOO]

BARBARBAR

BARBARBAR

```
このようにページヘッダの章見出しでも新たに採番されてしまいました。

![コメント 2020-07-11 013846](https://user-images.githubusercontent.com/54132088/87177965-72729f00-c317-11ea-9a7e-97228fef4330.png)
![コメント 2020-07-11 014032](https://user-images.githubusercontent.com/54132088/87178032-8c13e680-c317-11ea-8a6f-4705d67393a0.png)

**Comment by kmuto** [comment]
確認しましたが、これはTeXの深淵に踏み込むことになりそうですね…。

- もともとchapter等で\footnoteを使うのは御法度
- どうしても使いたいときには\footnotemarkでマークを入れ、\footnotetextでテキストを別途定義 (現在Re:VIEWは見出し・キャプション・表・コラムの場合はこうなるように設定済み)
- 柱はchapterの中身を使うので、ここに\footnotemarkが入っていると柱のたびにカウントが増殖

対処方法ですが、TeX変換されたときの
`\chapter{BRAH BRAH BRAH\footnotemark}`
 を
`\chapter[BRAH BRAH BRAH]{BRAH BRAH BRAH\footnotemark}`
のように `[〜]` のfootnoteなしになるようにフック等で書き換える必要があります。`[]` は柱等の変数に使うとき用の文字列で、紙面上で2行折り返しを恣意的に指定したいときなどにもよく使う手法です。
https://review-knowledge-ja.readthedocs.io/ja/latest/latex/tex-hook.html

Re:VIEW側でなんとかできるかというと、考えてはみますが、エスケープの順序などだいぶ厳しい気がするのと、いろいろと過去の制作物に影響が出てしまうので、当面はプロジェクト固有でフックスクリプトを作って処理いただくのがよさそうです。

**Comment by uyumyuuy** [comment]
ありがとうございます。
フックスクリプトでうまく行きました。

**Comment by munepi** [comment]
TeX側で対応する場合、結局、LaTeXクラスファイルごとによって処理が異なってしまいますね。
ましてや、ページレイアウトデザインを変更してしまうパッケージ（fancy系パッケージなど）を利用している場合には、
それに従うことになりますので、
 * 見出しに脚注を振らないように編集するか、
 * LaTeXコード上で `\chapter[目次出力文字列]{本文出力文字列}` で対応したほうが賢明ですね。

**Comment by kmuto** [comment]
フックで対応しましょう で回避策としますね。

https://review-knowledge-ja.readthedocs.io/ja/latest/faq/faq-tex.html#bebbddb4021a61d6acf094ed6c776b04
