### ISSUE TITLE
chapterlinkについてconfig.yml.sample記載がない

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1529]
これはもうデフォルトでもいいかもしれないけど…
`@<chap>`や`@<hd>`のハイパーリンクを有効にするオプションで、review-compileでは昔から`--chapterlink`で使えていたもの。

…デフォルトにしちゃおうかな。

**Comment by takahashim** [comment]
印刷原稿用には必要ないのでどうしたものか、というところでした＞デフォルトにするかどうか

**Comment by kmuto** [comment]
昔と違って今はreview-jsbookなりreview-jlreqなりだとmedia=printだとhyperrefが無効になってるんで、たぶん影響はないかなぁと。EPUBのほうは変わることになりますが、これはむしろ今までないほうが不便だったはず？

**Comment by takahashim** [comment]
確かにそうですね。ではデフォルトにしましょうか。

**Comment by kmuto** [comment]
#1532 にて対処
