### ISSUE TITLE
same icons make warning: duplicate ID

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1539]
現在、同じ文書中に同じアイコン `@<icon>{foo}` が出現すると重複の警告が出ます。

例:

```
AAA @<icon>{smile} BBB @<icon>{smile} CCC
```

結果:

```
WARN review-pdfmaker: warning: duplicate ID: smile (#<ReVIEW::Book::Index::Item:0x00007f9912a700f0 @id="smile", @number=2, @caption=nil, @path=nil, @index=nil>)
```

現状、画像パスの探索用にIndexを使って管理しており、重複した出現はIndexの参照時に困ることがあるため警告を出している、という経緯なのですが、`@<icon>`は参照機能がないため警告を抑制しても問題ない気がします。

**Comment by kmuto** [comment]
これ、なんとかしたいなと思いつつ、さぼっていました。
簡単に対処できそうでしょうか。

**Comment by takahashim** [comment]
#1541 で直るといいなあ…というところです
