### ISSUE TITLE
章番号を表示しないようにするとrake pdfがコケる

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#1559]
章番号を表示しないように locale.yml を以下のようにしてから、

```yml
locale: ja
chapter: ""
```

``rake pdf`` すると、「``review/lib/review/latexutils.rb:68:in `escape': undefined method `gsub' for nil:NilClass (NoMethodError) rake aborted!``」になる。

latexutils.rb:
```ruby
    def escape(str)
      str.gsub(@metachars_re) { |s| @metachars[s] or raise "unknown trans char: #{s}" }
    end
```

↓ nil.to_s でよければ。。。

```ruby
    def escape(str)
      str.to_s.gsub(@metachars_re) { |s| @metachars[s] or raise "unknown trans char: #{s}" }
    end
```

**Comment by takahashim** [comment]
どちらかというと、正しく設定されていればnilが来ない方が良いかと思うので、そちらで修正してみます。
