### ISSUE TITLE
epubmakerライブラリをlib/review下に戻していく

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1575]
独立のライブラリとして使う必要があった時代も終わったし、configureなどが別になっているのは面倒なので、epubmaker generation 3としてlib/reviewに戻していきたい。
EPUBv2ももう考えなくてよいだろう…。

**Comment by takahashim** [comment]
どちらかというとEPUB生成は gepub https://github.com/skoji/gepub とかに丸投げした方が品質が担保しやすそうかもという気もするのですが、外部gemの依存は増やさない方が良いですか？

**Comment by kmuto** [comment]
EPUB生成はコア機能なのでgem依存したくないのと、途中にいろいろ挟みたいこともあるので、自前でいきたいですね。
今の実装がベストというわけではまったくないですが…

**Comment by takahashim** [comment]
なるほど、では現状のものをベースに、APIは参考にするかも（しないかも）くらいが良さそうです
