### ISSUE TITLE
//quoteもminicolumnかも

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1589]
最近、引用内での箇条書きに遭遇したので、`//quote` もminicolumn扱いにしたほうがよいかもと思いました。

**Comment by takahashim** [comment]
そうすると minicolumn内に `//quote` が入れられなくなるかと思いますが、それでも良いですか？

**Comment by kmuto** [comment]
おぉ、なるほど… たしかにそれは困りそう。
やめときましょうか。
