### ISSUE TITLE
layoutでセクションタイトルを参照できるようにする。

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#159]
Sphinxの右カラムの Table Of Contents のような感じ。
http://sphinx-users.jp/doc10/tutorial.html

**Comment by takahashim** [comment]
@kdmsnr 突然ですけど、これって使ってます？　リンクが生成されないといまいち不便なのでは…と思ったのですが。

**Comment by kdmsnr** [comment]
最終的にはsphinxみたいにしたいので（したかったので）、あったほうがいいですよねえ。

**Comment by takahashim** [comment]
やっぱり。あとで調べてissueたてます
