### ISSUE TITLE
lib/lineinput.rbをlib/review/lineinput.rbに統合する

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1600]
汎用ライブラリにする必要もなさそうですし、lib/review/lineinput.rbに統合するのはいかがでしょう。

**Comment by takahashim** [comment]
これをするなら #1599 はマージしない方がよいかと思いますが、どうしましょうか？（統合についてはどちらでもOKです）

**Comment by kmuto** [comment]
方針としてよさそうなら、履歴にこだわりはないので #1599 に混ぜてしまおうかと…

**Comment by kmuto** [comment]
#1601 を作りました。
