### ISSUE TITLE
パイプ（|）を索引登録すると|hyperindexformat|となってしまう

### ISSUE THREAD

**Issue by uchan-nos** [kmuto/review#1611]
次のようなreviewファイルを作ってPDFをビルドすると、索引が予期しない文字列になります。

    = パイプを索引にするとバグる
    
    @<idx>{|}というような感じで索引登録すると、索引が@<code>{|hyperindexformat|}となる。

実際のPDF出力はこんな感じになります。

![予期せぬ索引出力](https://user-images.githubusercontent.com/1825663/101755639-7437cd00-3b18-11eb-860e-547225f43597.png)

config.ymlの中の索引の設定は次の通りです。

    pdfmaker:
      makeindex: true
      makeindex_options: "-f -r -I utf8"
      makeindex_mecab: false

現象を確認したreviewのバージョンは4.0.0です。

    $ review version
    4.0.0-master

ソースコード一式とビルド済みPDFをパックしたtarを添付しておきます。

[pipe-index.tar.gz](https://github.com/kmuto/review/files/5671769/pipe-index.tar.gz)

**Comment by kmuto** [comment]
報告ありがとうございます。

mendex的にほかにもエスケープが必要ないろいろと危ない文字がありそう。
makeindex_commandが `/.*mendex.*/`だったらmendexエスケープをする方向で考えます(互換性を壊しそうなのでオプション増やさないとかも…)。

**Comment by kmuto** [comment]
エスケープしてるけどそれがおかしいんだな

**Comment by kmuto** [comment]
`@<idx>{記号}` で検証

コンパイル時点の問題

- `{` はrunaway argumentエラー
- `}` はToo many }'sエラー

結果の問題

- `|` が`|hyperindexformat|`になる

**Comment by kmuto** [comment]
TeXとhyperrefのパンドラの箱を開けてしまった感があります…。本質的な解決には至っていないですが、
ひとまずissueの問題だけの回避策であれば、

index.dicなどの適当な辞書ファイルをプロジェクトフィルダに作り、中身を

```
|	｜
```
(間はタブ)

としておいて、config.ymlで
```
  makeindex_dic: index.dic
```
としておけば、|についてはTeXのhyperrefパッケージによって壊されない全角文字が読みに使われて、ソートも問題ありません(全角でもちゃんと記号側にソートされます)。
ただ{}とかは根本的にまだ動かないですし、ユーザ側でつまらない設定が必要なのは釈然としないので、Re:VIEWコア側で手当てできるものかもう少し粘ってみます。
