### ISSUE TITLE
用語リストのタイトルでは chapterlink が動作しない

### ISSUE THREAD

**Issue by matsubara0507** [kmuto/review#1619]
```
 : @<chap>{ch01}
```

などと書くと、 `\hyperref\lbrack{}chap:ch01\rbrack{}{第1章}` という感じの LaTeX にコンパイルされます。
期待値は `\hyperref[chap:ch01]{第1章}` のはずですが、おそらく

https://github.com/kmuto/review/blob/da817154297474b43c4f13db2e612350ee380b49/lib/review/compiler.rb#L507-L512

の部分の `text` で先にインラインがコンパイルされて、 `dt` で `[]` が `\lbrack{}\rbrack{}` に置換されるからですかね。

そもそも、用語リストのタイトルに chapterlink を使うべきでないと言われればその通りですが、もしかしたら想定外の挙動かもしれないので Issue にしておきます。

**Comment by kmuto** [comment]
ありがとうございます、再現しました。

`@<hd>`展開のreviewsecrefのほうは影響を受けないので、chapref, chap, titleについても同じようにいったん別のものを挟むようにすれば対処できそう。

**Comment by kmuto** [comment]
ひとまず回避だけのreview-ext.rbです。reviewsecrefを借りています。

```
module ReVIEW
  module LATEXBuilderOverride
    def inline_chapref(id)
      title = compile_inline(@book.chapter_index.display_string(id))
      "\\reviewsecref{#{title}}{chap:#{id}}"
    end

    def inline_chap(id)
      "\\reviewsecref{#{@book.chapter_index.number(id)}}{chap:#{id}}"
    end

    def inline_title(id)
      title = compile_inline(@book.chapter_index.title(id))
      "\\reviewsecref{#{title}}{chap:#{id}}"
    end
  end

  class LATEXBuilder
    prepend LATEXBuilderOverride
  end
end
```

実際の修正のほうでは、reviewsecrefとは分けたいかもしれないのでreviewchaprefを導入予定です。
