### ISSUE TITLE
rake webでbuilderディレクトリ内の画像を見つけられない 

### ISSUE THREAD

**Issue by Nyoho** [kmuto/review#1623]
Re:VIEW 5.0.0 を使用しています。#611 と少し似た状況に遭遇しました。

[ドキュメントの画像ファイルの探索](https://github.com/kmuto/review/blob/master/doc/format.ja.md#%E7%94%BB%E5%83%8F%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E6%8E%A2%E7%B4%A2) にしたがって、ビルダディレクトリを作ってその下に画像を置いています。

すると、html ビルダでは画像が見つけられませんでした。
```
WARN review-epubmaker: chap1.re:8: image not bound: sample
WARN review-epubmaker: chap1.re:10: image not bound: sample
```
と出ます。

#611との違いは、pdfビルダでは大丈夫ということです。
手元では次のように再現されます。

- `images/latex/sample.png` に置いたものは、`rake pdf` では参照された。 (`images/pdf/` ではだめだった)
- `images/html/sample.png` に置いたものは、`rake web` や ~rake epub では参照されない~ 。(12/28 0:37) →  `rake epub` では参照されました。 `rake web` だけでした

サンプルコードを https://github.com/NyohoSampleCodes/review-images-builder-test に置きました。

チェックすべきところがあるでしょうか。

**Comment by kmuto** [comment]
rake web (WebMaker)では再現した(修正ドラフト #1624 ) のですが、rake epub (EPUBMaker)のほうで再現しないですね、うーん…。
なお、サブフォルダはビルダ名に基づいているので、`images/pdf/` は×、 `images/latex` が○ なのは合っています。

**Comment by takahashim** [comment]
私の方でもepubmakerは再現しないようでした…。

**Comment by Nyoho** [comment]
ありがとうございます。 #1624 ということは、ディレクトリ名は `images/html/` で合っているはず、ということですね。

**Comment by kmuto** [comment]
ご報告ありがとうございます、ではwebmakerのほうを修正しますね。
(別のロジックミスがあるような気がするので、#1624 はもうちょっと精査します)

**Comment by Nyoho** [comment]
ありがとうございます。

この作業をするときにビルダ名の一覧がドキュメントに探せなかったので、どこかわかりやすく一覧が書かれているといいなあと思いました。(「rake pdfのときのビルダ名はpdfではない」とか、すぐわかりませんでした)

ビルダの名前の一覧はソースを見ればわかるでしょうか。可能ならドキュメントへのPRを書いてみたいと思います。(別イシューっぽい)

**Comment by Nyoho** [comment]
タイトルも修正しました。

**Comment by kmuto** [comment]
@Nyoho ドキュメントのほうも更新しておきますね。#1626

**Comment by Nyoho** [comment]
@kmuto #1626 、ありがとうございます!
