### ISSUE TITLE
見出し参照命令を使っていると Markdown 生成でエラーになる

### ISSUE THREAD

**Issue by usami-k** [kmuto/review#1628]
Re:VIEW 5.0.0 を使っています。

Re:VIEW のドキュメントから Markdown を生成しようとして、`review-compile --target=markdown` を実行したのですが、re ファイルの中で hd 命令を使っているとエラーになってしまうようです。

再現手順：

1. `review-init book` でドキュメントを生成する。
2. `book.re` の中身を以下のようにする。
3. `review-compile --target=markdown` を実行する。

ファイルの中身：

```
= AA

== BB

@<hd>{BB}
```

エラーメッセージ：

```
ERROR review-compile: book.re:5: error: undefined method `inline_hd_chap' for #<ReVIEW::MARKDOWNBuilder:0x00007ff9381e83c0>
Did you mean?  inline_chap
```

なお、当てずっぽうですが、`lib/review/markdownbuilder.rb` に `inline_hd_chap` メソッドを適当に定義してやるとエラーが発生しなくなるようでした。

**Comment by takahashim** [comment]
確かに `@<hd>{}` は対応してなさそうですね…。修正してみます。

**Comment by takahashim** [comment]
うーん、リンク先の拡張子をどうするかが悩ましい…（`book.md`にリンクしても意味なさそう）

**Comment by usami-k** [comment]
対応ありがとうございました。
