### ISSUE TITLE
ins, del命令のエラーと表現対応

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1630]
- insを入れるとWebMakerやTextMakerで失敗する。plaintextbuilderにinline_insが実装されていない。WebMakerは目次採取にこのビルダを使っているためのエラー。
- TeXでinsに表現が適用されていない。HTMLではアンダーラインがデフォルト表現みたい。reviewinsertマクロを追加し、中身のデフォルトとしては下線にした。jsbookではjumolineなので単なる下線、jlreqではulemを使っているので二重下線にしてみた。
- TeXでdelの表現をあえて無視していた。しかしjsbookではjumolineをコピーしているし、jlreqではulem前提にしているので、それぞれの打ち消し線を使うように設定する。
- plaintextbuilderでdelを空文字にしているが、delは「表示はするが打ち消し表現をする」という意味なので、空文字にしてしまうのはよくない。

最後のは挙動としては互換性を壊すが、どっちにしろins/delは現時点ではほぼ使われていないと思うので変えて問題なさそう(pandoc2review由来でdelは今後よく入ってくる可能性)。

**Comment by kmuto** [comment]
ins/delはあったけど明文化していなかった裏コマンドだった模様…。表コマンドにします。

**Comment by takahashim** [comment]
plaintextbuilderは`@<del>`は空文字にするのでいいと思いますが……（制御文字とかは使わない方が良さそうなので）。

**Comment by kmuto** [comment]
delって「出力はするけど打ち消し表示したい」という意図なのではないかと思うんですよねぇ。
plaintextbuilderのほうは端末制御文字などは使ってないですね、そのままの出力です。

**Comment by takahashim** [comment]
うーん、まあ何にせよ原則プレーンテキストで表現できないものをプレーンテキストで表現するという無理筋な対応なので、どうするかは決めの問題かとは思いますが、私見では、

* `foo`→`foo`
* `@<ins>{foo}`→`foo`
* `@<del>{foo}`→`foo`

よりは、

* `foo`→`foo`
* `@<ins>{foo}`→`foo`
* `@<del>{foo}`→ (空文字列)

の方が良さそうな気がしております。

**Comment by kmuto** [comment]
なるほど。まぁそれほどコダワリポイントでもないし、影響するのはplaintextbuilder (普通のtextとして使うtopbuilderのほうは削除擬似命令つきで出力してる) とそれを目次に使うwebmaker/review-volume/indexくらいなので、空にしちゃいますかね。

**Comment by kmuto** [comment]
本年もよろしくお願いいたします!
