### ISSUE TITLE
uplatex/platexコンパイラ時に\RequirePackage{plautopatch}を最初に入れる？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1644]
uplatex/platex利用時にはファイルの最初で `\RequirePackage{plautopatch}` を入れる、のが諸々クラス/パッケージの利用の上でトレンドのようです。
(見ている資料が公開されたらURLをはりつけます)

クラスファイルその他のマクロ定義の段階では手遅れなので、layout.tex.erbの冒頭を加工する必要がありそう。

layout.tex.erb
```
<%= latex_pre_documentclass_config %>
\documentclass...
```

pdfmaker.rb
```
def latex_pre_documentclass_config
   ...(latex_config類似、latex/pre_documentclass_config.erbを読み込む)
end
```

pre_documentclass_config.erb
```
<%- unless @config['dvicommand'] -%>
\RequirePackage{plautopatch}
<%- end -%>
```

texcommandの文字列比較でplatex文字列に真という判定もできるけど、dvicommand存在有無のほうがlualatex/xelatex等除けには確実な気がしています。

**Comment by kmuto** [comment]
https://qiita.com/wtsnjp/items/76557b1598445a1fc9da が元ネタです

**Comment by kmuto** [comment]
LuaLaTeXでやってみたらエラーになるのかな、と思ったけど
```
Package plautopatch Warning: This package is meant for pLaTeX/upLaTeX,
(plautopatch)                you will not need it..
```
でちゃんとスキップされたので、「デフォルトでlayout.tex.erbの頭に書いておく」でもいちおうOKそうなことはわかりました。

**Comment by kmuto** [comment]
独自クラス持ちならクラス冒頭でも問題ないのでは という話でした。それならcls2つ直すだけなので安全で助かりそう。

**Comment by munepi** [comment]
（Re:VIEWとTeX Liveのバージョンの組合せをあまり考えたくもないのですが……、）
[CTAN: Package plautopatch](https://www.ctan.org/pkg/plautopatch)によると、2018年7月よりも古いTeX環境では、plautopatchパッケージが存在しないので、

``` latex
\IfFileExists{plautopatch.sty}{\usepackage{plautopatch}}{}
```

としておいたほうがよさそうでしょうか。

**Comment by takahashim** [comment]
今後、Re:VIEWとTeXのどちらかが古くなっても別に問題なさそうであれば入れてしまってもいいんではないかと思います。
