### ISSUE TITLE
処理表示をカラーリングしたい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1660]
Vivliostyle-CLIの処理表示がほどよいカラーリングのかんじなので真似したい。

- 緑太字のチェックマーク+黒のメッセージ: そのプロセスが成功
- 赤太字のバツマーク+赤太字のメッセージ: エラー
- 薄緑か青のぐるぐるマーク: 時間のかかる処理を実行中 (これは出力した行を再描画しないと無理そう？)

カラーリングはカラー可能ttyのみで、リダイレクトされた場合は黒のままにする。

**Comment by takahashim** [comment]
最近のRubyではTTY-Toolkitシリーズが定番そうではあります。
https://ttytoolkit.org/

TTY全部はてんこ盛りすぎるので、一部を使うだけで良いはず。ログを吐くだけならtty-loggerとかでしょうか。
https://github.com/piotrmurach/tty-logger
