### ISSUE TITLE
image 命令がエラーになる

### ISSUE THREAD

**Issue by techlabxe** [kmuto/review#1666]
Re:VIEW 5.0 (Docker版)を使用しています。
この環境で review-init sample として生成したファイル一式を使い、
画像読み込みの image コマンドを使用したときに以下のエラーが生じました。

```
INFO review-pdfmaker: compiling sample.tex
WARN review-pdfmaker: compile error in sample.tex (NoMethodError)
WARN review-pdfmaker: undefined method `<<' for nil:NilClass
ERROR review-pdfmaker: compile error, No PDF file output.
```

私の環境では、以下の２つの条件を満たすときに発生しております。

- ドキュメント一式は 5.0 の review-init により生成したものである
    - 4.x 系で生成したファイルでは問題なく動作しているようにみえます(review_version 5.0に変更して確認)
- review-pdfmaker のときに発生する
    - review-webmaker では発生しない

簡単な対処法などあるようでしたら、教えて頂ければ幸いです。

**Comment by kmuto** [comment]
sample.re全体、または少なくとも//image行付近の内容を拝見したいです。

**Comment by techlabxe** [comment]
生成されたものを以下の内容に変更して実行しました。
画像データは初期データとして用意されている cover.jpg を使うようにしています。

```
= テスト

//image[cover][図][scale=0.75]{
//}
```

**Comment by kmuto** [comment]
うーん、再現しなくて謎ですね。

より生のデータが出ると思うので、お手数ですがreview-compileを実行していただけますか。
手元だとこんな感じになります。

```
$ review-compile --target=latex sample.re 
\chapter{テスト}
\label{chap:sample}
\begin{reviewimage}%%cover
\reviewincludegraphics[width=0.75\maxwidth]{./images/cover.jpg}
\reviewimagecaption{図}
\label{image:sample:cover}
\end{reviewimage}
```

**Comment by techlabxe** [comment]
コンパイルの結果は以下の通りです。

```
root@6e7b7465ed1a:/workspaces/tmp/samplebook2# review-compile --target=latex samplebook2.re 
Traceback (most recent call last):
        12: from /usr/local/bin/review-compile:23:in `<main>'
        11: from /usr/local/bin/review-compile:23:in `load'
        10: from /var/lib/gems/2.5.0/gems/review-5.0.0/bin/review-compile:184:in `<top (required)>'
         9: from /var/lib/gems/2.5.0/gems/review-5.0.0/bin/review-compile:29:in `main'
         8: from /var/lib/gems/2.5.0/gems/review-5.0.0/bin/review-compile:83:in `_main'
         7: from /var/lib/gems/2.5.0/gems/review-5.0.0/bin/review-compile:83:in `each'
         6: from /var/lib/gems/2.5.0/gems/review-5.0.0/bin/review-compile:88:in `block in _main'
         5: from /var/lib/gems/2.5.0/gems/review-5.0.0/lib/review/compiler.rb:44:in `compile'
         4: from /var/lib/gems/2.5.0/gems/review-5.0.0/lib/review/compiler.rb:312:in `do_compile'
         3: from /var/lib/gems/2.5.0/gems/review-5.0.0/lib/review/compiler.rb:589:in `compile_command'
         2: from /var/lib/gems/2.5.0/gems/review-5.0.0/lib/review/compiler.rb:603:in `compile_block'
         1: from /var/lib/gems/2.5.0/gems/review-5.0.0/lib/review/builder.rb:182:in `image'
/var/lib/gems/2.5.0/gems/review-5.0.0/lib/review/latexbuilder.rb:582:in `image_image': undefined method `<<' for nil:NilClass (NoMethodError)
```

自動生成されたもの＋上記の変更分程度なのですが、
自分の環境でエラーとなるプロジェクト一式を添付します。

[samplebook2.zip](https://github.com/kmuto/review/files/5975259/samplebook2.zip)

**Comment by techlabxe** [comment]
自己解決しました！大変申し訳ありません。

image の後にキャプションなしとなっている場合にこのエラーに出遭うようです。

- NG:  `//image[cover][]{`
- OK:  `//image[cover][hoge]{`
    - hoge の部分がスペース１つでも入っていればセーフ

確認不十分で Issue 立ててしまい申し訳ないです。

**Comment by kmuto** [comment]
わかりました。いただいたものでは `//image[cover][図][scale=0.75]{` ではなくて
`//image[cover][]{` になっています。
2つめ引数のキャプションが空で失敗していますね。

- キャプションなし画像にするのであれば、`//indepimage` のほうをご利用ください。
- 「採番ありキャプションなし」にするのは、今すぐの話だと全角スペースあたりを入れておいてごまかしておいてください。
- キャプションなしでバックトレースになるのは直しますね。

**Comment by kmuto** [comment]
はい、キャプションなしで壊れることはバグなので、openのままでけっこうです。

**Comment by techlabxe** [comment]
わかりました。このまま Open にしておきます。
調査頂きありがとうございました。
