### ISSUE TITLE
warnとerrorを整理する

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1674]
いろんなところで`error`と`warn`を定義しているので、もうちょっとまとめたいですね…。

**Comment by kmuto** [comment]
:+1:

**Comment by takahashim** [comment]
* warn: とにかくloggerに出力する
* error:
    * builder: 基本はCompilerから呼び出されるので、例外をあげてCompiler側で処理させる
    * compiler: `@errors`か何かでエラーを保持する？ 途中では死なない。loggerに吐いて保持しておいて、最後にエラーが保持されていれば終了する？
    * maker: 終了する

**Comment by takahashim** [comment]
終了するエラーは `error!(msg)`とかにした方がいいかも？

**Comment by takahashim** [comment]
compileエラーについてはエラーになったファイルと行数が表示されるようにできそう

**Comment by takahashim** [comment]
`error!`は終了
