### ISSUE TITLE
Re:VIEW 5.2 または Re:VIEW 6.0リリース

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1678]
次は6月末の予定です。

- [x] warn/errorを整理する #1674
- [ ] lib/review がだいぶ増えたのでサブサブフォルダ化する #1673
- [ ] EPUBライブラリをバラし、今の間接的な利用方法をやめて扱いやすくする

できるかどうか…
- [ ] PDFMakerのttインライン命令で欧文補助文字エラー #1675 
- [ ] 暗黙のIDエスケープ #1616 
- [ ] 参考文献DB連携 #1590
- [ ] メジャーアップデートならブロック命令結果を文字列返しできんかなぁ、つらいかなぁ…。ただreview-extレベルの互換性を完全に殺すことになりそう。

**Comment by kmuto** [comment]
ぼちぼち6月が迫ってくる感ある

**Comment by takahashim** [comment]
#1673 は何も考えずにやってみたら色々壊れたので難しいかもです…。

**Comment by kmuto** [comment]
> #1673 は何も考えずにやってみたら色々壊れたので難しいかもです…。

りょかいー

**Comment by kmuto** [comment]
5.2リリース済みなのでこれはcloseします
