### ISSUE TITLE
Docker内でrake epubを実行したときに、css, imagesが0ファイルになる

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1686]
vvakame/review:latest (Re:VIEW 5.1.1)環境で実行

```
Archive:  book.epub
  Length      Date    Time    Name
---------  ---------- -----   ----
       20  2021-04-25 13:24   mimetype
      250  2021-04-25 13:24   META-INF/container.xml
      452  2021-04-25 13:24   OEBPS/vscli.xhtml
        0  2021-04-25 13:24   OEBPS/style.css
      561  2021-04-25 13:24   OEBPS/book.xhtml
        0  2021-04-25 13:24   OEBPS/images/cover.jpg
      649  2021-04-25 13:24   OEBPS/book-toc.xhtml
      575  2021-04-25 13:24   OEBPS/titlepage.xhtml
     2136  2021-04-25 13:24   OEBPS/book.opf
---------                     -------
     4643                     9 files
```

- ネイティブなDebian環境では問題なし
- Dockerでも`REVIEW_EPUB_OPTIONS="-d" rake epub`とすれば問題なし
- `remove_entry_secure`のところで何かタイミングがおかしい？(逆にWindowsだとまたおかしくなるかも…)

**Comment by kmuto** [comment]
ではなくて、EPUB3::produceの時点ですでに0バイトなのでおかしい。コピーのところが変なようだ。

**Comment by m-shibata** [comment]
関係ないかもしれませんが、以前Docker+Re:VIEWな環境で、`FileUtils.cp`をするとコピー先のファイルサイズが0になるという問題にはまりました（kmutoさんにもいろいろ相談にのってもらいました）。

どうもoverlayfsかtmpfsがらみでメタデータの同期がうまく動いていないような感じです。また、デバッグモードだとtmpfsにコピーしないので起きない状態でした。

原因自体はわからなかったので、手元のプロジェクトではconfig.yamlのhook_aftercopyimageとhook_prepackから「`find $1 -exec touch {} \;`」を実行するだけのシェルスクリプトを叩くようにしています。

**Comment by kmuto** [comment]
そうか、以前にあったような…とおぼろげな記憶でした。ありがとうございます。今後もずっと困りそうなので、preserveしてしまうか…。
