### ISSUE TITLE
pygmentsをemlist、cmdでも利用したい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#169]
・今は//listのIDの拡張子を使っている。
・emlistやcmd、sourceで使うにはIDをどう指定するかが問題。
・驚き最小法則にのっとると、IDパラメータを後ろに追加するのはlistの使い方と逆になるのでまずい。

//emlist[ID][]{ →現//emlist{相当

//emlist[ID][CAPTION]{ →現//emlist[CAPTION]{相当

若干最初のが気持ちが悪いがこういうかんじか？

**Comment by takahashim** [comment]
とりあえずpygments自体は対応したので、このチケットは閉じますね
