### ISSUE TITLE
review-extでの拡張インライン命令でエラー

### ISSUE THREAD

**Issue by uyumyuuy** [kmuto/review#1709]
review5.1でreview-ext.rbでインライン命令を追加しました。
[Re:VIEW のモンキーパッチによる拡張の基本](https://review-knowledge-ja.readthedocs.io/ja/latest/reviewext/review-ext-basic.html)を参考にBuilderOverrideとLATEXOverrideの両方で命令を定義しました。上記ページには「中身は適当でよいので」とありますが、BuilderOverrideでも何か値を返さないとエラーになるようです。

とりあえず入力をそのまま返したらうまくいったのですが、本来は何を返すのがいいのでしょうか。

reviewtest.re
```
= test

@<kaibun>{てすと1てすと2}
```

review-ext.rb
```ruby
module ReVIEW
  module BuilderOverride
    Compiler.definline :kaibun

    def inline_kaibun(s)
      #下の行のコメントを外すとOK     
      #s
    end
  end

  class Builder
    prepend BuilderOverride
  end

  module LATEXBuilderOverride
    Compiler.definline :kaibun

    def inline_kaibun(s)
      s.reverse
    end
  end

  class LATEXBuilder
    prepend LATEXBuilderOverride
  end

end
```

これで`rake pdf`として実行すると、下記のようなエラーメッセージが出力されました。
``` console
ℹ INFO    compiling reviewtest.tex 
⚠ WARN compile error in reviewtest.tex (ReVIEW::ApplicationError)
⚠ WARN reviewtest.re:3: error: no implicit conversion of nil into String
⨯ ERROR   compile error, No PDF file output.
rake aborted!
Command failed with status (1): [review-pdfmaker  config.yml...]
lib/tasks/review.rake:112:in `block in <top (required)>'
Tasks: TOP => pdf => book.pdf
(See full trace by running task with --trace)
```

**Comment by kmuto** [comment]
インラインはnilではなく何らかの文字列を返すことが期待されています。単に空を返したいということであれば、

```
    def inline_kaibun(s)
       ''
    end
```

**Comment by uyumyuuy** [comment]
例ではブロック命令だったから何も返していなかったのですね。

ちなみにIndexBuilderOverrideやBuilderOverrideで空以外のものを返すとどのように使われるのでしょうか？ nilでなければなんでもいいのでしょうか。

**Comment by kmuto** [comment]
IndexBuilderのほうだと何も使われない、Builderのほうだとこれは基底クラスなので仮にHTMLBulderで定義しなかったらそちらではBuilderと同じものが使われる、ということになりますね。
IndexBuilderもBuilder派生なので、まずはBuilderにとりあえず無難なものを追加し、ビルダ(出力)ごとで変えたいところはLATEXBuilderなりHTMLBuilderなりでカスタマイズというのがよいかと思います。

**Comment by uyumyuuy** [comment]
よくわかりました。ありがとうございます！
