### ISSUE TITLE
openanyにしても第一章だけが偶数ページはじまりになる

### ISSUE THREAD

**Issue by uyumyuuy** [kmuto/review#1711]
openanyを指定しても第1章のみ偶数ページ始まりになるという現象に悩まされています。

あるいは目次の後に白紙ページが出るということなのかもしれません。
白紙ページは、ノンブルはついていますがヘッダやフッタのページ番号はないので、おそらくlatexレベルの話かと思います。tocの後にcleardoublepageなどが入っているのかなと思ったのですがよくわかりませんでした。

環境はこんな感じです。
* luatex
* review-jlreq
* プロジェクトは4.2で作成後5.0にreview-updateで更新
* review-ext.rbでいろいろインライン命令を追加しています（ほぼフォント変更用）
* review-custom.styで\usepackage[greek,bidi=basic]{babel}  しています←あやしいそうだけど消しても変わりませんでした

```
texdocumentclass:
  [
    "review-jlreq",
    "media=print,paper=a5,fontsize=9pt,baselineskip=15pt,line_length=34zw,number_of_lines=32,head_space=21mm,gutter=23mm, openany, startpage=1,serial_pagination=true, hiddenfolio=nikko-pc",
  ]

```

新しいプロジェクトで少し試したのですがそちらでは再現しませんでした。

最小構成で再現できない上に、上記のとおり怪しいところがたくさんあるのでReViewの問題ではない可能性がだいぶ高いのですが、何か考えられることあるでしょうか。

**Comment by kmuto** [comment]
jlreqの更新がいろいろアグレッシブでなかなかついていきづらいのですが、mainmatterにcleardoublepageがデフォルトで設定されているのが原因のような気がします。

review-custom.sty
```
\jlreqsetup{mainmatter_pagebreak=clearpage}
```
だとどうでしょうか。

**Comment by uyumyuuy** [comment]
完璧です！　こんなオプションがあったのですね。ありがとうございます！

**Comment by kmuto** [comment]
性質的にopenanyの効果はjlreq.cls側で対処してもらうほうがよさそうなので、あとでjlreq.clsにお願い出してみますね。

**Comment by kmuto** [comment]
https://github.com/abenori/jlreq/issues/85
