### ISSUE TITLE
隠しノンブルが全て1になる

### ISSUE THREAD

**Issue by huideyeren** [kmuto/review#1720]
## 概要

現在書いている本でPDFでねこのしっぽ仕様のノンブルを設定しようとしていますが、隠しノンブルが全て1になってしまいます。

## 完成したPDF

[XiandaiFenshuVol5.pdf](https://github.com/kmuto/review/files/7026573/XiandaiFenshuVol5.pdf)

## 望むこと

隠しノンブルが通し番号でふられるようにする。

## 参考ファイル

- [書籍のリポジトリ](https://github.com/huidetang/XiandaiFenshuVol5)
- [config.yml](https://github.com/huidetang/XiandaiFenshuVol5/blob/main/config.yml)

**Comment by kmuto** [comment]
TeXLive 2020, 2021で再現確認しました。
TeXカーネルの変更に伴う何かだと思われます。修正を試みます。

急ぎの場合はvvakame/review Dockerイメージが動作確認の取れているTeXLIveバージョンですので、これでビルドしてみてください。

**Comment by huideyeren** [comment]
修正を試みるとのこと、ありがとうございます。

まだ入稿までに余裕があるので修正を待ちます。

**Comment by kmuto** [comment]
とりあえず場当たりな対応としては、sty/review-jsbook.clsの47行目
```
\RequirePackage{xkeyval,everypage}%%,etoolbox
```

を

```
\RequirePackage{xkeyval,everypage-1x}%%,etoolbox
```

としてみてください(-1xを追加する)。TeXLive2021ではこれで戻るのを確認しました。

**Comment by huideyeren** [comment]
TeXLive2020を使った私の環境でも正しくノンブルが表示されていることを確認しました。
ひとまず、これで対処してみるとします。

**Comment by kmuto** [comment]
@munepi こういうとき-1x以外だとどうするのが妥当なんでしょう。EverypageHookでのthepageが初回のみしか評価されなくなってる、ということですよね。新カーネルでフックはいろいろ増えたようなのですが動的に変わるものへの手段が見当たらず…(jlreqはexpl3化されてよく読めない…)。

**Comment by munepi** [comment]
@kmuto （Re:VIEW公式でどこまでTeX Live年次バージョンを面倒見るかにもよりますが、余計なものを使わない方向で対応するならば、）
(u(p))LaTeX2e kernelのバージョンを見て、処理を変えることになりそうです。

ここらへんのダンプしたフォーマットのバージョンを見るコードの例は、latexrelease.sty, platexrelease.styやそれらのドキュメントが参考になります。

``` latex
\makeatletter
\edef\recls@sourcepLaTeXdate{%
  \expandafter\@parse@version\pfmtversion//00\@nil}
\@onlypreamble\recls@sourcepLaTeXdate

%% 20200202 は例というだけです。
\ifnum\recls@sourcepLaTeXdate<20200202
\RequirePackage{everypage}
\else
\RequirePackage{everypage-1x}
\fi
\makeatother
```

----------

本件の背景として、昨今、TL20, 21の大幅な変更は、「tagged pdf」のための過渡期ですね……。
次は、エンジンを一つに絞って、LuaTeXに切り替えてしまってよいかもしれません。

**Comment by kmuto** [comment]
なるほど。現状でeverypage-1xを使うしかなさそうということだと、IfFileExistsでもよいのかな。
LuaTeX絞りですか、そろそろ考えないとですね。
