### ISSUE TITLE
utbookクラスでpdfを作ろうとすると表紙絡みのエラーで落ちる

### ISSUE THREAD

**Issue by huideyeren** [kmuto/review#1723]
utbookを使って縦書きのPDFを作ろうとしたところ、以下のようなエラーで落ちます。

```
./review-base.sty:433: Undefined control sequence.
96
l.433     \ifrecls@coverfitpage
```

なお、config.ymlは以下のような感じです。
https://github.com/huidetang/XiandaiFenshuVol5/blob/main/config.yml

**Comment by kmuto** [comment]
Re:VIEWで提供しているsty群は、review-jsbook.clsまたはreview-jlreq.clsが提供するマクロ名を前提にしているため、それ以外のclsではエラーになります。

- review-jlreqを使い(`review-init --latex-template review-jlreq`)、tateオプションを指定する。
- review-jsbook.clsをいじってutbook.clsを呼び出すようにする。`\PassOptionsToClass{\recls@set@js@paper}{jsbook}}`のあたり? 動くかの確証はないです。
- reviewmacro.styやその他styを変更し、review-jsbook.clsやreview-jlreq.clsが提供するマクロ名に依存しないようにする。

あたりから対応策をとっていただくことになりそうです。また、縦書きについてはreview-jlreqでいくらかテストはしましたが、奥付の見せ方など別途各自で固有の設定が必要だと思いました。

**Comment by huideyeren** [comment]
ありがとうございます。

こちらもreview-jlreqで本文の縦書きは実現できました。
なお、jlreqに関しては以下の点は要改善と思いました。

- 表紙や奥付が時計回りに90度回転したデザインになる
- PDF版のみ画像が時計回りに90°回転して表示される
- 自動的に挿入される数字がアラビア数字で縦中横が効いていない
- 後注用のタグと設定がほしい

とりわけ、PDF版で画像を90°回転させるようにするのは必要かと思います。
別途issueを起票するかもしれませんが、本issueはクローズとさせてください。
