### ISSUE TITLE
後注サポート

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1724]
縦書き、および翻訳書などで後注が登場することがあり、footnoteとは別にendnoteを導入したいかも、という話。

- 「書籍末尾」はRe:VIEWの機構的に難しいので、あくまで章(re単位)の末尾配置で。
- jlreqは`\endnote` (footnoteと同じ記法で後注登録) および `\theendnotes` (指定場所に後注展開)を提供している
- jsbookはendnotesjパッケージを使えばjlreqと同じマクロ名で実現可能。幸いDebian busterのTeXLiveにも入っている
- 命令名: `@<en>` / `//endnote` かな。わかりにくそうなら `@<endnote>` でも(table, listと同じ)。
- chapter内で利用があれば最後に`\theendnotes` を入れる で基本よさそうだが、後注見出しを指定したいということだと別途定義が必要そう。むしろ `//printendnote` みたいな命令を用意して見出し含めて全部re側で明記したほうがよい気がする(`//endnote` を使ったのに `//printendnote` を使わなかった、という警告がほしくなる？)。
- HTML: 覚えておいて最後に書き出す、ということになる。ハイパーリンクで相互関連付ける。今のテンプレートのbodyに割り込むのは大変な気がする。`//printendnote` 明記のほうがいいな…
- TEXT: 覚えておいて末尾に書き出すだけでよさそう。`//printendnote` のほうがわかりやすい。
- InDesign: 新しめのバージョンだと後注機能がある。これに乗せることを前提にする(footnoteと同じようにXML内に入れて処理はInDesignのJavaScriptに任せる)か、それとも `//printendnote` でリテラルに書き出すか…。後者のほうが見出し絡みを考えなくていいというのはある。PDF書き出し時のリンク関係は作れないが、どうしても必要ならJavaScriptでなんとかすればよさそう。

TeXでの注記号デフォルトは「(n)」になっている。変えるパラメータはあるがjlreq/jsbook(endnotesj)共通で安全にできる気はしないので、config.ymlやlocale.ymlで指定するのは厳しい。リテラル表現するHTML・TEXT・InDesignのほうはlocale.ymlあたりで変えられるようにしたほうがよいかも。

**Comment by huideyeren** [comment]
ちょうどモンキーパッチで実装したタイミングでしたが、人文・社会系縦書き派としては助かります。
