### ISSUE TITLE
脚注参照忘れの警告

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1725]
翻訳原稿などで `//footnote` を用意したものの `@<fn>` を忘れて紙面から落ちている、ということがたまにあります。
手元ではreファイルをなめてチェックする内製ツールを使っているのですが、コンパイラ/IndexBuilder側でfootnoteの未参照を拾えそうならWARNを出したいです(image,list,tableは参照しないこともままあるので現状確認したいのはfootnoteのみ)。

**Comment by takahashim** [comment]
これは普通に実現できそうな気もします

**Comment by kmuto** [comment]
素朴にはハッシュ用意して`#footnote`, `#endnote`でキー:ID、値0 として定義、`#inline_fn`, `#inline_endnote`でキーIDに値+1、最後のresult前にハッシュで値0のものを一覧というのを考えたところで、ビルダであちこちメソッド上書きしているので大変…と詰まりました。
lndexBuilder内か、Indexクラスに何か持たせるかするといいんでしょうかね。
