### ISSUE TITLE
//footnote[site][～]で生成される「*n」をspanで囲むなどして、縦書き時に倒れない指定をしたい

### ISSUE THREAD

**Issue by imamurayusuke** [kmuto/review#1741]
縦書きの原稿で脚注を作ると、脚注冒頭の番号「*n」が倒れます。これをspanで囲んで出力していただけると、倒れないようCSSで指定できます。
現在はEPUBを生成後[*n]を[&lt;span～&gt;*n&lt;/span&gt;]と変換しています。
ご検討のほど、よろしくお願いいたします。
![review_issue210908](https://user-images.githubusercontent.com/8149723/132474266-a90fc0b3-4a92-4d60-9350-335ac142eabc.png)

**Comment by kmuto** [comment]
HTMLでのそのあたりの出力はi18n設定側に移譲しており、後方互換性を考えるとデフォルトを今からそのように細かくspanを付けたものに変更するのは避けたいです。

要望の形についてはたとえば

locale.yml
```
locale: ja
html_footnote_textmark: '<span class="footnote_head">[<span class="footnote_number">*%s</span></span> '
```

と書けます。

**Comment by imamurayusuke** [comment]
なるほど、そういう方法があるんですね。それで対応できます。ありがとうございました。
