### ISSUE TITLE
エピグラフ付きの各章の扉を出力したい

### ISSUE THREAD

**Issue by huideyeren** [kmuto/review#1746]
各章の頭にエピグラフを入れたいとは思っています。

現状、Re:VIEWでは大扉と各部のタイトルのみ扉が作られる設定になっていると思いますが、各章にも扉を作ってそこにエピグラフを入れられたらよいと考えております。

ただ、どうやって情報を格納すべきかが悩ましいところですが。

**Comment by kmuto** [comment]
そのレベルになると定型があるわけではないのと、jsbook/jlreqからかなり逸脱したものになりそうで元のjsbook/jlreqの変更があったときに追従が苦痛になるので、公式提供なものは難しいです。

商業制作の経験では、

- reファイル側は//leadか//quoteを転用してエピグラフ記載。終わったところで改ページするようにTeXマクロか、あるいは明示的に\clearpage
- styでは\chapterを再実装
- 凝ったレイアウトの場合はre/styで必死にやるよりも、章ごとの扉PDFを作って、\thechapterカウンタに応じて貼り付ける

というかんじです。

**Comment by huideyeren** [comment]
ありがとうございます。けっこう大変ですね。

元の実装から逸脱するのもきついと思うので、対応無しでかまいません。

**Comment by kmuto** [comment]
何か別ツールで各章扉として実寸のPDFかAIファイルを用意しておき、それを順次貼り付ける、という例を作ってみました。

https://github.com/reviewml/reviewknowledge-ja/tree/master/codes/chaptobira
