### ISSUE TITLE
review-catalog-converterでDateシンボルエラー

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1753]
@takahashim 
a25ecc4c5a92ad7026385ca32645b58910fe8d26 で入っていた lib/review/catalog.rbの
```
       @yaml = YAML.safe_load(file.read, [Date])
```
なんですが、`require 'date'` をしていないのでエラーになりました。
意図的には単純にrequireすればいいんでしょうか。

**Comment by kmuto** [comment]
@takahashim これcloseします？ グローバルにします?

**Comment by takahashim** [comment]
最近のRubyではDateよりもTimeの方がおすすめという話もあるので、グローバルにはしなくても良いんではないかと思いました！

**Comment by takahashim** [comment]
というわけでこのissueは閉じてしまっても問題ないです

**Comment by kmuto** [comment]
ありがとうございます!
では閉じますね。
