### ISSUE TITLE
ファイル名に`-`が入っている、存在しない画像を参照するとreview-pdfmakerが異常終了する

### ISSUE THREAD

**Issue by atsushieno** [kmuto/review#1762]
context: https://twitter.com/atsushieno/status/1454355563953876994

`//image` で画像ファイル名を指定しているとき、通常は単にファイルが見当たらないことが警告として表示されるのみで正常終了しますが（`✔ SUCCESS built xxx.pdf`）、ファイル名に`-`が入っていると、`⨯ ERROR   failed to run command: uplatex -interaction=nonstopmode -file-line-error -halt-on-error __REVIEW_BOOK__.tex` のようなメッセージから始まるトレースログが出てきて異常終了するようです（ReVIEW-Templateだと`npm run pdf`で先に進めない状態）。

reproとbuild logを添付しています。（ReVIEW-Templateから自分の書籍用に手を加えて原稿関連ファイルを抜いたもの）
[build.log](https://github.com/kmuto/review/files/7450723/build.log)
[reviewtest.zip](https://github.com/kmuto/review/files/7450721/reviewtest.zip)

ビルド環境: Ubuntu 20.04 / ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

（最初のTwitterコメント時は、ファイルが存在しない警告にファイル名が含まれているのを自分が見逃していたようなので、本件は異常終了のみの問題として認識して登録しています。）

**Comment by kmuto** [comment]
ひとまず実行して再現しました。深掘りしてみます。

**Comment by kmuto** [comment]
わかりました、sty/review-base.styが古いです。
Re:VIEW 5.2.0で修正済みの #1527 ですね。

review-updateを実行してstyを更新してみてください(techboosterスタイルのためにはreviewcustom.styの書き戻しも必要です)。

**Comment by atsushieno** [comment]
ありがとうございます。review-update実行後は問題が発生しなくなったようです。（techboosterスタイルに戻しての確認まではしていませんが、本件は解決したと理解しています。）
