### ISSUE TITLE
local.yml %pdW指定にしても、目次はローマ数字になってしまう

### ISSUE THREAD

**Issue by TakaoKimura** [kmuto/review#1764]
re:view を使って、部の表示を、例えば、第3部としたいのだけど、local.yml を変えても、第Ⅲ部となってしまう。
文章中に表示されるのは、第3部となっているけど、目次や、部タイトルは、ローマ数字になってしまう。
環境の問題なのですかね？
ちなみにdockerを利用していて、re:viewのバージョンは5.3です。

locale: ja
part: 第%pdW部

**Comment by kmuto** [comment]
はい、そのあたりのナンバリング表現がTeXクラスファイル側で固定で、locale.ymlを作用させるのがだいぶ難しいのでした。

全角数字で表現するのはだいぶ複雑なので紙面上での目次・部タイトルについては半角数字で許容いただくとすれば、sty/review-custom.styに

```
\renewcommand{\thepart}{\arabic{part}}
```

と追加してみるとどうでしょうか。

**Comment by TakaoKimura** [comment]
ありがとうございます。
こちらで対応できました。

**Comment by kmuto** [comment]
Re:VIEW Knowledgeにドキュメント化しておきました。

https://review-knowledge-ja.readthedocs.io/ja/latest/faq/faq-tex.html#7e51c7ea32917287bc9dfdac1db212c3
