### ISSUE TITLE
Enabling GitHub Discussions

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#1770]
IssueじゃないQ&Aとか、その他Re:VIEWに関する情報共有用で、ここにGitHub Discussionsを用意するのがいいんではないかと思いました。
https://docs.github.com/ja/discussions

Settingsから設定できるはずです。
https://docs.github.com/ja/discussions/quickstart

**Comment by kmuto** [comment]
とりあえずEnableにしてみました。Announcementを書けということだけど、日本語でいいですかね…ユーザ的にも日本語圏がほぼ100%だろうし。
議論やBANの線引きとしてCoCみたいなのを作っておいたほうがよさそうに思いました。

**Comment by takahashim** [comment]
ありがとうございます、Announcementはとりあえず日本語でもいいんではないでしょうか。

**Comment by kmuto** [comment]
とりあえずアナウンス作ってみました〜
