### ISSUE TITLE
節項参照の採番のみパターンがほしい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1809]
`@<hd>`で現在 節項の採番+見出し となりますが、これとは別に節項の採番のみを出すものがほしいという要望あり。
併用したいためlocale.ymlで済ませるわけにはいかないという事情があります。

実装自体は簡単なのですが、すでに`@<hd>`で採番+見出しにしており、`@<chap>` (採番のみ)、`@<chapref>` (採番+見出し) との関係一貫性をとれないので名前に悩みますね…。`@<sec>`, `@<secref>`、`@<sectitle>` とか新たに作ってしまう？

**Comment by kdmsnr** [comment]
sec, secref よさそうです
