### ISSUE TITLE
Supporting imgmath on IDGXML maker

### ISSUE THREAD

**Issue by kn1cht** [kmuto/review#1820]
## 概要
InDesign XML (IDGXML) makerでも `imgmath` 機能をサポートすることを提案します。
現在、[Forkしたリポジトリでimgmathの実装を試しています](https://github.com/kmuto/review/compare/master...kn1cht:review:imgmath-for-idgxml?expand=1)。

## 背景
LaTeX数式を画像化する `imgmath` は、現在epubmaker, textmaker, webmakerに実装されています。最近InDesign XML出力に数式を含めたい機会があり、idgxmlmakerでも `imgmath` が同様にサポートされると嬉しいです。

Issueなどを拝見しても、idgxmlmakerに`imgmath`を実装してはいけない理由は特にないように見受けられました。サポートすることに問題がなければ、私の方で実装してみたブランチからPull Requestを提出させていただきます。

なお、Re:VIEWで用意されている数式の出力オプションには他にもMathML, MathJaxがあるものの、 #1603 で[議論された](https://github.com/kmuto/review/pull/1603#issuecomment-739599728)ようにいずれも現状でInDesignでの使用が困難です。

## 実装方針
`lib/review/idgxmlbuilder.rb`, `lib/review/idgxmlmaker.rb` にimgmath用のコードを追加します。他のbuilder, makerから関係する箇所をコピペしてみたところ、問題なく機能しているように見受けられます。

### `//texequation`
通常の`indepimage`と同じく、`<img>`の下に`<Image>`を入れる構成でいかがでしょうか。

- 入力
```re
//texequation{
e=mc^2
//}
```
- 出力（imgmath有効時）
```xml
<img>
<Image href="file://images/_review_math/_gen_882e99d99b276a2118a3894895b6da815a03261f4150148c99b932bec5355f25.png" />
</img>
```

### `//texequation` with caption
- 入力
```re
//texequation[emc2][The Equivalence of Mass @<i>{and} Energy]{
e=mc^2
//}
```
- 出力（imgmath有効時）
```xml
<equationblock>
<caption>式1.1　The Equivalence of Mass <i>and</i> Energy</caption>
<img>
<Image href="file://images/_review_math/_gen_882e99d99b276a2118a3894895b6da815a03261f4150148c99b932bec5355f25.png" />
</img>
</equationblock>
```

### `@<m>{}`
こちらも、`@<icon>{}`命令と同様に`<Image type="inline" />`を出力することでいかがでしょうか。

- 入力
```re
@<m>{\sin}
```
- 出力（imgmath有効時）
```xml
<Image href="file://images/_review_math/_gen_5fded382aa33f0f0652092d41e05c743f7453c26ca1433038a4883234975a9b0.png" type="inline" />
```

**Comment by kn1cht** [comment]
現状の実装で、InDesignへの読み込みを試してみましたので結果をご報告します。

左がXMLを元にしたInDesignの画面、右がPDF出力です。InDesign側の数式のベースラインは、とりあえず手動で調節したものです。

![image](https://user-images.githubusercontent.com/16277200/176986846-b6c8b9be-c1b5-46fb-a596-e73ae6824c78.png)

**Comment by kmuto** [comment]
遅くなりましたがようやく拝見しました。
大筋良さそうです! ありがとうございます。

- texequation: `<img>` だと後から区別したいときに厄介そうなので、`<equationimage>` に。
- m: こちらも該当を絞り込みやすいように、`<inlineequation><Image ... /></inlineequation>` と外を囲む。

はいかがでしょうか。

**Comment by kn1cht** [comment]
@kmuto ご確認ありがとうございます！

texequationでは
```xml
<equationimage>
<Image href="file://images/_review_math/_gen_882e99d99b276a2118a3894895b6da815a03261f4150148c99b932bec5355f25.png" />
</equationimage>
```

mでは
```xml
<inlineequation>
<Image href="file://images/_review_math/_gen_5fded382aa33f0f0652092d41e05c743f7453c26ca1433038a4883234975a9b0.png" type="inline" />
</inlineequation>
```

となるようにしました。
