### ISSUE TITLE
icon命令のLaTeX出力について

### ISSUE THREAD

**Issue by fabon-f** [kmuto/review#1836]
# 提案1

現状だと、インライン命令`@<icon>`と画像を出力する各種ブロック命令の両方で`\reviewincludegraphics`が使われています。今のところ引数1が空ならインライン画像だと分岐させることはできますが、そもそも役割が別である以上、別のマクロに割り当てた方がスタイルをいじるときに分かりやすいのではないかと思います。

```
icon: @<icon>{hoge}
```

現状の出力:
```latex
icon: \reviewincludegraphics{/full/path/to/hoge.xxx}
```

変更案:
```latex
icon: \reviewicon{/full/path/to/hoge.xxx}
```

# 提案2

現状だとインライン画像はそのままの大きさで出力されるので、画像によっては想定よりもはるかに大きく表示されてしまうことがあります。デフォルトでは1行分の高さで表示されるようにした方が、多くの場合想定通りの出力になるのではないでしょうか。

ただ、表の中に画像を入れたいなどの理由で`@<icon>`を使っている場合は逆に困りそうなので、どちらをデフォルトにするべきかは議論の余地があるかもしれません。(ひょっとするとこちらのユースケースの方が多い?)

(いずれにせよ、styファイルをいじるか、逆の挙動をする命令を`review-ext.rb`で追加すれば解決できる問題ではあるのですが)

**Comment by kmuto** [comment]
お返事遅くなりました。
提案1はそれで採用しようと思います(以前にそうするはずだったのを忘れていました…)。
提案2のほうについてはたしかに悩みますね…。インライン命令でオプションを付けづらいのとCSS/TeXで互換性を持たせづらくてスケール値も難しいし。

**Comment by kmuto** [comment]
#1838 でreviewiconマクロを導入しました。
文字高にするのは状況に依存しすぎるので、review-base.styのreviewiconの定義のところにヒントを書いておきました(が、どうやってこれを見てくれるのか問題はあります)。
