### ISSUE TITLE
ruby命令と空白の挙動について

### ISSUE THREAD

**Issue by fabon-f** [kmuto/review#1837]
現在、ドキュメント(`format.md`)ではルビ記法について`@<ruby>{親文字, ルビ}`と記載がされています。ここで親文字とルビの間にコンマと空白があるのですが、`builder.rb`で命令の中身をパースする段階ではこの空白が取り除かれておらず(ルビの方に入っている)、その結果ルビ部分の前にスペースが入るかがビルダ依存になっています。

* 空白付きで出力される: LaTeX(`\ruby{親文字}{ ルビ}`のように)、HTML
* 空白が削除される: IDGXML

前者はドキュメントの挙動と食い違うため、全てのビルダについて挙動を後者に合わせるべきではないでしょうか。(たとえば`compile_ruby`に渡すところで`trim`してしまうとか)

**Comment by kmuto** [comment]
ご報告ありがとうございます。
これは最近自分もハマったのでビルダ共通でスペースをtrimする方向にします。

**Comment by kmuto** [comment]
タイプミスでauto closeできなかったという痛恨…

ご報告ありがとうございました!
