### ISSUE TITLE
囲み記事のキャプションがすべて■メモ: になってしまう

### ISSUE THREAD

**Issue by fenril058** [kmuto/review#1843]
//note[キャプション]{ 〜 //} : ノート
//memo[キャプション]{ 〜 //} : メモ
//tip[キャプション]{ 〜 //} : Tips
のどれを使ってもキャプションが
■メモ: キャプション
になってしまいます。

**Comment by kmuto** [comment]
review-jsbook/review-base.sty
```
\newcommand{\reviewminicolumntitle}[1]{%
\review@ifempty{#1}{}{%
  {\large \review@intn@memohead{}: #1}\\}}
```
たしかにあらゆる`memohead`にしちゃってるのでマズイですね…。

review-jlreqのほうだとtcolorbox版を使っていてtitleに個々設定しているので問題ないのですが(review-jsbookでもboxsettingでtcolorboxを使うバージョンにできますが、デフォルトではtitleのプレフィクス付けてないので「メモ」などすらも入らないというのがネックになりそう)。

**Comment by kmuto** [comment]
breaking change にはなるんですが、 #1856 で対処しようと考えています。
