### ISSUE TITLE
bound ではなく found かもしれない。

### ISSUE THREAD

**Issue by oipest** [kmuto/review#1850]
bound とあちこちに出てきますが、found のような気がして気になってしまいます。
バグではないので報告を上げていいものか悩んでいましたが、念のため。

**Comment by kmuto** [comment]
imageまわりですね。mineroaokiさん設計の当初からこうなっていて、タイプミスではなくbindの過去形boundです。
imageについてはほかと違ってIDをもとに外部ファイルから妥当な候補を探して結びつける(bindする)という仕組みなので、あえてこの語句を使っているのではないかと思います。

**Comment by oipest** [comment]
ありがとうございます。気にならなくなりました。
