### ISSUE TITLE
章タイトルに[nonum]をつけると章ヘッダが正しく反映されない

### ISSUE THREAD

**Issue by uyumyuuy** [kmuto/review#1855]
「第1章」のような章番号をつけたくなくて、[nonum]を使ったところ、ヘッダ部分が思った通りになりませんでした。

# 環境
* Review 5.5.0
* review-init直後のプロジェクト

```
=[nonum] はじめに

てすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすと

 
== つぎに

てすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすと

== さらに

てすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすとてすててすと


```

jlreqではヘッダの章タイトルが「目次」になってしまいます。
![image](https://user-images.githubusercontent.com/54132088/188132701-b1053bf1-67ac-44d8-b1e2-f7ce7f4f95f8.png)

jsbookでは「第0章　はじめに」と表示されます。
![image](https://user-images.githubusercontent.com/54132088/188132883-c3e0c600-4121-4d12-bb18-56debffd0807.png)

nonumを使う代わりに
config.ymlでsecnolevel: 0にしても同じ動作のようです。

**Comment by kmuto** [comment]
review-base.styのreviewmainmatterhookのところですね。
全部なしでよいなら、review-custom.styで、

```
\def\reviewmainmatterhook{%
  \renewcommand{\chaptermark}[1]{\markboth{##1}{}}
  \mainmatter
}
```

と再定義してしまうとどうでしょう。

**Comment by uyumyuuy** [comment]
ありがとうございます。
jsbookだとその方法で「第0章」が消えてうまくいきますが、jlreqだとchaptermarkが使われていないせいか（？）、うまくいきませんでした。

jlreqの場合は章が進んでもずっとヘッダに「目次」と表示され続けるのでなにか変数が更新されていないんだと思うのですが、わかりませんでした。

TexLive2021を使っているのですがjlreq.clsが古いのでしょうか？

**Comment by kmuto** [comment]
nonumの場合はre→TeX化で `\chapter*{はじめに}` となるのですが、このstar付きのときにはjlreq内部で`_chapter`に収まず、前の「目次」が引き継がれてしまうようです。
jlreqの追跡はだいぶ困難でメゲています。
すべての採番を付けない前提でよさそうであれば、[nonum]は外した上で、

review-custom.sty
```
\ModifyHeading{chapter}{number=false}
\ModifyHeading{section}{number=false}
\ModifyPageStyle{headings}{mark_format={_section={#1}, _chapter={#1}}}
```

で一応ご要望の形にはなりました。1行目と2行目は見出し設定の上書きで採番をしない。3行目は柱のフォーマットの設定の上書きで節・章の採番出力をしない(さもないと柱には第0章や0.1のように入ってしまう)。というものです。

**Comment by uyumyuuy** [comment]
ありがとうございます！　うまくいきました。
いつもお手数をおかけしてしまってすみません……。

**Comment by kmuto** [comment]
エッジケースの発見はありがたいので、今後ともぜひ〜

Re:VIEW側のstyで対処するのはどうにも難しそうなので、Re:VIEW Knowledgeのほうに書きとめておこうと思います。
