### ISSUE TITLE
コラム内の見出しで nonum/nodisp/notoc が使えない

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#1865]
```
= 章見出し

===[column] コラム

====[nonum] コラム内の見出し

===[/column]
```

とすると

```
review-compile --target=html --footnotetext --stylesheet=style.css
⨯ ERROR   column-notoc.re:7: column is not opened.
⨯ ERROR   column-notoc.re cannot be compiled.
```

エラーになりました。

**Comment by kmuto** [comment]
コラム内で地の文引き継ぎの採番をすること、コラム内で独自見出し採番をすること どちらともちょっと想定しづらいのですが、どういう結果が期待されるんでしょうか。

**Comment by kdmsnr** [comment]
何も指定しないと「コラム内で地の文引き継ぎの採番をする」になりますよね。これは変だなと思いました。
「コラム内の見出しは採番しない」がよいのかなと思い、nonumを指定してみたのですが、上記のエラーになりました。

**Comment by kmuto** [comment]
あぁそうか、review-jsbookだと引き継いじゃうのですね…。業務用のは手当てしていて気付かなかったです。
`@doc_status[:column]` 有無でなんとかなるかな…

**Comment by kmuto** [comment]
手元だと、コラム内の小見出しは採番対象でない最下位レベルにすることで回避していましたが、運用回避というのもあまりよくなさそうですね。HTMLでも同じ症状になるので少々根が深い。

**Comment by kmuto** [comment]
パーサの挙動を見ているとだいぶ厄介そうな気がしますね。


とりあえず「今困っている」ということの対処であればダミーとしてnonum閉じを入れる、でしょうか。
```
= 章見出し

===[column] コラム

====[nonum] コラム内の見出し
====[/nonum]

〜

===[/column]
```

**Comment by kdmsnr** [comment]
なるほど、閉じタグも使えるんですね。

**Comment by kdmsnr** [comment]
これは「運用回避」でよいと思いますので、クローズします。

ドキュメントにも書いてはありますね。

> より下位の見出しを使うことでコラム内に副見出しを入れることができますが、それが必要になるほど長いコラムはそもそも文章構造に問題がある可能性があります。
