### ISSUE TITLE
//blanklineの挙動

### ISSUE THREAD

**Issue by munepi** [kmuto/review#1872]
`latexbuilder.rb` で定義されている `//blankline` は、

``` ruby
    def blankline
      puts '\vspace*{\baselineskip}'
    end
```

ではなくて、

``` ruby
    def blankline
      puts '\vspace{\baselineskip}'
      ## もしくは、puts '\par\vspace{\baselineskip}\par'
      ## もしくは、puts '\@@par\vspace{\baselineskip}\@@par'
    end
```

とするほうが良さそうに思います。
理由は、`\vspace*` を使った箇所が版面天に来た場合、該当箇所の版面上部でそのまま空いてしまいます。

ちなみに、issuesを検索すると、PR #951 のときには、[pending](https://github.com/kmuto/review/pull/951/files/f9eb49b41fad8d727b604c066f1a4fe60ff9e735..d5ec0e996f84d0f4714fcbb9fe8499cb3e90e866#diff-88b3814f8fbe616df62cd9c09aed0a0c14954b6741e084c37818e28080e2666e) でした。

**Comment by kmuto** [comment]
なんか理由があった気もしますが、たしかに先頭になるとまずいですよね。
parを付けたほうが安全かな…。

あとで反映します。

**Comment by kmuto** [comment]
#1873 で対処しました。
前後の要素によっては\parしておかないとくっついてしまうようなので、前後\par付きにしています。

**Comment by munepi** [comment]
ご対応いただき、ありがとうございます。

ちなみに、標準的なLaTeXを使うかぎりにおいて、まずLaTeX2e kernelで`\let\@@par=\par`となっており、`\@@par`はTeX primitiveを保持していて、`\par`はLaTeXマクロです。
（なので、アレなLaTeXパッケージを使ったり、LaTeXマクロの作り方がアレだと、場所によって`\par`がうまく意図した改行の挙動にならない場合があります。）
