### ISSUE TITLE
C2A0の扱い

### ISSUE THREAD

**Issue by dmiyakawa** [kmuto/review#197]
以下のプロジェクトに対して

https://github.com/dmiyakawa/test_article

review-compile --target=latex sample.re をかけたとき
結果にC2A0が入る時と省略されて入らない時があります。

上記プロジェクトの sample.re に「こちら サンプル に　なります」とありますが、「こちら」と「サンプル」の間には半角スペースではなく\xC2\xA0が挿入されています
http://www.sitespiral.jp/archives/83.html

これが、環境ごとに微妙に残ったり消えたりします。reviewのバージョンとしてgitの最近のもの (b117955dcdf43e) を両方使いましたが、一方 (debian wheezy, 7.1) では消え、もう一方 (debian wheezy, 7.1 つまり同じ) では残りました。

これが残ってしまうと、latex 側でのコンパイルに最終的に失敗します (debian のtexliveだとおそらく)。具体的には、上記の場合 review-pdfmaker sample.yaml が成功したり失敗したりします。

ソースコードを追えていないので環境の違いによって挙動が変わる理由がわからないのですが、何か心当たりはあるでしょうか。

**Comment by mhidaka** [comment]
本Issueは https://github.com/kmuto/review/pull/399 のおかげで解消した、との理解で大丈夫？かな。

**Comment by kdmsnr** [comment]
「環境ごとに微妙に残ったり消えたり」は解消されたのではないかと思います。

「これが残ってしまうと、latex 側でのコンパイルに最終的に失敗します」については、「そんなの原稿に入れるな」とするか「Re:VIEWでどうにかする」を選択しないとですねえ。

**Comment by takahashim** [comment]
uplatexにしたらC2A0があってもPDFが生成できるようになりました。uplatexすごい！
というわけで、こちらは解決ということで閉じておきます。
