### ISSUE TITLE
maprangeについて

### ISSUE THREAD

**Issue by dmiyakawa** [kmuto/review#215]
http://seuzo.net/entry/2012/03/12/100307

二点ありまして

1. quickstartあたりに公式の説明が欲しいです
2. 先頭が#@だとC++等のファイルを引用する際引用元に問題が発生しないか気になっています。オプションの第三引数等で先頭の文字列を変更するといったことに対応したりはしていないでしょうか。

**Comment by takahashim** [comment]
#632 の通り、doc/preproc.mdとdoc/preproc.ja.mdに説明を記載しました。ので、こちらは閉じます。
