### ISSUE TITLE
column中のtableがpdfに出てこない

### ISSUE THREAD

**Issue by yanzm** [kmuto/review#222]
```
===[column] Hoge

...

//table[my_table][Fuga]{
テーマ               色         透明度
---------------------------------------
Theme.Holo          #333333     60%
Theme.Holo.Light    #FFFFFF     80%
//}

===[/column]
```

をPDFにすると、tableが出てきません。
columnの外に出すと出てきます。

review-pdfmaker では、次のようなエラーが出ています。

```
! LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...                                              

l.99 \begin{table}[h]

? 
! Undefined control sequence.
\@float@Hx ...ltovf \fi \global \setbox \@currbox 
                                                 \color@vbox \normalcolor \...
l.99 \begin{table}[h]

? 
! Missing number, treated as zero.
<to be read again> 
                  \vbox 
l.99 \begin{table}[h]

?
```

**Comment by munepi** [comment]
（Re:VIEW Meeting 2017 Autumnに向けて、）

`//column` のブロック要素をLaTeX側において何で実装しているかに依りますけれども、
`//column` に対応するブロック要素のLaTeX側実装で、こちらに対処すべきだと思います。

それから、この強制位置固定 `[H]` について。
LaTeXのフロート位置指定 `[H]` は、現状、標準的に利用可能なパッケージとして、 float.sty を利用することになります（昔は、here.styでした）。ところが、この float.sty は、余計なお節介をたくさんやってくれますので、単なる 強制位置固定の `[H]` だけを利用するには、このfloat.styは、無駄に大きすぎるパッケージとなります。

一方、大昔の here.sty の `[H]` は確かに必要な機能だけがありますけれども、（とくに商業利用する上で、）強制位置固定をした図表の前後アキと各種見出しやブロック要素とのアキ詰め処理をするには、このhere.styは非力すぎます。
ひとまず、jclasses, jsclasses系の汎用クラスファイルで強制位置固定 `[H]` を簡単に使う分には、 here.sty 程度で十分だと思いますので、これらの汎用クラスファイルに対しては、簡易的な `[H]` をどこかに定義しておけば十分だと思います。

また、 `[H]` の実装に依りますが、版面の上部にちょうど `[H]` の図表がきたときに、前アキを除けるのが良いですけれども、実装次第でそうなっていません。

それゆえ、実際には、利用する特定のクラスファイルごとに、 `[H]` が実装されていて、 `[H]` を調整するのが望ましいように思います。

**Comment by kmuto** [comment]
今のところは #1095 で入れたfloat+Hで対処済みということにしておきます。
