### ISSUE TITLE
yamlの拡張子が yaml と yml で揺れている

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#244]
どちらかに統一したいところ

**Comment by tkhm** [comment]
通りがかりです。yaml vs ymlで探していて辿り着きました。使われているのはymlが多くこちらでもymlが採用されたようですが、Official Siteでは`yaml`を推奨しているようですね。

http://www.yaml.org/faq.html

**Comment by dmiyakawa** [comment]
興味深いので結論を待っている筋です。

感覚的には.ymlの方が多い印象で、自分も.ymlの方が好みではあります。
できればRe:VIEWでも探索優先順序も .yml -> .yamlの方が最も肌感覚に合います。

「公式では.yamlを推奨している」というのは非常にありがたい情報で参考になります (初めて知りました)。本点で気になるのは次の点です。

 1. 推奨する理由について書かれていない
 2. 実態の利用数は.ymlが多い (らしい) ため理由なければ多い方に統一するのが自然に思える
 3. 公式サイトのcopyrightの年号が 2006年で止まっており10年前。全体的にサイトの更新が数年滞っているように見える (そりゃ仕様が変わってねーんだから、というのはもちろん正しい指摘)

正直どっちでも良いと思われました。が、Re:VIEWとして「こう決めた」というスタンスを貫いていただいて、それをどこかWikiでもFAQでも明示して維持していただくことが、一人の利用者としては一番頼りになります。

**Comment by kmuto** [comment]
* closeされてるとおり、Re:VIEW内では「Rubyの主流に合わせて」という理由で、ymlで統一。
* 一部のものについては.yaml を読むようにもしているが、とりたてて愛や主張があるわけではなく、Re:VIEWでは旧来データ資産が重要なので過去に.yamlとしていた時代との互換性のために残している。（何度か壊して移行に四苦八苦したのではないか？というのはサテオキ）
*  よって今後何らかのYAMLファイルを新規導入することになったときには.ymlのみとなるだろう。

というのがスタンスかな。
個人的には3文字以下にするのは「DOSか？DOSなのか？」という気にはなるけど ;-)
