### ISSUE TITLE
「電書協形式」ePUBサポート

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#251]
epubcheckが通っても、これになっていないと不正と言われる事案が……。

いろいろめんどくさいので、どこまでがんばるかは別。

- OEBPSのかわりにitemというディレクトリ
- TOC以外のxhtmlはitem/xhtml、CSSはitem/style、図版はitem/image
- TOCはnavigation-documents.xhtmlという名前
- OPFはstandard.opf
- OPFにprefixとebpajメタ
- OPFにauthorやpublisher等をrefinesで読み指定
- 使用するCSSやHTMLタグはマスト要件ではないはずだが…

今はフックスクリプトで必死にいじっている。読み指定のほうは標準機能として用意してもよさそう。

**Comment by takahashim** [comment]
いろいろあって、真面目に対応しようかと思っています。
EBPAJMakerを作るべきかどうか悩み中です…

**Comment by kmuto** [comment]
ようこそJ地獄へ…
吐き出しHTMLを調整するフィルタは手元にあるんだけど、ad-hocすぎるのでbuilderとmakerに手を入れたほうがよさそう。

**Comment by kmuto** [comment]
だいたいガイドの骨子は入れたはず
