### ISSUE TITLE
indeptableが必要

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#255]

**Comment by suzukin** [comment]
これあると嬉しいかもという事象に遭遇したのでコメントに残しておきます。

**Comment by kmuto** [comment]
indepimageは名前が悪かった気がするので、tableのほうは別の名前にしたくなってきました。listに対するemlistってどういう意味だったんだろう…

**Comment by kdmsnr** [comment]
青木さんから `embeded list` だと聞きました

**Comment by kmuto** [comment]
emtable だとどうだろう…

**Comment by kdmsnr** [comment]
あ、ほんとですね。 `numberlessimage` にエイリアスされてますね。
`emtable` でいいと思います。
