### ISSUE TITLE
review-pdfmakerでフックしてTeXソースをいじりたい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#259]
変換したTeXソースをさらにがっつりいじりたい、review-extでは収まらないレベル、というときにeubmaker-ngと同様にフックスクリプトを呼び出せるようにしたい。
＃名前空間考えとけばよかったか…

**Comment by kdmsnr** [comment]
1.5で入りましたよね？

**Comment by kmuto** [comment]
あーそうですね、ありがとうございます。
