### ISSUE TITLE
索引への対応

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#261]
現状索引が機能するのはInDesign版のみ（それもタグ抽出＆辞書読み＆ソートは外部ツール依存）。

LaTeX版は辞書読みが面倒そうなので、hidxで読みも入れることを前提として、\makeindexを最後に挿入、mendexをpdfmakerで呼び出す？ （yamlで辞書ファイル指定できるようにする？ istでスタイルも指定しないと多分いろいろせつない結果になる）

HTML版は頭が痛い。読みも入れることを前提とする？mendexの存在を期待するのはまずいか。リンク位置の一意化が複雑そう。

**Comment by kmuto** [comment]
#660 のPRに関連。

現状、手元の既存資産の索引は次の形になっています。

```
@<idx>{索引単語}
@<hidx>{索引単語}
@<hidx>{索引親単語<<>>索引子単語}
```

読みは中カッコ内には指定せず、辞書から読む形。

mendexで辞書を指定させるという手段は可能だけれども、mendexのエラーはちょっとわかりにくいのでユーザーは混乱しそうです。

PRのものは生のLaTeXを直接指定する形なので、ほかのビルダで困るのと、日本語混じりの``@<idx>``は（辞書を指定しない限り）読みも出てしまっておかしなことになるので、そのままの採用はしづらいです。
LaTeX索引にあるようなseeとか範囲とかも使いたいことはありますかね。

**Comment by kuroda** [comment]
@kmuto レスポンスありがとうございます。

私のPRは単なる議論のきっかけと考えてください！

> LaTeX索引にあるようなseeとか範囲とかも使いたいことはありますかね。

いま作っている本では使っていないのですが、今後は使いたいと思っています。

**Comment by kmuto** [comment]
ビルダ固有（実質ほぼTeX向け）索引を作りたいときには
```
@<hidx>{|latex|tex書式索引……}
```
という記法を導入するのがよさそうかなぁ。

@kuroda さんのパッチのをベースにちょっといじってみますね。mendex辞書まわりはドキュメントで説明かな。

**Comment by kmuto** [comment]
#669 にて辞書ファイル+MeCabの実装を用意してみました。

また、ビルダ固有でほかではまずだめなものは@<raw>や//rawを使ったほうがよいかなと思いました。

**Comment by kmuto** [comment]
#261 にての対応
