### ISSUE TITLE
config.yml へのRe:VIEW文法バージョンの明示

### ISSUE THREAD

**Issue by dmiyakawa** [kmuto/review#276]
ある本を執筆するときには「どのバージョンのRe:VIEW文法(~=Re:VIEWツール)で本が書かれたか」を明示しておけるべきと感じています。ざっと見た限りではそういう機能をサポートしているように見えなかったのでファイルします。

ビルドに使っているRe:VIEWツールのバージョンが、 config.yml に記載されているバージョンより古い場合、ビルドはデフォルトでは失敗するようにする方が良いと思います。

特に前回のRe:VIEW カンファレンス 1 では、互換性破壊をして綺麗にする、的な話もあったような気がしていますので、どうせビルドの途中で謎のエラーが出るのであれば、いっそ最初に明確な理由をつけて失敗して欲しいと思ったりします。

逆のケース(新しいツールが古いバージョンを見たケース)では別の議論が必要と感じます。

古い・新しいをどう判定するかは課題です。数字(例: 1.3.1 < 2.0)だけであれば簡単ですが。

**Comment by kmuto** [comment]
``review-init --version``は実装はないですが、とりあえずmakerのほうでバージョニング付けの仕組みと警告（エラーはやりすぎと判断）が入りました。
