### ISSUE TITLE
別ファイルの章を参照する

### ISSUE THREAD

**Issue by kazu-yamamoto** [kmuto/review#277]
あるRe:VIEWファイルから、別のファイルにある章を参照するには、どうすればいいでしょうか？たとえば、

```
=={id1} テスト1
:
@<hd>{id1}を参照。
```

はうまくいきますが、

```
=={id2} テスト2
```

と

```
=={id3} テスト3
:
@<hd>{id2}を参照。
```

を `review-compile --target html -a` で変換しても、key がないと言われて、参照できません。

**Comment by kzhk75** [comment]
上記同様に `@table` 識別子を利用する際、 `==` から始まる re file があると、表番号が一つ加算されるという現象に遭遇しました。
これはどこかに know-how として、記載されていたりしますか？ 例えば、git内 wiki等。
```
% review version
5.5.0
```
