### ISSUE TITLE
``[nonum]``をつけた場合の章番号カウンタの挙動

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#301]
統一されてないので仕様を決めた方が良さそうです。

* HTMLBuilder: 章に``[nonum]``がついている場合は章番号が+1される（「第XX章」は表示されないけど）。節番号はリセットされる。
* LATEXBuilder: 章に``[nonum]``がついている場合、章番号が増加しない（「第XX章」を除いた章タイトルが表示されるだけで、前章の続きのようになる）。節番号もリセットされず、前の章からの番号が引き継がれる。

あと、章レベルに``[nonum]``がついていても、節見出しには``[nonum]``がついていない場合、「XX-YY」みたいな節番号が表示されてしまうのは変な場合が多いかと思いますが、これは「いったん``[nonum]``をつけた場合、その下位レベルには``[nonum]``をつけるべき」みたいな使い方（ややバッドノウハウ）でいいんでしょうか。

**Comment by kmuto** [comment]
TeX挙動に合わせられるか見てるんですが、これかなり難しいですね。

book/base.rb
```
num=0
 ...
return catalog.parts_with_chaps.map do |entry|
            if entry.is_a? Hash
              chaps = entry.values.first.map do |chap|
                Chapter.new(self, (num += 1), chap, "#{@basedir}/#{chap}")
              end
              Part.new(self, (part += 1), chaps, read_PART.split("\n")[part - 1]
)
            else
              chap = Chapter.new(self, (num += 1), entry, "#{@basedir}/#{entry}"
)
              Part.new(self, nil, [chap])
            end
          end
```

numberとなるのはChapterコンストラクタの2つめ引数で、ここではシーケンシャルにcatalogで読んだ順に採番しているだけ。
この時点ではファイルを開いているわけではないので、nonumがあるかどうかというのは判断できない。判断するにはファイルを開かないといけない。

* catalogで情報を持たせる…のは難しそう。構文的にも変になりそう
* catalogのロードが終わったあと、章/部の見出しheadlineだけを探す軽量なパーサを実行する？(うーん…)

**Comment by kmuto** [comment]
#555 で対処したつもり
