### ISSUE TITLE
review pdfmakerでのフォント埋め込み

### ISSUE THREAD

**Issue by mhidaka** [kmuto/review#329]
PDFでフォント埋め込み機能が欲しい。
config.yamlで指定できると嬉しいはずですが、どの程度需要あるかはわかんないです。
（これはとくにPDF入稿、オフセット印刷するときに聞く要望なのでコミケに近づくにつれ高まる需要です）

実際には　https://twitter.com/androidsola/status/502662076838338561 のように改造して利用している模様。

**Comment by mhidaka** [comment]
あっ。このスレッドがまだ生きてる。
追加で作業している内容についてご意見を伺いたい状況になりました。

このたび、フォント埋め込みについてモリサワさんのリュウミンを使おうとしています。
TeXで
```
kanji-config-updmap morisawa
```
といったかんじで指定する、というのは理解できたのですが、

たとえば見出しに新ゴをつかいたい、本文はリュウミンだ、としたい場合どのような方法があるのかわからないです。

パターンとしてはTeXでフォントマップを作るという話は
https://oku.edu.mie-u.ac.jp/~okumura/texwiki/?TeX%E3%81%A8%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88#q1b5e62f
あたりで言及されているのですが
実際、pdfmakerではこの方法しかないのでしょうか？

**Comment by takahashim** [comment]
その辺はTeX周りの感じですよね…。

従来からのTeXは基本的にいったんdviファイルを吐いて、そのdviを何かしらの変換器でpdfに変換するという流れで、そのdvi→pdfの際にフォントの処理が入ります(dviファイル自体はフォントに独立した形になることになっているので)。

で、現状はその変換器としてdvipdfmxを使っています。これを変更するのであれば、config.ymlの`dvicommand`を、またdvipdfmxのオプションを変更するのであれば`dvioptions`を使えば指定できます。こうするとフォントマップファイルも指定可能です。

あと、フォントに凝ったPDFを作るならlualatexに走る方法もありますが、ビルド速度がびっくりするくらい遅くなるので、締め切り近いタイミングでは大変ストレスフルになっておすすめできないのでした…。

**Comment by kmuto** [comment]
これは閉じてOK? > @mhidaka 
sample.ymlかどこかに -fでマップ指定できるよ くらいの例を入れたほうがよいでしょうか。

**Comment by mhidaka** [comment]
はい、閉じましょう。
PDFへのフォント埋め込みは現状
http://osksn2.hep.sci.osaka-u.ac.jp/~taku/osx/embed_hiragino.html 
もしくは -fでマップできるよ、があれば十分だと思います。
