### ISSUE TITLE
inline_columnで他章への参照ができない

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#333]
hdと同じ挙動（|で区切り）にしたほうが一貫性としてはわかりやすいか。builder.rbと*builder.rbで同じような処理をしているのも綺麗にしたいところ。

**Comment by suzukin** [comment]
手元の案件でこの需要（他の章のコラムを参照したい）があって調べていたらこのissueにたどり着いたので期待を込めてコメントを残します！ そこまでニーズがある気がしなくもないと言えばそれまでなんですが。。

**Comment by kdmsnr** [comment]
a13826ae49c4552add5932ff30235417bf21e5ee
