### ISSUE TITLE
catalog.yml のファイル名をconfig.ymlから指定できるようにしたい

### ISSUE THREAD

**Issue by dmiyakawa** [kmuto/review#338]
以前相談したような……それともかく。

現状ですとcatalog.yml決め打ちなんですが、catalogfileをconfig.ymlにとりあえず入れられると助かります。

コンセプトコード的なのはこちらです。これだとマジで全部上書きできてしまうのですが。
https://github.com/dmiyakawa/review/commit/0693e98bbe3609e0fce3da170672f98bce926db5

OKそうなら他のbin変更してPRします

**Comment by kmuto** [comment]
機能は入ったし、参照先不在はさすがに原稿側でなんとかしていただきたいというかんじなので、これはcloseしますね。
