### ISSUE TITLE
epubmakerのzip実行でpure ruby実装のものを試すようにする

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#353]
epubmakerで内部で使用するzipコマンドのやり方はWindowsで困りそうなので、
Pure Rubyのライブラリを利用できそうならそちらを使う？（gem版はそれに依存させちゃう？）

**Comment by takahashim** [comment]
1.8.7への依存もなくなったということで、#487 で実装してみました。

**Comment by takahashim** [comment]
取り込んでみました。

* 依存gemとしてrubyzipを指定しているので、gem install reviewでrubyzipもinstallされるはず
* Re:VIEW本体としてはZipクラスの有無を調べて、Zipクラスがない場合はzipコマンドを使うようにしています。Zipクラスがある場合はzipコマンドは使いません（参照もしません）。

**Comment by takahashim** [comment]
無事動いているようなので閉じます
