### ISSUE TITLE
#@maplinesが必要？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#354]
旧TODOより

* #@maplines の導入。

なんだっけこれ……

**Comment by takahashim** [comment]
これって「外部ファイルに対して行数を指定してその部分を読み込めるようにしたい」という話だったのではないかと思いました。

この要望は #215 で出てたような、「先頭に`#@range_begin`とか`#@range_end`とか埋め込むのができない場合がある→そこで行数指定できるようにすればいいのでは」という流れに由来したのだと思うのですが、 `#@@range_*`を使うことで解決できるのであればなくてもいいのかも、ということだと理解しています。

**Comment by takahashim** [comment]
上記の通りかと思うので、`#@@range_begin 〜  #@@range_end`を使うことにして、具体的な要望が出たら改めて考えるということで閉じます。
