### ISSUE TITLE
htmlbuilder: comment/inline_comment

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#360]
comment記法はdraftモード以外のときにHTMLのコメント扱いになっているが、他のビルダーと同様に出力しなくてもよさそう。

**Comment by takahashim** [comment]
@kmuto これって非表示でもいいでしょうか。idgxmlbuilderでは使ってます？

**Comment by kmuto** [comment]
- ドラフトモードtrueのときに何らかの表示とする
- ドラフトモードfalseのときは一切表示しない

というルールにしましょうか。
markdownのほうは手頃なものがなさそうですし、◆→←◆にしてしまってよいかな。

**Comment by kmuto** [comment]
markdownのはmd2inaoのspan redを使おうかな。md2inaoからmarkdownのほうに持っていきます。
