### ISSUE TITLE
//imageで引数[scale]を指定するとEPUB 3.0でエラーになる

### ISSUE THREAD

**Issue by suzukin** [kmuto/review#372]
回避策はいくつかありそうですが、ひとまず現状のご報告です。

//imageで[scale=0.XX]を指定した際、EPUB側では" width="XX%"に変換されます。すると、 value of attribute "width" is invalid; must be an integer のエラー判定をくらいEPUB 3.0のValidatorが通りません、のでiBook Storeでリジェクトされました（イマココ）。

**Comment by takahashim** [comment]
こちらですが、

```
//image[img1][画像その1][scale=0.5]
```

みたいなマークアップがあった場合、

```
<img src="foo/img1.png" alt="画像その1" class="width-050per" />
```
 
みたいなclassつきのimg要素を生成することで対応したいと思います(classは電書協のstylesheet互換で、`.width-050per { width:  50%; }`みたいな定義があることを期待している)。

**Comment by takahashim** [comment]
classがすでに指定されている場合もマージするようにしてみました。

**Comment by kmuto** [comment]
:+1: 

しかしこのあたりはTeX|InDesign|HTML共通の指定ができないので、いずれプレフィクスオプション記法が必要なんだろうか。

**Comment by suzukin** [comment]
おーすばらしい！

**Comment by takahashim** [comment]
リフローと固定で同じ指定というのに限界がある気もしないではなく…。
が、とりあえずないとepubcheck的に困るのでマージしますね。
