### ISSUE TITLE
hdを使うときにidだけで参照したい。

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#374]
```
= ch01
== A
=== B
```

というコードがあった場合、 ``@<hd>{A|B}`` のようにしないとBを参照できない。

```
= ch01
== A
==={id_b} B
```

としていれば、 ``@<hd>{id_b}`` だけでも参照できるようにしたい。

重複がある場合は、最初に見つかったものにするとか。

**Comment by kmuto** [comment]
重複はエラーかせめてwarningを出したいな。
