### ISSUE TITLE
doc/sample.ymlの記述についてmaker側の見直しが必要

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#386]
`doc/sample.yml`が新しくなったため、いろいろ対応してないものが増えてる(a-*とかcreditfileとかはpdfmakerではサポートしてない)ので、対応方針を決め、必要に応じて実装する。
(1.5.0には間に合わなさそうなのでその後で対応)

**Comment by takahashim** [comment]
## 前付・後付にファイルを挿入する機能

EPUBMakerには、catalog.ymlに記載されるファイル以外のファイルを、frontmatterとbackmatterに挿入する機能がある。PDFMakerは一部未対応。

### frontmatter

以下の順に挿入される。ファイルが存在しなければ通常は無視される（coverは特別に生成する機能がある）

* cover (カバー)
* titlefile (大扉)
* originaltitlefile  (原著大扉)
* creditfile  (権利表記)

## backmatter
同上（colophonは特別に生成する機能がある）
* profile (プロフィール)
* advfile (広告)
* colophon (奥付)
* backcover (裏表紙)

**Comment by kmuto** [comment]
TeXの場合は差し替えがTeXソースでやりたいときもPDFソースでやりたいときもありそう。
YAML分岐がだいぶ複雑になりそうですね。

pdfmakerもコードをいろいろ解体しないと触りづらい…。

**Comment by takahashim** [comment]
@kmuto  む、PDFソースのものを１ページ挿入するとかできるんですか？

PDFMakerも何か変更したいところがあげれば出していただければ。

**Comment by kmuto** [comment]
あいや、本をコマンド一発で作ろうとする場合だと、ソース状態でLaTeXビルドに混ぜたいときもあれば、PDFを用意してあとで差し替えたい（カバーとか広告とか奥付とか）ときもあるんだよなーという話でした。今のところ手元ではこのあたりはフックでなんとかしてる感じです。

とりあえず3.timesでtex compileしてるところを書き直したいので、そちらは別途実装を考えてみます。

**Comment by takahashim** [comment]
とりあえずRe:VIEWでは「TeXソースでやる場合」を実装して、PDFを用意する場合は別途何とかしてもらう方法が無難な気がしてきました。

* TeXでPDFを任意の場所に埋め込むのは難しそう
* Rubyのライブラリ（Prawnとか）で何とかする方法はよく分からなかった
* というかTeXでPDFを作ってから混ぜるのであればRe:VIEW外で処理してもあまり変わらなさそう

**Comment by kmuto** [comment]
これはもう実装済みということでcloseしていいですよね。

3.times なんとかならないかとずっと考えていたのですが、`LaTeX Warning: There were undefined references.` だけでいいのかとか、もしかしてTeX処理系によってはメッセージが違わないかとか頭が痛いので、手を出さないほうがいいと判断しました…。
