### ISSUE TITLE
Re:VIEWの公式ドメイン名の確保

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#391]
そういえば2/17辺りからドメイン名の値上げが各所で行われるそうなので、今日明日のうちにドメインをとっておこうかと思いました。

Sphinx(sphinx-doc.org)の真似をしてreview-doc.orgというのを密かに確保しているのですが、「review-doc」というワードは検索ノイズが多そうなので今ひとつかな…と思って今日に至っています。
どうもハイフンつきのものは検索には向かなさそう。

というわけで、

* reviewml.org
* reviewdoc.org

といった辺りが良いかと思うのですが、どうでしょうか？ > 特に @kmuto , @kdmsnr 
前者はtwitterのハッシュタグで使っていて実績があるのと、後者もまあまあ自然かなあというところです(でもreviewdocってasciidocみたいで微妙かも。あとreviewdoc.comは他の人に取られている。reviewml.comは空いている)。

**Comment by kmuto** [comment]
reviewml.org がよさそうな気がする（review-docからはリダイレクトさせる？）。ドメイン名の管理体制はどうしましょうかね。

**Comment by kenjis** [comment]
ところで、reviewml の ml って何ですか？

**Comment by kmuto** [comment]
markup language

**Comment by takahashim** [comment]
ユーザが直接触るものを意識すると〜MLとかになって、最終成果物を意識すると〜DOCとか〜BOOKといったネーミングになりそうな気がします（ちなみにreviewbook.comとreviewbook.orgは取られてました）。

ドメインの管理はどうするのがいいでしょうねえ…(Rubyの会でも悩んでいるのでした)。サイトはgithub pagesで済ませるとして、ネームサーバのおすすめはありますか？
あとreview-docの方は名前だけとって使ってないので特に対応の必要はありません。

**Comment by kmuto** [comment]
DNSだけならたとえばkmuto.jpとtopstudioでできるけど。

**Comment by takahashim** [comment]
ドメイン名やネームサーバについては、個人で管理するのはあまり問題ないのですが、何人かで変更可能な権限を共有するのが難しいなあ…ということなのでした。

**Comment by takahashim** [comment]
とりあえず reviewml.org でとってみますね

**Comment by takahashim** [comment]
とりました
