### ISSUE TITLE
@<u> のLaTeX表現

### ISSUE THREAD

**Issue by k16shikano** [kmuto/review#406]
提案です。現在は決め打ちで `jumoline`パッケージを前提とした `\Underline` になっていますが、より一般的な `\underline` とするか、`\reviewunderline` として`layout.tex.erb` に以下のような定義を追加するのはどうでしょうか。

{{{
\makeatletter
\@ifpackageloaded{jumoline}
{\newcommand{\reviewunderline}{\Underline}}
{\newcommand{\reviewunderline}{\underline}}
\makeatother
}}}

**Comment by takahashim** [comment]
:+1: いいんではないかと思います！（あ、`\Underline`をrenewcommandしている人は困るのかな…？）

**Comment by takahashim** [comment]
これですが、実際に試してみると、上記のコードをユーザカスタムマクロを読み込んだ後に置くとユーザが変更できなくなるし、ユーザカスタムマクロの前に置くと`\@ifpackageloaded{jumoline}`が無意味になるのでうれしくないですね……。

ということで、単純に`\newcommand{\reviewunderline}{\underline}`をユーザカスタムマクロの読み込み前に定義しておいて、必要であれば`\renewcommand{\reviewunderline}{\underline}`してもらうというのが確実な気がしてきました。

**Comment by k16shikano** [comment]
ユーザカスタムマクロ！ 

いずれにせよ、ユーザが別途個別にインストールしないといけないパッケージが変換部の仕様としてハードコードされてるのはつらい、という状況が解消されればよいと思っています。 \reviewunderline のデフォルトについてはおかませします。
