### ISSUE TITLE
PDFMaker: Wrong bounding box may be used if there exist two images having the same basenames

### ISSUE THREAD

**Issue by orangain** [kmuto/review#421]
# 問題

`abc.png` (HTML/EPUB向け) と `abc.pdf` (LaTeX/PDF向け) のように、拡張子だけが異なる2つの画像ファイルを`images`ディレクトリに置いて、`//image[abc][...]` で画像を挿入した場合に、PDFMakerで出力されたPDFにおいて画像が意図しないサイズになることがあります。以下のスクリーンショット（左側）では、小さくなっています。

![_2015_05_01_19_18](https://cloud.githubusercontent.com/assets/532251/7429135/20037d74-f037-11e4-9531-0e1fd1e27528.png)

# 原因

LATEXBuilderではPDFが優先され、texのソースには以下のようにPDFのファイル名が挿入されます。

```tex
\includegraphics[width=\maxwidth]{./images/abc.pdf}
```

一方PDFMakerでは、PNG/PDFの両方の画像が作業ディレクトリにコピーされます。コピーされた後に[xbb/bbファイルが作成されます](https://github.com/kmuto/review/blob/906d0eb052cd6235b520df677060b4a8311a8f55/lib/review/pdfmaker.rb#L211-218)が、PDF用のxbb/bbファイルはPNG用のxbb/bbファイルで上書きされてしまいます。これは`extractbb`が生成するxbb/bbファイル名は画像ファイルの拡張子をxbb/bbに置き換えたものになり、拡張子だけが異なる2つのファイルを対象に処理すると、引数の順で後のものが前のものを上書きしてしまうためです。

これによって、PDFのサイズとは関係ないPNGのサイズのBounding Boxの情報が使われるため、最終的に画像が意図しないサイズで表示されます。

# 対応策（案）

以下のような対応策が考えられますが、あるべき姿を判断しかねるためIssueとしました。そもそも、このように拡張子だけが異なる複数の画像ファイルを置くことを想定していないようでしたら、教えて頂ければと思います。

1. 最近のLaTeX処理系では、適切に設定していればxbb/bbファイルが存在しない場合に自動で`extractbb`を実行してくれるので、xbb/bbファイルを作らないようにする。
    1. pdfmakerのhook_beforetexcompileでxbb/bbファイルを削除する。(Re:VIEW本体に変更を加えずにad-hocに対応可能)
    2. pdfmakerにオプションを追加し、xbb/bbファイルを作らないように設定できるようにする。
2. 画像を作業ディレクトリにコピーする際に、実際に使われている画像だけをコピーするようにする。(epubmakerのverify_target_imagesオプションに相当)

**Comment by kdmsnr** [comment]
ビルダーごとにディレクトリを分けることが可能です。

https://github.com/kmuto/review/wiki/ImagePath

**Comment by orangain** [comment]
見落としてました。。ありがとうございます！
