### ISSUE TITLE
某電子取次EPUB仕様対応

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#429]
review-epubmaker、htmlbuilderの両方を調整する必要あり。別のツールにしたほうがいいかも。

仕様全体は公開を許可されていない＆恣意的でチェッカーがないため、仕様からのmustと思われる内容やRe:VIEW制作物納品時に修正要求された項目に基づく。
仕様にないものもあるような…。

* [x] epubcheckが通り、Readiumで表示検証していること。→これは問題ない
* [ ] 電書協ガイドに準拠すること。特にフォルダ構成、opfファイル名、カバーと奥付のファイル名は固定、作品名・著者名とへの読みの指定。（スタイルファイル内容や章ファイル名などにはこれまでツッコミはこず。）→epubmakerとbuilderで設定を変更できるようにする調整が必要
* [x] いっさいの外部リンク(aでhttp://〜等でブックの外に出るもの)を禁止。(が、矛盾する記述もあり）→コンテンツの作り方なのでRe:VIEW自体には関係浅い
* [ ] 表（table）は禁止。画像化すること。（必ずしも禁止ではない気もするが…）→builderで何か代替画像を優先利用する手法は必要かも
* [ ] 本文の図版は原則600x800pixel以上、2000x1536pixel以下。→lintツールがほしいところ。RMagickがあったらそれを中で呼び出す、みたいなことはできるかもしれないけど。
* [x] CSSでの絶対文字サイズ指定（pt等）は禁止。相対指定を使うこと。→CSSの作りなのでRe:VIEWには関係浅い
* [ ] カバーと目次を用意すること。→今の目次仕様でだいじょうぶだったかな…
* [x] 章扉から目次へのリンクはないこと。（？）→そもそも章扉的な機能を入れてなかったので関係なさそう。

**Comment by takahashim** [comment]
cf #251

**Comment by suzukin** [comment]
参考になるか微妙ですが過去の経験より

> 電書協ガイドに準拠すること。特にフォルダ構成、opfファイル名、カバーと奥付のファイル名は固定、作品名・著者名とへの読みの指定。（スタイルファイル内容や章ファイル名などにはこれまでツッコミはこず。）→epubmakerとbuilderで設定を変更できるようにする調整が必要

これは
> いっさいの外部リンク(aでhttp://〜等でブックの外に出るもの)を禁止。(が、矛盾する記述もあり）→コンテンツの作り方なのでRe:VIEW自体には関係浅い

明確にNGと取引条件にあるが、先方の検査が厳密でないため、そのまま発売される場合と先方が発見し修正を依頼される場合があります。

> 表（table）は禁止。画像化すること。（必ずしも禁止ではない気もするが…）→builderで何か代替画像を優先利用する手法は必要かも

これはリジェクトくらったことないなあ。

**Comment by kmuto** [comment]
ありがとうございます、suzukinさんが使ったところとおそらく同じところなんですが、基準がイマイチよくわからないんですよね……。伝言ゲームのshouldとかmayが制作に届く頃にはmustになってしまってるというか。

ほぼそのままで通ったというのは耳寄り情報です。でも、電書協ガイドからの逸脱は版元責任において、というのがついていた気もするので、制作についてはやっぱり最大安全側に振られるのか……。

**Comment by suzukin** [comment]
フィードバックその2、「」部分は弊社制作担当のメールから抜粋です。具体的なストア名は伏せさせていただきます。

> いっさいの外部リンク(aでhttp://〜等でブックの外に出るもの)を禁止。(が、矛盾する記述もあり）→コンテンツの作り方なのでRe:VIEW自体には関係浅い

「○○○でEPUBファイルがエラーになりました。EPUB中に外部リンクがあるのが原因といわれております。ざっとみたところ、奥付に商品詳細ページへのリンクが張られている箇所があり、そこが原因のひとつかと思われます（他のストアへの購入リンクがあるページへのリンクは、自社運営サイトで会ってもほとんどのストアで審査にひっかかります）。」

「また、XXXより以下の修正依頼を頂いております。EPUBの修正をお願いできますでしょうか。opfファイル内にページの綴じ方向を指定するタグ(page-progression-direction)がございませんでした。」


綴じ方向タグについては、https://github.com/kmuto/review/pull/435 で解消されていることを確認できました。次期バージョン1.7.0？ でGem版にも組み込まれるものと期待しております。現場からは以上です。

**Comment by suzukin** [comment]
くどいようですが外部リンクについてのアップデートです。なんどかキャッチボールして結論としてはやっぱりダメでした（弊社制作担当より）。

```
差異がありますが、基本的にどのストアも、外部リンクについてはNGになっている、とお考えください。
ストア側で挙げている理由としては、おもに以下の点になります。
・競合ストアへの誘導になる可能性がある
・リンク先のリンクがきれている（将来的にきれる）可能性がある
・ネットワークにつながっていない端末でリンクを踏んだときにエラーになる、ということに対してお客様のクレームを回避する
このことから、通常EPUBファイルを制作する場合は、外部リンク（EPUBファイルの外部です）は張らず、URLはテキストとして掲載することにしております。
```

kmutoさんがコメントされているようにこれはやっぱりコンテンツマターで捉える問題なんでしょうかね……。aタグありなしをオプションで選べるようにして、入稿するストアにあわせて出し分けられると嬉しいことは嬉しいのですが。

**Comment by takahashim** [comment]
@suzukin  オプションで外部リンクを全部無効にするか、外部リンクがあった場合に警告を出す機能をつけるかするのがいいんですかね…。必要な機能かはちょっと悩ましいですが。

**Comment by mhidaka** [comment]
「opfファイル内にページの綴じ方向を指定するタグ(page-progression-direction)がございませんでした。」
ひつじのほうでも連絡ありました。ｳｯ

https://github.com/kmuto/review/pull/435 を参考に対応してみます

**Comment by takahashim** [comment]
page-progression-direction、デフォルトでltrにしちゃってもいいのかもしれませんね…。

**Comment by kmuto** [comment]
#499 のimgtableが入ればひとまずcloseできそうかな

**Comment by kmuto** [comment]
おおむね必要事項は達成できたと思うのでcloseします。

マーケット個有のTipsはいろいろありそうですが、customized_epub.mdかWikiかを利用することにしましょう。
