### ISSUE TITLE
epub出力時の（縦書き）右綴じ対応について

### ISSUE THREAD

**Issue by keiji** [kmuto/review#431]
縦書きについてはCSSのカスタムで対応可能ですが、右綴じ（rtl）についてはepub出力後、content.opfの&lt;spine&gt;をカスタムする必要があるという認識です。

縦書きおよび右綴じ対応について、今後、Re:VIEWで対応を検討する予定はありますか？

**Comment by takahashim** [comment]
縦書き・綴じ方向については、具体的な要望を出してもらえれば対応できるかと思います。
（その辺は異様に奥が深いので…。例えば「表の中の一部のセルだけ縦書き」みたいなのは華麗に却下したいところではあります）

**Comment by kmuto** [comment]
右綴じ対応自体はパラメータに入りましたので、いったんこのissueはcloseします。

縦書きはCSSのほか、代表的なものでは縦中横のマークアップが必要なので、これは実際に必要なたびにパッチやissueなどにて解決していきましょう。

**Comment by keiji** [comment]
👍
