### ISSUE TITLE
footnoteと最新のconfig.ymlの組み合わせでepubmakerがコケる

### ISSUE THREAD

**Issue by suzukin** [kmuto/review#433]
しばらくハマっているので投げます……。

脚注（@<fn>{}, //footnote[][]）と最新のconfig.yml（ https://github.com/kmuto/review/blob/master/test/sample-book/src/config.yml ）を組み合わせると、epubmakerのコンパイルが通らなくなりました。Re:VIEWのバージョンを1.3.0〜2.0.0beta1まで試してみましたがいずれもダメでした。以下エラー文です。

```
Create ch01.html from ch01.re.
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:413:in `block in pull_event': Undefined prefix epub found (REXML::UndefinedNamespaceException)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:411:in `pull_event'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:184:in `pull'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rexml/parsers/streamparser.rb:18:in `parse'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rexml/document.rb:241:in `parse_stream'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:311:in `write_info_body'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:290:in `build_chap'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:207:in `block (2 levels) in build_body'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:206:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:206:in `block in build_body'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:191:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:191:in `build_body'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/lib/review/epubmaker.rb:61:in `produce'
	from /usr/local/lib/ruby/gems/2.2.0/gems/review-1.5.0/bin/review-epubmaker:44:in `<top (required)>'
	from /usr/local/bin/review-epubmaker:23:in `load'
	from /usr/local/bin/review-epubmaker:23:in `<main>'
```

試しにオフィシャルで提供されている sample-book（ https://github.com/kmuto/review/tree/master/test/sample-book/src ）を使ってみます。このサンプル ch01.re には脚注がないので16〜18行目を以下の通り変更します。

```
L16: ２行以上以上空いていても１行空いているのと同様に処理します@<fn>{fntest}。
L17: 
L18: //footnote[fntest][test]
```

やはりepubmakerはエラーになります。ちなみにpdfmakerはちゃんと動きます、実行結果は添付のとおりです。

ただ、手元にある昔のプロジェクトは脚注ありでも動いていたので、今度はconfig.ymlを遡って調べてみます。と、どうやらこのコミット 310a26bef9df0be3c15d812346b92f94c6fdf7df からコンパイルが通らなくなった模様です。どのパラメータが影響しているか、はたして本当にconfig.ymlの影響なのか引き続き調査中です。
![2015-06-24 14 47 28](https://cloud.githubusercontent.com/assets/5789999/8324182/a8472106-1a88-11e5-95fa-d45f26781eff.png)

**Comment by suzukin** [comment]
ちなみにエラー時点で「book-20150624-1734-m5rblm」といった感じのテンポラリフォルダはありますが「book-epub」は生成されません。book-20150624-1734-m5rblmの中にある ch01.html の脚注部分は問題なく作られていました。
![2015-06-24 16 02 15](https://cloud.githubusercontent.com/assets/5789999/8324333/7bf59536-1a8a-11e5-9930-c75538519ec4.png)

**Comment by takahashim** [comment]
@suzukin ひょっとして、layouts/layout.html.erb を使われていますか？
もし使っている場合、そのlayout.html.erb冒頭のDOCTYPE宣言とhtml要素の中身はどうなってますか？

**Comment by kdmsnr** [comment]
``epub:type="noteref"`` みたいなのがREXMLで引っかかってるような

**Comment by takahashim** [comment]
（なんとなく、layout.html.erbの中身がXHTML1.1 になっているのに EPUB3を作ろうとしていて、xmlns:epub がなくてエラーになっているのではないかと推測しています）

**Comment by kdmsnr** [comment]
layouts/layout.html.erb を以下のように……

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2011/epub" lang="ja" xml:lang="ja">
<head>
```

**Comment by kdmsnr** [comment]
``layout.epub.html.erb`` みたいなのを作ったほうがいいですかねえ。

**Comment by suzukin** [comment]
おー！ 進行中のプロジェクトはご指摘通り layouts/layout.html.erb が入ってました（layout.tex.erbをいじっていたときにlayout.html.erbも入ってた）、そして推察通りXHTML 1.1になっていました。

ただ、sample-book は layouts フォルダがそもそもないですね。。

**Comment by takahashim** [comment]
ひょっとしてconfig.ymlのhtmlversionを5にしないといけないのが自動で行われていないのかもですね…

**Comment by kdmsnr** [comment]
あ、手動で変えればエラー出ませんね。

``htmlversion: 5``

**Comment by takahashim** [comment]
#434 でどうでしょうか…

**Comment by suzukin** [comment]
@takahashim @kdmsnr 検証、アドバイスありがとうございました。手動で5にすることでエラー回避できることをこちらでも確認できました。手元のデータでは脚注を使わないとエラーはおきなかったので、、htmlのバージョンに起因していたところまで特定できませんでした。XHTML 1.1の件は、実は自分の中で別のissueで管理していたので一気に2つ解決したことになります。今夜はゆっくり眠れそうです。

**Comment by takahashim** [comment]
@suzukin いちおう最新版ではepubversionを3にすれば自動でhtmlversionも上書きされるはずです

**Comment by suzukin** [comment]
あ、コメントしてませんでした。こちらでも上記の動作確認できました。ご対応ありがとうございます！
