### ISSUE TITLE
EPUBMaker: 第1レベル見出しに[nonum]をつけるとページが欠落する

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#436]
章がない書籍（小説）の場合、章見出しがないものもあるわけですが、そのまま章見出しナシでEPUBを作ろうとするとその章（本文）がページごと抜けてしまいます。
仕方ないので空の見出しを作り、それに「[nonum]」を付け加えても、結局そのページが抜け落ちたままです。

サンプルは https://github.com/takahashim/nayamino_hitotoki/tree/nonum です。nonumブランチの方では正しいEPUBが生成できません（生成されるEPUBは https://github.com/takahashim/nayamino_hitotoki/raw/nonum/archives/book.epub です）。masterブランチの方ではEPUBは生成できますが、PDFでは第XX章というのが表示されてしまいます。

**Comment by takahashim** [comment]
とりあえずEPUBそのものはcatalog.ymlの内容通りのファイルを拾うのが良さそうな気がします

**Comment by kmuto** [comment]
はい、これバグですね。

見出しナシにすると目次どうしよう問題があり。
あと、h2からいきなり始められたりすると、目次作るのが辛くなるという問題あり。

**Comment by takahashim** [comment]
見出しナシは、現状ではとりあえず目次もなくて良さそうな（前から読めばそのうち読める）。根本的な対策としては、

* 「章扉（のページ）」という概念を追加する
*  catalog.ymlの構造に手を入れて、単に文字列じゃない複雑なデータ構造を入れられることにして、見出しがなくてもページにはリンクできるようにする

辺りが理想でしょうか（前者も後者で実現する形？）。

**Comment by suzukin** [comment]
PDFしか作成していなかったのでこのバグには気付かなかったのですが、こちらも高橋さんの状況に近い使用例がありました。具体的には「章見出しがあり目次にも反映されて欲しいけど章番号は不要」というケースで、個々の章が独立している雑誌（というかムック）的な用途です。

**Comment by kmuto** [comment]
cf #554 と #555

**Comment by kmuto** [comment]
#555 で対応しました。ドキュメントが必要かな…
