### ISSUE TITLE
bib参照がbib.html固定になっていて、htmlextで拡張子を変えても追従しない

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#440]
本来は「bib.<ext>」という名前自体も固定なのはどうか、という問題はあるが。
とりあえずhtmlextを見るように変更する。

**Comment by takahashim** [comment]
拡張子じゃない部分については、実はconfig.ymlに「bib_file: "hoge.re"」と書けば自由に設定できるようになっている気がします。

**Comment by takahashim** [comment]
cf. d17c84e3d42dfc9496cb7b26c9a93e3672d735f8

**Comment by kmuto** [comment]
これ解決してますね、ありがとうございます。
