### ISSUE TITLE
PDF出力した場合、リストと図の採番がズレるケースがある。

### ISSUE THREAD

**Issue by mhidaka** [kmuto/review#444]
Re:VIEWからreview-pdfmakerでPDF出力する際に以下のような記述があると採番がおかしくなりました。

```
～次の通りです（@<list>{識別子}）。

//list[識別子][]{
 ... 略 ...
//}
```

このようにリストのタイトルが空だと、LaTeXでは、以後の採番がズレてしまう現象を確認しました
（リスト1.10のところがリスト1.9と表示される挙動からタイトルが空のリスト採番を無視するようです）。

図でも同じく、図番号がズレていました。挙動から察するにLaTeXの不具合かもしれません。。
回避案としてRe:VIEWコンパイル時にエラーにする？←これは既存のreファイルに影響しそう。

**Comment by kmuto** [comment]
git HEADで見ていますが、TeXビルダでは``\reviewlistcaption{リスト1.1: }`` ``\reviewlistcaption{リスト1.2: AAA}
 ``
のようになって採番がずれることはありませんでした。

識別子が重複していませんか？

**Comment by mhidaka** [comment]
おや、こちらの環境依存なのかな。。。後ほど最少構成で条件を再確認してみます。

**Comment by kmuto** [comment]
こちらはどうなったでしょうか？

**Comment by mhidaka** [comment]
すごい久しぶりに試してみました。最新版では再現しないのでCloseいたします。
