### ISSUE TITLE
htmlbuilder: listnum、emlistnumコマンドが動作しない

### ISSUE THREAD

**Issue by turky** [kmuto/review#449]
htmlbuilderでlistnum、emlistnumコマンドが使えなくなっているようです。状況は以下の通りです。

* pygmentsはインストール済み
* bコマンドなどでスタイルを設定したいので、設定ファイルでpygmentsを無効にしている
* listnum、emlistnumの結果が行番号の指定がなく、スタイルも割り当てられない状態
* pygmentsを有効にすると行番号とスタイルが割り振られる

pygmentsを無効にしたときに期待の動作をしないようです。

**Comment by suzukin** [comment]
あ！ これ数カ月前に自分も躓いたところです……。
後ほどご本人からも解説あると思いますが、下記のコメントを読んで納得した記憶があります。
https://github.com/kmuto/review/commit/6bb810b69f6cb7c0e0e0a45cdaa8a38314952b48

**Comment by kdmsnr** [comment]
修正しました。どうでしょうか。

**Comment by turky** [comment]
ありがとうございます。pygmentsを有効／無効にした場合の両方で、期待の動作をしていることを確認しました。

**Comment by takahashim** [comment]
そうか、pygmentsのチェックが甘かったんですね。失礼しました :bow:
