### ISSUE TITLE
pdfmakerで付録が生成されない

### ISSUE THREAD

**Issue by suzukin** [kmuto/review#450]
ちょっと実際の原稿をお見せできないのと、再現性がイマイチなのですが……。catalog.ymlが以下の状況のときに、
```
PREDEF:

CHAPS:
  - A.re

APPENDIX:
  - B.re

POSTDEF:
  - C.re
```

pdfmakerで付録が出力されない（B.re自体がどこにも出てこない）現象が出て困っています。なお、epubmakerは問題ありません。

ちなみに、まったく同じ原稿を、
```
PREDEF:

CHAPS:
  - A.re
  - B.re

APPENDIX:

POSTDEF:
  - C.re
```
や
```
PREDEF:

CHAPS:
  - A.re

APPENDIX:

POSTDEF:
  - B.re
  - C.re
```
に変更した場合は問題なく出力されます。また、B.reのファイル名はappendix.reではありません。何か心当たりがありましたら情報いただけると助かります。シルバーウィーク初日がこれでorz

**Comment by takahashim** [comment]
とりあえずサンプルを作ってみましたが、問題なさそうです。

https://github.com/takahashim/review-test-20150919

生成結果のPDFは https://github.com/takahashim/review-test-20150919/blob/master/book.pdf です。

config.ymlで`debug: true`という設定を追加してPDFをつくると【bookname】-pdf というディレクトリに*.texファイルができると思うので、そこでB.texが生成されているかどうか、【bookname】.texというファイルで`\input{B.tex}`という行が入っているかどうかをご確認ください。

**Comment by suzukin** [comment]
反応ありがとうございます。
状況としては、B.texが生成されているものの【bookname】.texに \input{B.tex} はなく、\reviewappendixにC.texが入っていました。ただし生成させるPDFは付録CにはなっておらずPOSTDEF（\backmatter）で処理されているように見えます。ちょっと再現サンプルを作ってみます。

```
\input{A.tex}

\renewcommand{\chaptermark}[1]{\markboth{\appendixname\thechapter~#1}{}}
\reviewappendix
\input{C.tex}
```

**Comment by suzukin** [comment]
当方の独自拡張の部分の可能性が高いのでいったんクローズさせていただきます。お騒がせしました。
