### ISSUE TITLE
cannot use `imagedir` in config.yml

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#453]
### 現象

config.ymlで`imagedir`を定義しても機能しないようです。
- PDF: エラーが出て止まる
- EPUB: 生成はされるが、画像は表示されない
### 原因（実装に関する話）
- （前提） 画像のパスにはソースのパスとターゲット（生成結果）のパスがあるのに注意。`imagedir`はソースのパスのみを指定するべきもの（ということにする）
- 画像のベースディレクトリ`basedir`はReVIEW::Book::ImageIndexオブジェクトのインスタンス変数として管理されている。
  - この値はReVIEW::Book::Compilableモジュールのimage_indexメソッドで作られる（この時点のパスは`"#{book.basedir}/#{@book.image_dir}"`）。これがImageIndex#initializeの引数として渡されて、`@basedir`の値となる。
- 画像探索用としてはImageFinderクラスのオブジェクトが使われている。このオブジェクトはImageIndexのコンストラクタで作られていて、値としては`@basedir`が使われる。これがソースの画像パスとして使われることになる。
- 実際にimgタグのsrcのパスを生成するときにも、どの画像かの指定にImageIndexを使ってひいてくるため、ImageIndexの値が使われる。これがターゲットの画像パスになる。
- 結果、ソースの画像パスとターゲットの画像パスが一緒になってしまっている。現状では修正困難。
### 対策
- ImageIndexの引数を変えるべき？
  - basedirを渡すのではなく、bookかconfigを渡して、ソースの画像パスもターゲットの画像パスもそこから両方作れるようにするとよさそう

**Comment by m-shibata** [comment]
#756 で話をしたのですが、現時点での最新版である f77429992fcf6c09c66a49fdc2f6b3ff418d7d80 を試してみたところ、
`imagedir`はepub/pdfともに期待通り動いているように見えます。

実際に試したのは次の手順です。

```
$ review-init samplebook
$ cd samplebook
$ echo "imagedir: altimage" >> config.yml
$ mv images altimage
$ rake epub
$ rake pdf
```
サンプルとして生成されたカバー画像のディレクトリを`altimage`にリネームした上で、
`config.yml`にて`imagedir`にリネームしたディレクトリを指定したところ、
epubもpdfも生成時にエラーとはなりませんでした。

PDFファイルはカバー画像としてaltimageの画像が使われていますし、
EPUBデータの中の`img`タグのパスも期待どおりの値になっていました。

`imagedir`の挙動として何か異なるのかもしれませんが、とりあえずはご報告まで。

**Comment by kmuto** [comment]
カバーはちょっと特殊な経路をたどるので、カバーの挙動は参考にならないのでした。

適当なファイルを画像ディレクトリに置き、reファイルのimageやindepimageを使ってそれを参照すると、EPUBではmissing、TeXではコンパイルエラーになりませんか（手元のmaster HEADではやはり失敗します）。

**Comment by m-shibata** [comment]
なるほど……

こちらで`image`や`indepimage`を使って試してみたところ、おっしゃるとおりEPUBでもPDFでもダメでした。
十分確認できていなかったようで、申し訳ありません。

```
$ review-init samplebook
$ cd samplebook
$ echo "imagedir: altimage" >> config.yml
$ mv images altimage
$ cp altimage/cover.jpg altimage/foo.jpg
$ cp altimage/cover.jpg altimage/bar.jpg
$ echo '= サンプル' > samplebook.re
$ echo '//image[foo][画像1]' >> samplebook.re
$ echo '//indepimage[bar][画像2]' >> samplebook.re
$ rake epub
  => warning: no such image
$ rake pdf
  => LaTeX Error: File `' not found.
```

で、自分の本番環境だとなぜうまくいっていたかと言うと、
上記で言うところの`altimage`とは別に`images`にも同じファイル名で画像が存在したからのようです。
`images`にはオリジナルのカラーの画像を、`altimage`にはそれらをモノクロにした画像を置いていました。
電子版は`config.yml`を、印刷版は`config-print.yml`から`config.yml`を`inherit`しつつ、
`imagedir: altimage`を指定していたために、`ImageIndex`か`ImageFinder`は`images`を参照しつつ
`copy_image`は`altimage`を参照した結果、うまくいっているように見えていたようです。
