### ISSUE TITLE
章ごとの著者を表示したい

### ISSUE THREAD

**Issue by huideyeren** [kmuto/review#454]
現在、色々な人の合同誌を作ろうと考えてます。
各章ごとに別々の人に書いてもらうことを考えていますが、
Re:VIEWでは、章ごとに著者データを変え、
各章の冒頭にその章の著者を表示させる方法はございますか？

**Comment by kmuto** [comment]
章ごと著者情報というのはRe:VIEW標準では持ち合わせていないので、何か工夫する必要があります。

たとえば自分がエッセイ集を制作したときには、infoタグを流用して作りました。

```
= サンプル
//info{
●Gonbei
//}

あああ
```

そのときはHTML/InDesignだったのでスタイルについては悩まなかったのですが、TeXについてはinfoブロックの部分を置き換える必要があり、review-ext.rbでたとえばこんなかんじでしょうか。

```
# -*- coding: utf-8 -*-
module ReVIEW
  class LATEXBuilder
    def info(lines, caption = nil)
      puts "\\vspace{-3\\Cvs}"
      puts "\\begin{flushright}\n"
      lines.each do |line|
        blocked_lines = split_paragraph(lines)
        puts blocked_lines.join("\n\n")
      end
      puts "\\end{flushright}\n"
      puts "\\vspace{3\\Cvs}"
    end
  end
end
```

目次にも入れたい、ということだと、review-ext.rbでがんばるよりも何かマップファイルを作って、設定ymlファイルのpdfmaker: / hook_beforetexcompile: パラメータに指定したフックスクリプトで生成texファイルをいじる、というようにしたほうがよさそうです。

**Comment by huideyeren** [comment]
ご連絡が遅れてしまい申し訳ありませんでした。
上記方法で対応することにします。

**Comment by kmuto** [comment]
ひとまず閉じます。

configのYAMLでこれを実装するのは難しそう…。
