### ISSUE TITLE
Re:VIEW PEG版をいったん別の名前のgemにしたい

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#455]
PEG版は粛々と作業中なのですが、現行の正式版と一緒に使うことができないのでなかなかデバッグしづらいところがあります。
（review-epubmaker-legacyのように「同一gemの中で実行ファイル名だけ変える」という作戦も考えられますが、同名ライブラリに大幅に手を入れる形で開発しているため、共存させるのが困難なのでした…）

そこでとりあえず別のgemの名前を作って、そちらでもリリースしておくと使い比べられるのでいいのではないか、ということを先日 @mhidaka さんたちとしていたのですが、どんなもんでしょうか。

**Comment by takahashim** [comment]
名前の案としてはreview-ngとかreview-pegとかreview-astとか出ています

**Comment by kdmsnr** [comment]
よいと思います

**Comment by kmuto** [comment]
よいのではないでしょうか。名前は基本お任せしますが、ngだとforkした「いいもの（安定版）」と勘違いする人がいそうなので、実験的な感じのある-pegとか-astとかのほうがよさそう。

**Comment by mhidaka** [comment]
reivew-peg でどうでしょうか。素直に読み取れたのでエンジニア向けの名前だとおもいました。

**Comment by takahashim** [comment]
ではreview-pegで！

**Comment by takahashim** [comment]
出してみました！
https://rubygems.org/gems/review-peg

`gem install review-peg` でインストールできるはず。

全コマンドに`-peg`というpostfixがつきます。`review-epubmaker-peg`みたいな。

**Comment by mhidaka** [comment]
:+1: つかってみます！
