### ISSUE TITLE
listnumのキャプションが2回表示される

### ISSUE THREAD

**Issue by vvakame** [kmuto/review#465]
PDFを作った時にreview 1.7.0とreview-peg0.2.0双方でlistnumのキャプションが2回表示される。
見た感じ、reviewlistcaptionが意図せず複数回出力されていそうです。

```
$ review-compile --version
review-compile 1.7.0
$ cat cattaka_net.re
= test

@<list>{a}

//listnum[a][b]{
c
//}
$ review-compile-peg --target=latex cattaka_net.re
\chapter{test}
\label{chap:cattaka_net}

\reviewlistref{10.1}
\reviewlistcaption{リスト10.1: b}
\reviewlistcaption{b}
\begin{reviewlist}
 1: c
\end{reviewlist}
```

**Comment by takahashim** [comment]
う、これはエンバグしてました…。
masterの方は https://github.com/kmuto/review/commit/b8f682f1e591c3bea587cc5a3d70d492de504f6c で、pegの方は #468 で修正されているはずです

**Comment by vvakame** [comment]
できればreview版も1.7.1で出して貰えると嬉しいです…！

**Comment by takahashim** [comment]
@kmuto @kdmsnr これは1.7.1を出した方がいいでしょうか…？

**Comment by kdmsnr** [comment]
出してもいいと思います！

**Comment by takahashim** [comment]
こちらリリースしました

**Comment by mhidaka** [comment]
review版 1.7.1、listのリストキャプションが表示されていませんです。

**Comment by takahashim** [comment]
どうやらhighlightingしてると問題ないけどhighlitingしてないとNG、という現象のようでした…。

**Comment by takahashim** [comment]
これでいけるはず…っ。
あともう少しテスト追加しておきます

**Comment by mhidaka** [comment]
:clap: ありがとうございます。

**Comment by mhidaka** [comment]
@takahashim これを1.7.2としてリリースしてもらうことは可能でしょうか。
いまRe:VIEW解説本を書いてて、安定したリリースを指定できないのでmaster/HEADを見ている状況です・・・！

**Comment by takahashim** [comment]
#475 を試してみています。とりあえずlist/listnum/emlist/emlistnumのsyntax highlightあり・なしそれぞれで見た感じでは問題なさそう。

**Comment by mhidaka** [comment]
:+1:

**Comment by takahashim** [comment]
v1.7.2、リリースしました！のでこのissueは閉じますね。

**Comment by mhidaka** [comment]
おつかれさまっした！
