### ISSUE TITLE
release v1.7.1 (bug fix version)

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#470]
> できればreview版も1.7.1で出して貰えると嬉しいです…！
> https://github.com/kmuto/review/issues/465#issuecomment-159121695

というわけで、v1.7.1をリリースします。ちょうど29日ですし。

v1.7.1に入るのは 

* #465 listnumのキャプションが2回表示される

と、あとは

* #457 review-init: fix to suport epub2 and epub3

も入れたいです（後者については、HTMLファイルを生成する場合とEPUBMakerを使った場合とで、拡張子をどうするかについて整理した方がいいかと思ったのですが、とりあえずこれでいいような気がしてきました）。

**Comment by takahashim** [comment]
上記2つをmergeしました。これからリリースします。

**Comment by takahashim** [comment]
リリースしました!

**Comment by kmuto** [comment]
:+1:

**Comment by vvakame** [comment]
:+1:
