### ISSUE TITLE
review-pdfmaker 1.7.1で番号なし箇条書きの途中のコメントの扱い

### ISSUE THREAD

**Issue by mhidaka** [kmuto/review#472]
review-pdfmaker 1.7.1において以下の番号なし箇条書き文を出力したところ、
途中のコメント行も一緒に表示されていました。

```
 * App Components
 ** ActivityCompat : getRefererやrequestPermissionsなど、API Level4以降で追加されたActivityの機能のバックポートを提供します
 ** Fragment：Android frameworkのFragmentへのバックポートを提供します。これを使用する時ActivityはFragmentActivityを継承する必要があります
 #@# onCreateAnimationがあるとかonTrimMemoryがないとかあるけど細かいので触れない
 ** NotificationCompat：リッチなNotificationの機能を追加します
```

![image](https://cloud.githubusercontent.com/assets/322019/11875606/da181dd6-a528-11e5-8794-d04edc1785d8.png)

期待値としてはコメントアウトされてほしいなー、という気持ちがありますが、いかがでしょう・・・！

**Comment by takahashim** [comment]
なんとなく、`next if line =~ /\A\#@/`を追加するといけそうな。あとで調べてみます

**Comment by takahashim** [comment]
む、これってひょっとして、

```
 * App Components
 ** ActivityCompat : getRefererやrequestPermissionsなど、API Level4以降で追加されたActivityの機能のバックポートを提供します
 ** Fragment：Android frameworkのFragmentへのバックポートを提供します。これを使用する時ActivityはFragmentActivityを継承する必要があります
#@# onCreateAnimationがあるとかonTrimMemoryがないとかあるけど細かいので触れない
 ** NotificationCompat：リッチなNotificationの機能を追加します
```

というように、コメントの先頭文字が行頭に来ていれば1.7.1でも問題が起きなくなったりしますか？

**Comment by kdmsnr** [comment]
コメントをインデントしたいという話？

**Comment by mhidaka** [comment]
@takahashim さんの指摘通り、
コメントの先頭文字が行頭にきていれば、コメントがただしくコメントアウトされます。

つまり仕様通りの挙動・・・！

つかっているテキストエディタ（Atom）の癖で開業時に `#@# coomment` の先頭文字列もインデントされてしまったようです。お手製のLintで警告出すぐらいがちょうどいいかな、と思いました。
