### ISSUE TITLE
review-compile の -a を削除

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#481]
なくてもいい気がする。

**Comment by takahashim** [comment]
要らないんでしょうかね…（私は使ってないので良くわからない）。

`--directory=DIR`オプションも不要ですか？　この2つがなくなれば、:dirモードが不要になります。

**Comment by kdmsnr** [comment]
なくすのではなく、章の指定がないときに ``-a`` と同様の挙動をすればいいかなと。

**Comment by takahashim** [comment]
なるほど。
少し見てみたところでは、review-compile -aとreview-epubmakerとreview-pdfmakerの挙動がそれぞれ細かいところが違ってそうなところが気になりますね…。

**Comment by kmuto** [comment]
-aは私も使ってないですね。最初からあるオプションなので、あおきさんが使ってるのかなぁ…

**Comment by kdmsnr** [comment]
``--directory`` いらない気がしますね。ARGVの数でmodeの切り替えをすればよさそうです。

**Comment by kmuto** [comment]
review-compileのほうはこれら捨てますか?
