### ISSUE TITLE
highlightをRougeに変更？

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#485]
https://github.com/jneen/rouge

**Comment by kmuto** [comment]
compatible with pygments ではあるけれども、既存制作物にかかわる互換性が心配なところ。pygments.gemに信頼性や継続性の疑義があるなら変える価値はありそうですが。
選択可能にさせるのも難しい？

**Comment by kdmsnr** [comment]
選択式でもいいと思います。
pygmentsは最終的にpythonが必要なので、rougeのほうがいいかなと。

**Comment by kdmsnr** [comment]
HTMLが違ってくるのでテストの修正が大変。あとまわし。

**Comment by takahashim** [comment]
#684 で対応しました。

* config.ymlでrougeを指定して使います

```yaml
highlight:
  html: "rouge"
````

* 構文要素についてはclass属性で指定しているので、CSSを変更しないと反映されないのに注意。doc/sample.cssは対応済み（のはず）です
* `//listnum`、`//emlistnum`はpygmentsと異なり`<table>`を使っています（pygments自体はinlineにもtableにもできるんだけど、Re:VIEWではinlineにしている。Rougeはinlineはそもそも対応してない模様）。

**Comment by kmuto** [comment]
これはclose?

**Comment by kmuto** [comment]
gemspecでもrouge優先になっているので、closeします。
（暗黙有効にするのはいろいろ副作用が大きいので、明示指定には変わりなし）
