### ISSUE TITLE
出力フォーマットにあわせて奥付を変更する際のベストプラクティスを知りたい

### ISSUE THREAD

**Issue by mhidaka** [kmuto/review#489]
要求：奥付の形態をEPUBおよびPDF（同人誌など印刷用）で変更したい

ソリューション：それぞれ別のConfig.ymlを用意してそちらで生成する

PDFの場合はconfig.ymlを次のように設定したうえで、layout/layout.tex.erb を書き換えるとちょうど良かったです。
```
 colophon: true
 colophon_order: ["edt", "prt", ...]
```

EPUBの場合上記のcolophon_order が効かなかったため、
```
 colophon: col.html
```
と指定して内容をほしい記述で書き換えました。
たぶん、印刷所が変わるケースなどはこのような単純な手法でなんとかなりそうだと思います。

ただ、この解決案では、
EPUBおよびPDFで共通の項目も多いため、根本解決には
サークル内で次のようなビルドシステム（スクリプト）を用意するのが適切かな、と思いました。

このような手法がベストプラクティスかどうか、迷ったので
良い方法があればおしえてください。

現在考えてるシステム：ひとつのconfig.ymlを用意してビルドターゲット（EPUBまたはPDFまたは両方）にあわせてビルド時に環境をコピー＆自動変換→ビルドする→ビルドが成功したら成果物だけ残して、作業中のファイルを消す。これをビルド対象分だけ繰り返す。

（もっとも colphon_orderがEPUBでも効く、layout/layout.tex.erbのような奥付が変更できるテンプレートが利用できる、という状況になれば大抵のことには対応できそうだな、と思うのですが…。

リフロー型のフォーマットへ原稿を流し込む際に、画像のScaleを無視したいなど見た目にかかわる変更は行いたくなってしまうので、ビルドシステムが一部変更を自動的に適用するのが安全かな？と副次的な理由もあり、考えてる次第です。

**Comment by mhidaka** [comment]
現状こうやるんだな、というのが分かったのでまとめます。

### ワンソースマルチユースに忠実にするためには
・PDF/EPUB用の大扉、奥付などレイアウト構成を切り分ける
・それぞれ個別のconfig.xml(pdf.xml or epub.xml 名前は便宜上のもの)を用意する

が良さそうでした

#### PDFがターゲットの場合
config.xml の　`colphon_order` および `colphon` を利用する。
レイアウトは `layout/layout.tex.erb` でカスタマイズ可能（大扉および奥付はここで調整）

#### EPUBがターゲットの場合
config.xml の `colphon` を利用する。指定時の仕様は `true `であれば標準テンプレート（変更可能か不明）
`filename`を指定すればその奥付を利用（変数利用可能かは試してない。試そう）
`titlepage` を利用することで大扉も変更可能。`colphon_order`同等の挙動は今のところ必要ないので入ってないよ（colphon_orderが導入された経緯は https://github.com/kmuto/review/pull/330 に）

**Comment by suzukin** [comment]
某弊社もいろいろと試行錯誤（別のアプリ作ったり）してるので第3回？DeveloperMeetingが待たれるところです。
