### ISSUE TITLE
HTMLBuilder: new parameter in config.yml: externallink

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#501]
config.ymlで`externallink: false`と書くと、`@<href>{}`でハイパーリンクを作ることを無効にできるようにする。

cf. #429

**Comment by kmuto** [comment]
externallinkブランチで実装してみました。``@<href>{url, label}```の場合は「LABEL(URL)」にしています（実際は日本語では全角カッコにするためにi18n.ymlにて定義）。 

本件が必要になるのはepubmakerくらいと思われるので、epubmaker:の下のexternallinkとしたのですが、シチュエーションによってちょっと問題があります。

* epubmaker:を一切YAMLに定義していないならハイパーリンクは作られます。
* review-epubmaker経由であればデフォルトでハイパーリンクは作られます（producerで設定）。
* epubmaker:があり、かつreview-compileでHTMLにする場合はepubmaker:externallink:の初期値がnullになってしまうので、 externallink:trueと明示指定しないといけません(!)。

review-webmakerを作るときにこの挙動だと厄介になりそうです。ただ、externallinkがTeXにも効くのかと思われるのは嫌な気もします。

この実装でいくなら、review-compileの初期値として、epubmaker:externallink: true も持たせる、ですかねぇ。

**Comment by takahashim** [comment]
この辺りはReVIEW::Configureクラスの方でよろしくやってほしいわけですが、configにmakerを指定した際のフォールバックの仕様をちゃんと決めるべきですかね…。

**Comment by kmuto** [comment]
Configureのほうに初期値入れました。

**Comment by kmuto** [comment]
これも #515 と絡んでます？

**Comment by takahashim** [comment]
はい、「WebではリンクにしたいけどEPUBではリンクNGにしたい」と「同じ結果になるようWebでもEPUBでもリンクNGにしたい」との選択肢は両方欲しいです。

**Comment by kmuto** [comment]
マージされましたね。
