### ISSUE TITLE
support ebpaj:guide-version

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#502]
OPFに`<meta property="ebpaj:guide-version">1.1.2</meta>`といったmeta要素を追加できるようにする。
その際、package要素に`prefix="ebpaj: http://www.ebpaj.jp/"`といった属性が追加されるようにする。

cf. #429

**Comment by kmuto** [comment]
#513 のパッチ、いいと思います

**Comment by kmuto** [comment]
opf_prefixにしました。
opf_prefix, opf_metaは epubmaker/ の下かな…と思ったのですが、これは #515 と絡みそうですね。
