### ISSUE TITLE
Re:VIEW EPUBtoSomethingEPUB なコマンドを用意する

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#504]
#502 にも絡むけれども、コアのepubmakerはできるだけ基本なものでキープしておき、各ガイドラインに従った変換コマンドを用意する？

* コマンド名ルールはどうするか。
* KADOKAWAと電書協ガイドライン、のように類似の処理をすることが多そうだと、1つの大きなepub converterプログラムにしてフラグ指定で切り替えるほうがよい？
* ZIPを開いて圧縮し直して、というのは若干無駄な気はする…。

**Comment by takahashim** [comment]
https://github.com/KitaitiMakoto/epub-maker#in-place-editing とかが使えると便利そうです

**Comment by takahashim** [comment]
* IDPFが策定した仕様についてはRe:VIEW側で対応する
* デファクトスタンダードのものはRe:VIEW側で対応することもある
* 特定書店のみの仕様だったりガイドラインだったりするものは積極的には対応しない

くらいの気持ちです。

**Comment by kmuto** [comment]
うーん、unzipしてzipという意味ではあまり変わらないような気はします。

気持ちについては同意です。ただebpajガイドラインとiBooksまわりくらいは現実になんとかしないといけないので、コマンドはどうしましょうかね…。

**Comment by kmuto** [comment]
#513 PRを取り込んで、あとは各場面でどうするかというドキュメンテーションがあればひとまず本件は済みそう。

**Comment by kmuto** [comment]
ひとまず電書協とiBooksはpackageとmetaだけで済んだということでcloseします。
まじめにディレクトリ構成やCSSなどやるとしたらそのときに考える。
