### ISSUE TITLE
冒頭が章見出し以外から始まるときの目次の対応方針

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#506]
#436 の内容と関連。

* 段落や節の場合、EPUBの目次にのらない。
* たとえば段落しかない章?ファイルに対して目次を作る場合、目次項目はどう指定したらよいか。catalog.ymlに入れるとしたら、その記法はどうするか。
* LaTeXとEPUBの挙動の違いもあり。

**Comment by takahashim** [comment]
この件は #498 の目次の作り方に影響するのでした（その章ページへのリンクがないと飛べないので死ぬので、何でもいいからリンク用の文字列が欲しい）
ある意味、LaTeXはあんまり関係ないというか、catalog.ymlで指定されていても無視する方針でもよさそうです。

**Comment by kmuto** [comment]
この見出しナシの処理の件はなんとかしたいけど、どう実装したものか…

原稿側に「目次にはのるけど直接のファイルには出ない」見出しを記述するようにすればいいでしょうか。

```
=[toc] 献辞
```

**Comment by kdmsnr** [comment]
目次にのらない、ではなく？

**Comment by takahashim** [comment]
@kdmsnr 本文には表示されないんだけど、EPUBの目次（ナビゲーション）ファイルには載って、そこからジャンプできる、というものです。

**Comment by takahashim** [comment]
```
=[TOCONLY] 献辞
```

くらいがいいですかねえ。長いけど、あんまり推奨するものでもないので。

**Comment by suzukin** [comment]
これ、会議で鈴木も発言してた気がするので乗っかります。だいぶ複雑になってきましたが、ここまでくると「目次なし、ページ表示あり」「目次なし、ページ表示なし」のパターンもあり得るんですかね。。（弊社の場合、奥付にいろいろ文字を入れないといけないのでcolophonでは実現できないのでした）

```
= はじめに
目次あり、ページ表示あり
=[toconly] 献辞
目次あり、ページ表示なし
=[nonum] あれこれ
目次あり、ページ表示あり（章番号なし）
=[notoc] 著者紹介
目次なし、ページ表示あり
=[none] 奥付
目次なし、ページ表示なし
```

**Comment by takahashim** [comment]
@suzukin 「ページ表示なし」ってEPUBで何かできるんでしたっけ？

**Comment by suzukin** [comment]
@takahashim ごめんなさいハイコンテクスト過ぎてついていけません！ EPUBのページで見出しを表示しない場合に、目次からどう飛ばすのかということでしょうか？

「ページ表示なし」の実装はre:viewデフォルトのcolophon.xhtmlをイメージしていました。

**Comment by kmuto** [comment]
予想ですが、ページ表示なしというよりは、Re:VIEW生成じゃないものにあとでサシカエるかんじですかね。

サシカエ作業自体はフックでやるとしても、目次掲載の情報は仮ファイルのほうには入れておく、と。

**Comment by kmuto** [comment]
とりあえずnotocとtoconlyがあればいいかな。これらの要素が採番をすることはまずないと思うからnonumとの重複ができないのは気にしなくてもいいだろうか。

**Comment by kdmsnr** [comment]
noXXX で統一のほうがキモくないです！

**Comment by kmuto** [comment]
toconlyのニュアンスをnoで表現するには…

**Comment by kdmsnr** [comment]
nodisp ... 苦しいですかね

**Comment by kdmsnr** [comment]
``=[nonum][notoc] ABC`` みたいにします？

**Comment by kdmsnr** [comment]
* 目次なし notoc
* 番号なし nonum
* 表示なし nodisp

**Comment by kdmsnr** [comment]
全キャンセルの ``[none]`` もあってもよいです

**Comment by takahashim** [comment]
@suzukin あ、「ページ表示なし」は「見出しが本文に表示されない」のことだったんですね、であれば問題ないです！

**Comment by kmuto** [comment]
見出しまわりはあまり複雑にしたくないんだよなぁ。そのあとのビルダの処理系を考えるとなるべくシンプルにしたい、今のheadlineメソッドの数が変わるのは避けたい。

* ``notoc && !nonum`` や ``nodisp && !nonum``  な状況はありえるんだろうか。
* []無限upはだいぶいやなので、せめて``[A,B]``と``か[A B]``とかの記法?

**Comment by kdmsnr** [comment]
いま見たら正規表現だったので、``[A,B]`` で賛成ですw

**Comment by kdmsnr** [comment]
> notoc && !nonum や nodisp && !nonum な状況はありえるんだろうか。

実際にはなさそうですけど、事前に用途は確定できないので、独立したパラメータを用意して、あとは勝手に使ってくださいというスタンスでよいかなあと。

**Comment by takahashim** [comment]
`notoc`、`nodisp`のときは自動的に`nonum`にしないと付番が破綻しませんか？

**Comment by takahashim** [comment]
あー、でも問題はそこじゃなくて、`nonum`自体が節・小節や図表番号の付番で問題があるんでしたっけ…。

**Comment by kmuto** [comment]
採番ありかつnodispはTeXのときにたぶんaddcounterする実装が面倒になりそう（章だけに限定する?)。

notocについても、ほかのビルダはともかく、TeXの場合、採番ありかつ目次なし というのはちと厄介な気がします（一度ビルドしてできたtocをいじることになる）。

nodispで採番なし なら ``\addcontentsline{toc}{lchapterなど}{目次用見出し}``

そもそもnonum＝内部的にはTeXのchapter*になって目次から落ちる、というのはTeXのわかりにくい挙動かも。nonumだけしかないならaddcontentslineを入れるようにしたほうがいいのかな。

**Comment by kmuto** [comment]
#301 これを直さないとか…
latexはコンパイラがやってくれるけど、HTMLなどは自力で採番調整をしないといけない。下手すると副作用が大きそうだが…。

**Comment by kmuto** [comment]
#555 で、epubmakerおよびpdfmakerでの

* nonum: 採番なし・目次に入る・本文に入る
* nodisp: 採番なし・目次に入る・本文に入らない

までを作ってみました。epubmakerの場合の採番なしによる採番のずれは、番号を戻すことで解消させています。ただ、一度簡易パースするなど、かなり無茶をしている感じはあります。

* nodispの場合に、柱が更新できません。あまりがんばれない気がするので、必要なら\markbothをrawで入れてもらったほうが安全そう。
* 「採番ありで目次に入れない」がTeXでやはり厄介です。見出しのTeXコマンドを自作するか、tocファイルをいじらないとダメなので、範疇を超えそう。
* 複合指定はcompiler.rbのロジック的に厳しそうです。
* 「採番なしで目次に入れない・本文に入る」「採番なしで目次に入れない・本文に入らない」見出しは、複合指定がだめだと別途何か名前が必要。名前地獄。

**Comment by kmuto** [comment]
* notoc 採番なしで目次に入れない・本文に入る

を#555 に追加してみました。そろそろ怖くなってきた。

**Comment by kmuto** [comment]
#555 をマージしました。
