### ISSUE TITLE
ReVIEW::Book::*Index classes should be fixed

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#514]
現状、ReVIEWでの参照解決等にChapterIndexとかImageIndexとかを多用しています。
このインデックス生成には本体のparserとは別の簡易parserが使われています。このせいもあって、PEG版では正常に動きません。

とりあえず2-pass（まず前処理として全文書をparseしてインデックス生成→その後の本番でもう一度parseしながら変換しつつインデックスを使って参照を解決、という流れ）で解決する方向で考え直す。

**Comment by takahashim** [comment]
2-passじゃなくて、構文解析木(Nodeの木)を全ての*.reについて作る→各種インデックス生成→木から各フォーマットへの変換をする際にインデックスを参照、という流れの1-passでいけるかも

**Comment by kmuto** [comment]
これは解決済みです？

**Comment by takahashim** [comment]
こちらですが、木は作らずにIndexBuilderを使って2-passで対応する、という方針で解決したのでした。

**Comment by takahashim** [comment]
というわけで閉じておきます
