### ISSUE TITLE
epubmaker: params["foo"] should be same result as params["epubmaker"]["foo"]

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#515]
YAMLで `@config["epubmaker"]["foo"]` で指定した値をepubmakerの`@producer.params["foo"]`で参照できるようにしたいです。

### 期待される挙動・優先度

- a) `@config["foo"]`が設定されていればそれを使い、設定されてなければ`@config[maker]["foo"]`を使う
- b) `@config[maker]["foo"]`が設定されていればそれを使い、設定されてなければ`@config["foo"]`を使う

挙動としてはa)の方が素直だけど、b)で上書きできるのは便利そうです。
ちなみにepubmakerじゃなくても同様。

**Comment by kmuto** [comment]
本当はparamsじゃなくてconfigにしてうまく統一できればよかった とこっそり思っていますが、
用途としてはどっちのほうがありえそうでしょう（いまいちケースがわからず）。

**Comment by takahashim** [comment]
お、そうなんですね。ではReVIEW::Configureと統一する方向で考えてみます。
用途として分かりやすいところでは、EPUBでは拡張子を`*.xhtml`にしたいけどWEBでは`*.html`にしたい、とかですね…。

**Comment by kmuto** [comment]
#540 マージを受けてほかに手を入れるところはあるかな。

**Comment by takahashim** [comment]
たぶんこれで大丈夫そうです。閉じますね。
