### ISSUE TITLE
doc/sample.ymlとtest/sample-book/src/config.ymlの同期方法

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#516]
review initで作ったファイルのconfig書式が若干古くて不思議に思ったのですが、test/から持ってきているんですね。2つを保守するのはしんどめなので、何かうまく解決したいです。

configもだんだん長大になって、必須なもの|もしかしたらいじるもの|どうでもいいもの およびepubmakerのようにブロックになっていて書き方がわかりづらいもの、など複雑化しているのでちょっと悩ましいところです（そこでinheritか…？）。

**Comment by takahashim** [comment]
review-initで生成するconfig.ymlをdoc/samle.ymlから持ってくるのがよいかもですね…。
それはそれとしてsample-bookの内容はもうちょっと増やしても良いような気がしました。

**Comment by kmuto** [comment]
#580 ので解決かな
