### ISSUE TITLE
部番号にローマ数字を使えるようにしたい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#519]
わりとよくあるので（今は必死に後加工）。
数を設定する汎用的な仕組みが必要かも。

**Comment by kdmsnr** [comment]
i18nに入れるですかねえ

**Comment by kmuto** [comment]
そうか、いちお今でもROMANはありますね。少し考えてみます。

**Comment by kdmsnr** [comment]
てか、もう入れてますね

**Comment by kmuto** [comment]
はい、ただ全角文字のほうでないとちょっと不便だったりするのと、あとこの先漢字の必要性がありそうなのでそのあたりを追加します。

**Comment by kmuto** [comment]
* 全角ABC（小文字はあまり使うことはないので用意しない）
* 全角1文字ローマ数字（これも小文字はあまり使うことはないので用意しない）
* 漢数字

を追加していますが、%pXのXは何かスタンダードなのはありますかね…。漢数字はJでいいと思うのですが。

**Comment by kdmsnr** [comment]
なるほど全角！

**Comment by kmuto** [comment]
2文字許容にして、%pAW、%pRW、%pJとしたほうがいいかもと思い始めました。
ちなみにi18nコードからすると、後ろに\w相当の文字がformatで入ってるとエラーになるのですね。
「%pACH」とか（そんなものは普通登場しない説）。

**Comment by kdmsnr** [comment]
%pRJ、%pAJは入れないとダメそうですねえ

**Comment by kdmsnr** [comment]
あ、小文字もか。Jがついたりらつかなかったり。

**Comment by kmuto** [comment]
#520 で作ってみました、どうでしょう。

**Comment by kdmsnr** [comment]
あ、かぶりましたw  #521
こちらは削除します。

**Comment by kdmsnr** [comment]
よさそうです

**Comment by kmuto** [comment]
マージしました
