### ISSUE TITLE
//imageで[scale]を指定した時に基準となるサイズがPDFとEPUBで異なる

### ISSUE THREAD

**Issue by orangain** [kmuto/review#522]
Re:VIEWのバージョン：masterの最新 (9e1c97a0e6406e962aa40831c18a4715d893c0ca)

例えば

```
//image[Yosemite][画像サンプル][scale=0.5]
```

と書くと、添付した画像のようにPDFでは**画像サイズ**に対して0.5倍になりますが、EPUBでは**本文領域の横幅**に対して0.5倍になります（#372 を参考に`.width-050per { width: 50%; }`というCSSを定義した場合）。

個人的にはPDFでも**本文領域の横幅**に対する倍率を指定できたほうが嬉しいので、[LATEXBuilderでの出力](https://github.com/kmuto/review/blob/9e1c97a0e6406e962aa40831c18a4715d893c0ca/lib/review/latexbuilder.rb#L362)が`\includegraphics[scale=0.5]`となる代わりに、`\includegraphics[width=0.5\maxwidth]`となると良いと思います（手元ではそのようにして回避しています）。

### PDFの場合

元画像が大きいので、画像のサイズを0.5倍にしても紙面からはみ出してしまっています。

<img width="873" alt="PDFの場合
" src="https://cloud.githubusercontent.com/assets/532251/14307770/6fcaedec-fc0c-11e5-8b1a-36c35551e2f9.png">

### EPUBの場合

意図したとおり本文領域の横幅に対して50%になっています。

![EPUBの場合](https://cloud.githubusercontent.com/assets/532251/14307769/6fcac68c-fc0c-11e5-8e06-9beddd1c6006.png)

**Comment by kmuto** [comment]
趣旨としては確かにそのほうがよさそうです。

TeXBuilderのscaleの挙動を変えると副作用がかなり大きなことになりそうなのが心配。
後方互換用の何かを用意する？

**Comment by takahashim** [comment]
なるほど、これでやってみますか？
後方互換用にはconfig.ymlのフラグで切り替え、とかでしょうか。

**Comment by kmuto** [comment]
そうですね、リリース時には注意勧告が必要そうですが。

pdfmaker: の下に作る？

**Comment by takahashim** [comment]
#543 で対応してみました。scale使いたいという場合もあるかと思うので、config.ymlの`image_scale2width`で変換するかしないかを指定してます。
デフォルトをtrueにした方がよいでしょうか。

**Comment by kmuto** [comment]
どっちが感覚的なんだろう、TeX版を多用しているであろう達人さんやてくぶさんの判断次第?

**Comment by takahashim** [comment]
わかりやすさでいうと揃えたほうが良いかと思うので、デフォルトtrueにしてみましょうか。

**Comment by kmuto** [comment]
マージされたので閉じます。リリースノートでは注意勧告したほうがよさそうです。
（doc/pdfmakerにも書いておこう）
