### ISSUE TITLE
デフォルトをuplatexに移行したい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#536]
影響範囲が大きいが、今後のためにはEUCしか利用できないplatexからUTF-8サポートのuplatexにデフォルトを移行し、今のMETACHARSで必死なのを減らしたい。
TeXLiveで入れているなら、platexがあるところにはuplatexも普通あるはず。

**Comment by takahashim** [comment]
@kmuto @kdmsnr もろもろデフォルトを変更して、PEGなしでRe:VIEW 2.0にした方がよいでしょうか…？

**Comment by kmuto** [comment]
はい、今回のバージョンはかなり手を入れてるので、2.0上げのほうがいいかなと考えてます。

**Comment by kmuto** [comment]
* jsbookの場合、texdocumentclassのオプションに"uplatex"を追加
* texcommandを”uplatex”
* layout.tex.erbではBookmarkの文字化け対策を一式消去、hyperrefのオプションをdvipdfmからdvipdfmxに、hyperrefのusepackage行のあとに``\usepackage[dvipdfmx]{pxjahyper}``を追加

でいちおうビルドは通る模様。ただ、ページ数が変わったような…
あまり複雑なものを通してみていないので、ほかに壊れるものもあるかもしれません。

**Comment by takahashim** [comment]
@kmuto とりあえずその辺を修正したものをpull requestしていただければ。

**Comment by kmuto** [comment]
#541 PRしてみました。

紙面デザインの変化はともかくとして、METACHARSやlayoutは「もしplatexだったら」というifロジックを残すべきだろうか。ただ、texcommandにたとえばディレクトリパスが入ってるとか拡張子exeが付いてるとかだと判別しづらそう。

**Comment by takahashim** [comment]
@kmuto 残しておいた方がいいような気がしますね…。

```ruby
if File.basename(@config["texcommand"],".*") == "platex"
  ## platex用のコード
end
```

みたいな感じでどうでしょうか。

**Comment by kmuto** [comment]
了解です、あとで実装してみます。

@munepixyz さんが素敵なクラスファイル（横も縦も）をコントリビュートしてくださるというお話ですが、間に合うかな…。

**Comment by kmuto** [comment]
latexutils.rbのMETACHARSのロジックをいじらないといけないんですが、この場所だと@book.config["texcommand"]は取れないですよね。

latexutils.rbのイニシャライザ相当を作らないといけないでしょうか。

**Comment by takahashim** [comment]
うーん、これは悩ましいですね…。

**Comment by kmuto** [comment]
#541 に追加してみましたが、あまりイケてない感じがあります…。テストもしづらい
