### ISSUE TITLE
release Re:VIEW 2.0

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#537]
The next release should be major update, ver. 2.0.

## Breaking Changes
* [ ] PDFMaker: default latex is uplatex
* [ ] config.yml: update default configuration
* [ ] layout.*.erb: update default templates
* [ ] HTMLBuilder: default version is HTML5
* [ ] EPUBMaker: default version is EPUB3

## New Features
* [ ] config.yml: allow `inherit:` attribute; support multiple configuration files
* [ ] add `review_version` attribute in config.yml

releted issues: #536, #534,  #532, #529

**Comment by kmuto** [comment]
#529 のとおり、EPUBのデフォルトを3、HTMLを5にしたいと思います

**Comment by takahashim** [comment]
足しておきました！

**Comment by kmuto** [comment]
#522 （TeX上でのimage scale）もこの機会に対応してしまったほうがいいかな。

imgtableもできるだけ入れたい。

#501 (externallink)も入れたいけれども、それには #515 (maker個有値) の実装が前に必要?

**Comment by kdmsnr** [comment]
（2.xになるなら後方互換のために入れているコードをぜんぶ削除したり……）

**Comment by takahashim** [comment]
@kdmsnr 気になるやつがあればissue作っておいていただければ…！

**Comment by kmuto** [comment]
#506 nonum,nodisp,notoc
#522 latexでのscale幅
#551 見出しid固有化

は含めたい。

**Comment by takahashim** [comment]
あとLATEXBuilderで、`textbf`とか`ruby`とかも、prefixとして`review`をつけて`reviewxxx`みたいにした方が良いかもです。

**Comment by kdmsnr** [comment]
review_versionを入れずに、bundlerで管理してほしい気がしました

**Comment by takahashim** [comment]
review_versionは、bundle updateをして更新されたRe:VIEWを実行したときに、どこが壊れそうかを警告してくれるとよいなあ、というところです。

**Comment by kmuto** [comment]
29はたぶんオンラインになれないので、当日リリース作業はよろしくお願いします…

**Comment by takahashim** [comment]
@kmuto @kdmsnr とりあえず今日くらいにいったん2.0.0 RC1をリリースしてみましょうか？
（チケットは用意してあります #584 ）

**Comment by kmuto** [comment]
私自身はgemは使ってないので、RCはあってもなくても…というかんじではあります。

**Comment by kdmsnr** [comment]
リリースノートかかないとですね。。。

**Comment by takahashim** [comment]
書かないとですね…

**Comment by kdmsnr** [comment]
せっせとマイルストーンは設定してみました
https://github.com/kmuto/review/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0

**Comment by takahashim** [comment]
主な変更点の列挙です（順番直して整理する必要あり） https://gist.github.com/takahashim/c3812b82d2a77a9e24cd3ea8f33e697b

**Comment by kdmsnr** [comment]
カテゴリ分けもしんどそうですね。
New Features, Bug Fixes, Breaking Changes くらいにざっくりとかなら。。。

**Comment by takahashim** [comment]
まあ何とか少し直してみます

**Comment by kdmsnr** [comment]
https://github.com/kmuto/review/wiki/release-note-2.0.0

少しずつ整理

**Comment by kdmsnr** [comment]
https://github.com/kmuto/review/wiki/release-note-2.0.0 ひとまず完成

**Comment by kdmsnr** [comment]
日本語化してます。。。

**Comment by takahashim** [comment]
@kdmsnr 変更点について、wikiを編集するのがよいですか？

**Comment by kdmsnr** [comment]
日英そろったら、コミットしますので、そちらを修正してもらったほうがよさそうです。

**Comment by takahashim** [comment]
了解です

**Comment by kdmsnr** [comment]
NEWS* をコミットしました

**Comment by takahashim** [comment]
#616 で修正してみました

**Comment by kdmsnr** [comment]
リリース準備はだいたい終わりですかねえ

**Comment by kmuto** [comment]
ありがとうございました！

**Comment by takahashim** [comment]
ちょっと修正していいですか？

**Comment by kdmsnr** [comment]
私のほうは他にやることないので、そのままリリースしてもらえばと！（あとはChangeLogの変更と rake release だけです）

**Comment by takahashim** [comment]
了解です、なんかepubcheckでエラーがでることがあるぽいので

**Comment by takahashim** [comment]
あ、ChangeLogの方は変更してもらっても大丈夫です

**Comment by takahashim** [comment]
#618 が通ればリリースできるはず…

**Comment by takahashim** [comment]
通ったのでリリースします！

**Comment by takahashim** [comment]
リリースしました！ 🎉
