### ISSUE TITLE
後方互換の廃止

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#546]
2.xで廃止してもよさそう

backwardでの検索結果：

* [x] epub: pbl と prt の混在を避ける（どっちが正？）
* [ ] CHAPSファイルなどの廃止（catalog.ymlに統一）
* [ ] 内部的なPOSTDEFとAPPENDIXの役割を明確に（昔はPOSTDEFで両方やってた）
* [x] paramという名前廃止（configに統一）
* [x] appendix_format 廃止（i18nで対応）
* [x] layout.html の廃止（layout.html.erbに統一）→ エラー出す
* [x] 拡張子yamlの廃止（ymlに統一） → エラー出す

他にもあれば……。

**Comment by kmuto** [comment]
pblが出版社、prtは印刷所ですね。
CHAPS系は可能ならコンバートツールを用意してあげたいところ（ごく単純なものでいいと思うけど）。

paramは今でももう使えないようになってる。
「yaml」はどのくらい影響あるだろう。基本リネームでいいのでユーザ側に任せても簡単とは言える。

あと、builderのパラメータ優先設定ができるようになったから、今epubmaker（producer.rb）に入れてるdeprecatedチェックは考えなくてよいコードにできそう？

**Comment by takahashim** [comment]
CHAPSのコンバータはbin/review-catalog-converterでだいぶいけますが、多少の取りこぼし（変換できないパターン）もあったかも。

EPUBMaker::Producerの変換はpubhistory -> historyの変換が手付かずです…（あとは何とかなるはず）。

**Comment by kmuto** [comment]
あそうだ、角さんが作ってくれてましたね。じゃぁコンバータについてアナウンスに入れる程度でよさそう。

pubhistoryはlegacy絡みのは全部捨てちゃってもよいかな…。（どっちにしろ手元の古いのはほかの面でいろいろ動かなくなっちゃってるのでconfig.ymlに手を入れることは確定だし）

**Comment by takahashim** [comment]
CHAPSファイル方面を削除するとテストがぼろぼろになるのがつらい感じですね…

**Comment by kmuto** [comment]
重そうだったら今回リリースではそのままという手も＞CHAPS
それほど負債にはなってないと思いますし。

**Comment by takahashim** [comment]
CHAPS方面は警告くらいならいけそうです

**Comment by kdmsnr** [comment]
#609
