### ISSUE TITLE
TeXのビルドパスが固定なのと再作成時のエラー

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#549]
‘‘‘
   def build_path
      "./#{@config["bookname"]}-pdf"
    end

def generate_pdf(yamlfile)
      remove_old_file
      @path = build_path()
      Dir.mkdir(@path)
‘‘‘
なので、特にdebug: trueのときだと再実行のたびにbookname-pdfフォルダを消さないといけないのが繁雑な感じがします。
ビルドパスをtmpnameにするか、mkdirする前に消去するかをしたほうがよいのではないでしょうか。

ちなみに、review initでできるサンプルがdebug: trueになるのも気持ちが悪いです……。

**Comment by takahashim** [comment]
> ちなみに、review initでできるサンプルがdebug: trueになるのも気持ちが悪いです……。

これは修正した方が良さそうですね…。

というかもともとのdebugの目的としては、debug: falseの時は中間ファイルは全部消えて欲しいけどdebug: trueの時は（デバッグのために）中間ファイルを全部残して欲しい、というところから始まっていて、

* debug: trueの時は`(bookname)-pdf`というディレクトリをローカルに作って、そこでビルド
* debug: falseの時はDir.mktmpdirで作った一時ディレクトリに`(bookname)-pdf`とかのディレクトリを作って、そこでビルドし、終了したら一時ディレクトリごと削除

というのが理想的です。が、debug: falseの時に一時ディレクトリが上手く消せなくて大量に残ることがあるため現状の挙動になった、と記憶しています。この辺を修正するべきですね…。

**Comment by kmuto** [comment]
TeXのコンパイルエラーがあったときに止まっちゃうんですかね。ensure使うか、mktmpdirをブロックで囲んでしまうか…

**Comment by kmuto** [comment]
#556 で実装提案してみました。

**Comment by kmuto** [comment]
merge済み
