### ISSUE TITLE
Re:VIEWのサンプル文書置き場を作る

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#553]
https://github.com/reviewml 以下に置くと良さそう。

1文書1レポジトリと、複数まとめるのと、どっちがいいでしょうか。

**Comment by kmuto** [comment]
量によるかなー。

* 小さいサンプルの集合ならたとえば review-samples リポジトリ下に各書籍を置くのがよさそう。
* ボリュームの大きなものなら各個リポジトリのほうがよい（でもサンプルだよね…）。

GitだとSubversionのように中間からフォルダを取り出せないのがちと不便ですねぇ。

**Comment by takahashim** [comment]
> GitだとSubversionのように中間からフォルダを取り出せないのがちと不便ですねぇ。

そうなんですよねえ…。

動作検証用に人工的な小さいサンプルが必要になりそうなので（さっきも`//imgtable`サンプルを作った）、そういうのを集めたreview-samplesを作ってみましょうか。

**Comment by takahashim** [comment]
https://github.com/reviewml/review-samples
作りました。
