### ISSUE TITLE
doc/format.ja.mdが古いし読みにくいので根本的にリライトする

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#565]
format_idg.ja.mdもいらなそう。

とりあえず今私のほうでこれらWIPしてます。

**Comment by kmuto** [comment]
#567 で作成しています。

* format.ja.md はおおむね読みやすく＋2.0要素も含められたかと思います。
* quickstart.ja.md で初期作成は review init として、ビルドは rake を使うよう推奨すべきなのでしょうか（今の Rakefile だとちょっと使いにくいかもと思いました）。ちなみに今書いているブツでは「review 〜」を使うようにしています。
* 英語のほうについてはまったく手がまわらなそうです…。私が書くと危なっかしすぎるし。

**Comment by kmuto** [comment]
quickstart.ja.mdをreview-initとrakeを絡めて変更しました（review 〜 はWindowsだとexecできなかったですね…）。
縦書きについてもドキュメントを追加しました。

そろそろマージして2.0備えとしたいところです。（あと英語…）

**Comment by kmuto** [comment]
NEWS*、catalog.md、format.md、quickstart.md が手つかずです。

**Comment by kdmsnr** [comment]
#588
