### ISSUE TITLE
LaTeXのテンプレートも templates にする?

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#568]
HTML および EPUB は templates に移動しているので、LaTeX もそのほうがわかりやすいかなと思いました。
i18n.yml も?

**Comment by takahashim** [comment]
LaTeXは移動しましょうか。
i18n.ymlはtemplatesじゃなくてassetsとかdataとかですよね…。どっちがいいのか

**Comment by kmuto** [comment]
まぁi18n.ymlは名前自体は違うもので使わなければいけないので、かえって混乱を招きそうであればママでもかまわないです。
とりあえずLaTeXだけでも。

**Comment by kmuto** [comment]
移動済み
