### ISSUE TITLE
inaobuilderの削除

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#571]
とりあえず入れてみたinaobuilderですが、このinaoフォーマットを利用していたWeb+DBでは改造Markdown→InDesignタグファイル（not XML）のフローに変わっており、inaobuilderの役目はもうないものと考えます。

今後いじっていくならMarkdownビルダのほうですね。ただ拡張されたものについてどう扱うかは検討しないとです。

**Comment by kmuto** [comment]
FYI https://github.com/naoya/md2inao

**Comment by kmuto** [comment]
マージ済み。Markdown版のほうは @vvakame さんに任せよう :)

**Comment by vvakame** [comment]
ﾋﾟｷﾞｨ! inaomdbuilderができたらpull request送ったりします…(震え
