### ISSUE TITLE
lib/epubmaker/producer.rb で循環参照のwarning

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#599]
Re:VIEWとepubmakerが相互に参照しているので、すべて lib/review 以下に入れたほうがよさそう？

**Comment by kmuto** [comment]
手元でepubmaker流用で使ってたのはだいたいreview-epubmakerに移行したから、移動してもいいかなぁ。ただちょっともう時間が足りないのでrelease後ですね（epubmaker.rbあたりが名前衝突して厄介なはず）。

**Comment by takahashim** [comment]
warningは出なくするだけならrequireの向きを直すだけでもいけるかもです

**Comment by kdmsnr** [comment]
lib/epubmaker/producer.rb で ``require 'review'``してるんですが、それだけでreviewのすべてのファイルを読み込みます。で、その配下にある lib/review/epubmaker.rb で逆方向に ``require 'epubmaker'`` してるから循環してるっぽいです。

**Comment by kdmsnr** [comment]
epubcommon.rb の ``require 'epubmaker/producer'`` も不要そう。

**Comment by kdmsnr** [comment]
とりあえず全部とりました。
