### ISSUE TITLE
review on Fedora

### ISSUE THREAD

**Issue by sagitter** [kmuto/review#602]
Hi all,

`review` is now officially packaged for Fedora and for CentOS/RHEL7 systems: https://admin.fedoraproject.org/pkgdb/package/rpms/rubygem-review/

To install:

`dnf install rubygem-review rubygem-review-doc`
or
`yum install rubygem-review rubygem-review-doc`

It will be in testing for some days.

**Comment by kmuto** [comment]
@sagitter , Thanks for your work!
Because Re:VIEW is under developping software, don't hesitate to contact us when you find a problem.

We plan to release Re:VIEW version 2.0 on day after tomorrow.
