### ISSUE TITLE
PNG画像から変換したJPEG画像を本文に埋め込むと、PDF生成時に「Dimension too large」エラーが出る

### ISSUE THREAD

**Issue by kuroda** [kmuto/review#603]
あるRe:VIEWのソースにJPEG画像を本文に埋め込んで `review-pdfmaker` でPDFを生成しようとしたところ、`Dimension too large` というエラーが出て止まってしまいました。

PNG画像を埋め込んでいた時は問題はありませんでした。JPEG画像はImageMagickで変換したものです。

問題を引き起こすソースコードを添付します。

[dimension-too-large.zip](https://github.com/kmuto/review/files/237790/dimension-too-large.zip)

ちなみに、JPEGに変換したい理由はEPUBファイルのサイズを小さくしたい、ということなので、PDF生成時にはPNG画像を使う、という方法で一応の対応はできます。ただ、両方でJPEGが使えると嬉しいです。

**Comment by kmuto** [comment]
エラー再現しましたが、原因はこのJPEGファイルが「壊れている」ことによるものです。
DPIが1、18592.8mm x 11125.2mm という異常な数値になっているため、TeXが計算エラーを起こしてしまいます。元データの問題なので、TeXやRe:VIEW側ではこれについてはどうにも対処できません。

ImageMagickの設定で直せるなら直すか、gimp, PhotoshopでJPEGファイルを作るのでいかがでしょうか。

**Comment by kuroda** [comment]
調査、ありがとうございました。また、Re:VIEWに関係のないことでお手数をおかけいたしました。すみません。

**Comment by kmuto** [comment]
しかしImageMagickで単にconvertしただけでしょうか、不思議ですね。

**Comment by kuroda** [comment]
`/usr/binconvert image1.png image1.jpg` しただけです。不思議です。

問題を引き起こさない画像ファイルもあります。

**Comment by kmuto** [comment]
ImageMagickに類似報告がありました。仕様というかバグというか…
http://www.imagemagick.org/discourse-server/viewtopic.php?t=24888

**Comment by kuroda** [comment]
http://www.imagemagick.org/discourse-server/viewtopic.php?t=24888 に書いてあったように、

```
$ /usr/bin/convert -units PixelsPerInch -density 72x72 image1.png image1.jpg
```

としてみたら、うまく行きました！

情報提供ありがとうございました。
