### ISSUE TITLE
review-pdfmakerやreview-epubmakerがbuilderディレクトリ内の画像を見つけられない

### ISSUE THREAD

**Issue by orangain** [kmuto/review#611]
Re:VIEWのバージョン：master (b0a4b2f987969f50f3e2c86cb4bbb5febaa5657f)

`images/latex/imgsample.jpg` や `images/html/imgsample.jpg` のようにbuilder名のディレクトリ内に格納した画像が使用されません。pdfmakerではPDF内に`--[[path =  (not exist)]]--` と表示され、epubmakerではログに`ch01.re:66: warning: no such image: imgsample`のように出力されます。

 `images/imgsample.jpg` に置いた場合は問題なく使用されます。またRe:VIEW 1.7.2では問題なく画像が使用されます。

試しに[ImageIndexを作成している箇所](https://github.com/kmuto/review/blob/b0a4b2f987969f50f3e2c86cb4bbb5febaa5657f/lib/review/book/compilable.rb#L126)で`p @book.config['builder']`として`@book.config['builder']`の値を表示させると`nil`になっていました。なお、`review-compile --target html`を実行した場合は`"html"`と表示されます。

**Comment by kdmsnr** [comment]
`Builder#image` で `@chapter.image(id).bound?` が `false` になっている。
Converterを導入したからかな？

**Comment by takahashim** [comment]
おそらくそこだと思います。ちょっと修正してみます。

**Comment by kdmsnr** [comment]
output_chaps を元に戻したら正常になりました。

```ruby
    def output_chaps(filename, yamlfile)
      cmd = "#{ReVIEW::MakerHelper.bindir}/review-compile --yaml=#{yamlfile} --target=latex --level=#{@config["secnolevel"]} --toclevel=#{@config["toclevel"]} #{@config["params"]} #{filename}.re > #{@path}/#{filename}.tex"
       if system cmd
         # OK
       else
         warn cmd
       end
    end

**Comment by takahashim** [comment]
@orangain 報告ありがとうございました！　おそらく #614 の修正で直っているかと思います。ご確認ください。

**Comment by orangain** [comment]
@takahashim 修正されているのを確認しました。ありがとうございます。
