### ISSUE TITLE
"How to update 2.0" Guide

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#619]
2.0にアップデートするときの注意事項をまとめた文書を作っておきたいところですが、どういう形にするのがいいでしょうか（とリリースした後で聞いてみる）。

**Comment by takahashim** [comment]
Qiitaに書いてみました http://qiita.com/takahashim/items/268be275cc0e1d2edc08

**Comment by takahashim** [comment]
英語版はまあいいかな…。

**Comment by kenjis** [comment]
公式ドキュメントにあった方がいいと思いますが。

**Comment by takahashim** [comment]
確かに。英語辛そう…というのがあるのですが、まとまったらWikiの方にも追加しておきます。
