### ISSUE TITLE
jlisting.styの入手はひとてま必要？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#635]
Re:VIEWのデフォルトでTeXビルドしたときにjlistingのエラーが出て気付いたのですが、
このjlisting.styはCTANにもなくてsf.netからダウンロードするしかない、のでしょうか。

**Comment by munepi** [comment]
jlistingの入手先は、ひとまず myTeXpertのここ https://osdn.jp/projects/mytexpert/releases/p6275 からですよね。

ちなみに、listing じゃないものとして、minted https://www.ctan.org/pkg/minted があります。

**Comment by kmuto** [comment]
CTANを絶対視するわけじゃないのですが、入手先がバラバラだとちょっとわかりにくいかなぁと思いました（とりあえずpdfmaker.mdあたりにドキュメンテーションはしたほうがよさそう）。

#419 についてはmintedだとよかったりするんでしょうか（issue的にはjs系classの問題、なのかもしれませんが）。

**Comment by takahashim** [comment]
@kmuto jlisting.styは再配布条件がよくわからず…。

**Comment by munepi** [comment]
（Re:VIEW Meeting 2017 Autumnに向けて、）
plistings https://github.com/h-kitagawa/plistings が現実的ですね。

**Comment by yuw** [comment]
私も plistings がよいと思います．
（先日ライセンスを明記してもらうようリクエストしたのは，Re:VIEWでと提案することも考えてだったり）

**Comment by kmuto** [comment]
plistings利用へ。

**Comment by kmuto** [comment]
plistings化済み
