### ISSUE TITLE
review-pdfmakerで「Font family `JY1+mc' unknown」というエラーが出る

### ISSUE THREAD

**Issue by kuroda** [kmuto/review#646]
Reviewを1.7.2から2.0.0に上げたところ、下記のようなエラーが出るようになりました。

```
This is e-upTeX, Version 3.14159265-p3.6-u1.20-141210-2.6 (utf8.uptex) (TeX Live 2015) (preloaded format=uplatex)
 restricted \write18 enabled.
entering extended mode
(./book.tex
pLaTeX2e <2011/05/07u00>+0 (based on LaTeX2e <2016/03/31> patch level 0)
Babel <3.9q> and hyphenation patterns for 81 language(s) loaded.
(/usr/local/texlive/2015/texmf-dist/tex/platex/jsclasses/jsbook.cls
Document Class: jsbook 2014/02/07 okumura

! LaTeX Error: Font family `JY1+mc' unknown.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.337 ...c}{m}{n}{<-> s * [0.961] \jsc@pfx@ jis}{}
```

環境依存の問題かとは思いますが、アドバイスいただけませんでしょうか。

**Comment by munepi** [comment]
@kuroda review-pdfmaker において、Re:VIEW 2.0.0 からデフォルトで`uplatex`を使うようになりました。
それゆえ、jsbook クラスファイルをお使いであれば、`config.yml` の `texdocumentclass: ` を以下のように少なくとも `uplatex` を追加してください。

```
texdocumentclass: ["jsbook", "uplatex"]
```

**Comment by kmuto** [comment]
2.0ではplatexからuplatexにデフォルトコンパイラをスイッチしたのですが、config.ymlでtexdocumentclassを明示指定していてuplatexオプションを付けていない、という症状に見えます。

https://github.com/kmuto/review/blob/master/doc/pdfmaker.ja.md

以下のいずれかの状態で対処できるかと。

- コンパイラをplatexに指定する
- uplatexオプションを付ける

**Comment by kmuto** [comment]
あ、かぶった

**Comment by kmuto** [comment]
``
(texcommand.nil? || Remove_file_ext(File.basename(texcommand)) == 'uplatex') && texdocumentclass.include?('jsbook') && !(texdocumentclass.include?('uplatex'))
``
みたいな擬似コード判定で自動でuplatexオプションを入れることはできるかもしれないけど……バグの温床になりそうなのでconfig.ymlに手を入れていただくほうが結局はよさそうです。

**Comment by kuroda** [comment]
@munepi ありがとうございます。

教えていただいた通り、`config.yml` の記述を次のように直したところうまく行きました。

```
texdocumentclass: ["jsbook", "uplatex"]
```

ただ、元々の `config.yml` には `b5paper` というクラスも指定されていて、次のような記述にした場合は、この Issue の本文に記したようなエラーが出ました。

```
texdocumentclass: ["jsbook", "b5paper", "uplatex"]
```

これを回避する方法はありますでしょうか？

**Comment by kuroda** [comment]
@munepi 

すみません。https://github.com/kmuto/review/blob/master/doc/pdfmaker.ja.md を読まずに、コメントを書いてしまいました。

```
texcommand: platex
texoptions: "-kanji=utf-8"
texdocumentclass: ["jsbook", "b5paper"]
dvicommand: dvipdfmx
dvioptions: "-d 5"
```

という記述を加えたところ、Reviewをアップグレードする前と同じような PDF ファイルが生成されました。

助かりました。

**Comment by munepi** [comment]
@kuroda jsbook.cls で `uplatex` を使う場合、
```
texdocumentclass: ["jsbook", "b5paper, uplatex"]
```
と書いてください。ちなみに、LaTeX をご存知であれば、上記は以下のようになります。
```
\documentclass[b5paper, uplatex]{jsbook} 
```

**Comment by kuroda** [comment]
@munepi うまく行きました。ありがとうございます。

**Comment by kuroda** [comment]
@munepi このIssueをオープンした時は、Macで作業していたのですが、Ubuntu 14.04に作業場所を切り替えたところ、類似のエラーが出ました。

```
! LaTeX Error: Font family `JY2+mc' unknown.
```

`config.yml` の `texcommand` の値を `platex` に戻したらエラーは出ないようになったので、とりあえず回避できているのですが、`uplatex` のままで対応できる方法をご存知ではないでしょうか。

**Comment by munepi** [comment]
@kuroda 
```
! LaTeX Error: Font family `JY2+mc' unknown.
```
このエラーが出るということは、`platex` でタイプセットしているということです。
したがいまして、`texcommand` を `uplatex` に変える（明示もしくはデフォルトに任せる）だけです。
```
texcommand: uplatex
```
すでに https://github.com/kmuto/review/blob/master/doc/pdfmaker.ja.md#uplatex-について にも説明がありますね。

**Comment by kuroda** [comment]
@munepi すみません。私の勘違いでした。

Ubuntuの方ではReviewを2.0にアップグレードしていませんでした。

お手間を取らせました。本当に申し訳ございません。
