### ISSUE TITLE
review-pdfmakerによる//sourceの出力でキャプションが重なる

### ISSUE THREAD

**Issue by kuroda** [kmuto/review#651]
Review 2.0での現象です。

```
//emlist[hello.rb]{
class Hello
  def world
    puts "Hello, world!"
  end
end
//}

//source[hello.rb]{
class Hello
  def world
    puts "Hello, world!"
  end
end
//}
```

上記のようなソースコードを `review-pdfmaker` でPDFに変換したところ
![issue-nnn](https://cloud.githubusercontent.com/assets/5565/15865373/7386fc2a-2d15-11e6-96e8-0b5b7bf62d2e.png)
のようにキャプションがソースコード本体の1行目と重なってしまいました。

UbuntuとMacの環境でこの現象を確認しました。

`config.yml` を含むソースコード一式を添付します。
[issue-NNN.zip](https://github.com/kmuto/review/files/303043/issue-NNN.zip)

**Comment by takahashim** [comment]
報告ありがとうございます。これは`//list`と揃える形にしたほうがよいかもですね…。

**Comment by takahashim** [comment]
これですが、次のバージョン(2.2.0)で`common_code_block`を使った形に修正したいと思います。
生成されるスタイルが変わるので他に影響あるかもしれません…

**Comment by takahashim** [comment]
#681 で修正してみました。

**Comment by takahashim** [comment]
マージしたので閉じておきます。
