### ISSUE TITLE
review-initで作成されたテンプレートでPDFの作成エラー

### ISSUE THREAD

**Issue by kazken3** [kmuto/review#652]
review-initで作成されるconfig.ymlには"rights"が含まれていない（コメントアウト）ため、
デフォルトのtemplates/latex/layout.tex.erbを利用してPDF作成処理を進めた際、
escape_latexで以下のエラーが発生します。

> review-pdfmaker config.yml
compiling test.tex
/home/x/work/review/lib/review/latexutils.rb:72:in `escape_latex': undefined method `gsub' for nil:NilClass (NoMethodError)
	from (erb):343:in `block in get_template'
	from (erb):343:in `map'
	from (erb):343:in `get_template'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/x/work/review/lib/review/template.rb:21:in `result'
	from /home/x/work/review/lib/review/pdfmaker.rb:371:in `get_template'
	from /home/x/work/review/lib/review/pdfmaker.rb:175:in `generate_pdf'
	from /home/x/work/review/lib/review/pdfmaker.rb:130:in `execute'
	from /home/x/work/review/lib/review/pdfmaker.rb:85:in `execute'
	from /home/x/work/review/bin/review-pdfmaker:18:in `<main>'

つまり、layout.tex.erb内にて"rights"の存在チェックを行わず、
escape_latexに文字列を引き渡している状況であるためのエラーと考えます。

**Comment by kazken3** [comment]
すみません、バージョン情報が抜けてました...
review-init 2.0.0
review-pdfmaker 2.0.0
いずれも2.x系のHEADです

**Comment by kazken3** [comment]
#653 にてlayout.tex.erbの修正案を出してみました。

**Comment by takahashim** [comment]
報告ありがとうございます。これは以前からある現象のようです。#653 で対応してみます

**Comment by takahashim** [comment]
#653 をマージしました

**Comment by kazken3** [comment]
HEADで確認できましたのでcloseします。
