### ISSUE TITLE
テンプレートのlayout.tex.erbでpblであるところがprtのまま？

### ISSUE THREAD

**Issue by mhidaka** [kmuto/review#654]
https://github.com/kmuto/review/blob/master/templates/latex/layout.tex.erb#L267
の`published_by`ですが今の最新は`prt`が指定されてます。

Re:VIEW 2.0.0以降は`pbl`のほうが適切でしょうか？

**Comment by takahashim** [comment]
う、すみません。これは修正漏れのようです。
