### ISSUE TITLE
PDF生成時にルビのエラー

### ISSUE THREAD

**Issue by kazken3** [kmuto/review#655]
※update:2.0系問わず、1.x系でも確認されています
2.0系（確認時はHEAD）でPDF生成時にルビが含まれている場合、エラーが発生します。
HTML、ePub上では問題ありません。また1.7系まではPDFでも問題なくルビが作成されています。

```
= てすと
@<ruby>{事故,ジコ}る@<ruby>{奴,ヤツ}は...
@<ruby>{不運,ハードラック}と@<ruby>{踊,ダンス}っちまったんだよ...

```

上記のreファイルでPDF生成を行う場合に以下のエラーとなります。

> ~/x/testing$ rake pdf
> review-pdfmaker config.yml
> compiling testing.tex
> This is e-upTeX, Version 3.14159265-p3.6-u1.20-141210-2.6 (utf8.uptex) (TeX Live 2015/Debian) (preloaded format=uplatex)
>  restricted \write18 enabled.
> entering extended mode
> (./book.tex
> pLaTeX2e <2011/05/07u00>+0 (based on LaTeX2e <2016/02/01> patch level 0)
> Babel <3.9n> and hyphenation patterns for 11 languages loaded.
> (/usr/share/texlive/texmf-dist/tex/platex/jsclasses/jsbook.cls
> Document Class: jsbook 2014/02/07 okumura
> ) (/usr/share/texlive/texmf-dist/tex/platex/japanese-otf-uptex/otf.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
> (/usr/share/texlive/texmf-dist/tex/platex/japanese-otf/ajmacros.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
> (/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def))
> (/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
> (/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/dvipdfmx-def/dvipdfmx.def
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
> (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
> (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
> (/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty)))
> (/usr/share/texlive/texmf-dist/tex/latex/framed/framed.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
> (/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
> (/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
> (/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
> (/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)
> (/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))
> (/usr/share/texlive/texmf-dist/tex/platex/base/ascmac.sty
> (/usr/share/texlive/texmf-dist/tex/platex/base/tascmac.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/base/alltt.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
> For additional information on amsmath, use the `?' option.
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
> (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
> 
> Package hyperref Message: Driver: hdvipdfm.
> 
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hdvipdfm.def
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
> (/usr/share/texlive/texmf-dist/tex/platex/pxjahyper/pxjahyper.sty)
> (./reviewmacro.sty
> (/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty))
> No file book.aux.
> (/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
> _geometry_ driver: auto-detecting
> _geometry_ detected driver: dvips
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
> 
> Package hyperref Warning: Rerun to get /PageLabels entry.
> 
> <./images/cover.jpg> [1](/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd) [2] (./testing.tex
> 第1章
> ! Undefined control sequence.
> l.4 \ruby
>          {事故}{ジコ}る\ruby{奴}{ヤツ}は...
> ? q 
> OK, entering \batchmode/home/x/work/review/lib/review/pdfmaker.rb:41:in `system_or_raise': failed to run command: uplatex  book.tex (RuntimeError)
>   from /home/x/work/review/lib/review/pdfmaker.rb:191:in`block (2 levels) in generate_pdf'
>   from /home/x/work/review/lib/review/pdfmaker.rb:190:in `times'
>   from /home/x/work/review/lib/review/pdfmaker.rb:190:in`block in generate_pdf'
>   from /home/x/work/review/lib/review/pdfmaker.rb:176:in `chdir'
>   from /home/x/work/review/lib/review/pdfmaker.rb:176:in`generate_pdf'
>   from /home/x/work/review/lib/review/pdfmaker.rb:130:in `execute'
>   from /home/x/work/review/lib/review/pdfmaker.rb:85:in`execute'
>   from /home/x/work/review/bin/review-pdfmaker:18:in `<main>'
> rake aborted!
> Command failed with status (1): [review-pdfmaker config.yml...]
> /home/x/testing/Rakefile:60:in`block in <top (required)>'
> Tasks: TOP => pdf => book.pdf
> (See full trace by running task with --trace)

**Comment by takahashim** [comment]
むむ、1.7.2で試したところ、この現象が再現してしまったのですが、「1.7系まではPDFでも問題なくルビが作成されています。」というのは何かマクロを使われていましたか？

**Comment by kazken3** [comment]
@takahashim 

ご指摘の通り、review-initで新規に作成したものでは、1.7系でもアウトでした。

そこで、問題なくルビが打てたものと比較したところ、独自テンプレートでlayout/layout.tex.erbを
利用していて、ルビを有効にする\usepackage{okumacro}が定義されていました。
1.x~2.x系でもrubyが利用できなかったのはこのパッケージが定義できていないことが原因です。

#656 に"\usepackage{okumacro}"を追加した、templates/latex/layout.tex.erbをPRします。

**Comment by kazken3** [comment]
2.0系にとどまらずPDF生成でルビ関連のエラーが確認できましたので、タイトルを修正しました。

**Comment by takahashim** [comment]
ところがルビのマクロについては、okumacroだけではなくnruby.styやpxrubricaとかもあるので、決め打ちにするのは避けたほうがよいような気もしています。

@munepi いきなり振ってみますが、こういう時ってどうするのがいいんでしょうか…？

**Comment by kazken3** [comment]
@takahashim 
ルビのパッケージの選択に関しては、上記のように検討事項はあるかと考えますが、
すぐに決まる状況ではないと思いますので、まずは現状のlayout.tex.rb自身に
uコマンド（デフォルトではコメントアウト）の様にrubyコマンドに関しても
コメントアウトで情報は与えたほうが迷わなくて済むのかなと考えますがいかがでしょうか。

**Comment by munepi** [comment]
@takahashim （おっと、振られていました！）
ひとまず、標準で動作する（グループルビ） `\ruby` コマンドが `layout.tex.rb` に定義されておれば、十分じゃないでしょうか？　`pxrubrica` を読み込んでおいてもよいと思います。

**Comment by kmuto** [comment]
結局、pxrubricaを入れる？

**Comment by kmuto** [comment]
pxrubricaを入れるスタイルファイルにしていく方針。TeXLiveに入ってるし、Dockerにもインストール済み。

**Comment by takahashim** [comment]
#1031 で対応しました。3.0以降はデフォルトで使えるようになるはずです。

![rubi](https://user-images.githubusercontent.com/10401/41551533-14f3e3fe-7367-11e8-8689-54a0f1131382.png)
