### ISSUE TITLE
templates/ 以下のファイルのライセンスを変更したい

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#663]
Re:VIEWのドキュメントを作る際にtemplates/以下のファイルの一部をlayouts/としてコピーして使う場合、その文書のライセンスをLGPL以外で配布できるようにしたいとの要望がありました。

そもそもHTMLテンプレートやLaTeXテンプレートのライセンスとしてLGPLになっているのは解釈が複雑そう（HTMLテンプレートにとってリンクとは？　とかライブラリとは？　といった疑問が湧く）ので、もうちょっと再利用しやすいようにしたいところです。

CC-BYかMITライセンス辺りが無難？

**Comment by kmuto** [comment]
MITのほうが好みです。

ほぼ高橋さんと私によるテンプレートだと思うので、そのままMITにしてよいのではないでしょうか。

**Comment by takahashim** [comment]
ではその方向で変更してみます

**Comment by takahashim** [comment]
変更しました
