### ISSUE TITLE
review-compile --target=htmlで図番号採番結果が全部`%2$d`になる

### ISSUE THREAD

**Issue by muojp** [kmuto/review#667]
バージョン: review-2.0.0

```
$ review-compile -v
review-compile 2.0.0
```

実行コマンド: `review-compile --target=html 1608_bar.re`

対象と望ましい結果、実際の結果はgistに貼りました: https://gist.github.com/muojp/975621ab06a92205f638add27797ce9e

どうも図番号が全て`%2$d`になるようです。

作業を実行しているディレクトリ以下のimages/には、myimg1.pngとmyimg2.pngがあります(なくても結果は同じです)。

**Comment by muojp** [comment]
1.6 → 2.0で、catalog.ymlの存在しない場合のビルド挙動が変わったようでした

**Comment by takahashim** [comment]
うーん、私のローカルでは以下のようになるようです（空のディレクトリに1608_bar.reだけ置いた場合）。

```
$ review-compile -v
review-compile 2.0.0
$ review-compile --target=html 1608_bar.re
configuration file has no review_version property.
1608_bar.re:6: warning: no such image: myimg1
1608_bar.re:11: warning: no such image: myimg2
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:ops="http://www.idpf.org/2007/ops" xml:lang="ja">
<head>
  <meta charset="UTF-8" />
  <link rel="stylesheet" type="text/css" href="stylesheet.css" />
  <meta name="generator" content="Re:VIEW" />
  <title>Bar!</title>
</head>
<body>
<h1><a id="h1"></a><span class="secno">第1章　</span>Bar!</h1>
<p>Here's an image (図1.1).</p>
<div class="image">
<pre class="dummyimage">
</pre>
<p class="caption">
図1.1: My Image
</p>
</div>
<p>And here's another (図1.2).</p>
<div class="image">
<pre class="dummyimage">
</pre>
<p class="caption">
図1.2: My Image 2
</p>
</div>
</body>
</html>
```

**Comment by kmuto** [comment]
何か変なlocale.ymlを食っているとか？ %2$dというgettext置き換え記法を含んだものはRe:VIEWのコードにはどこにもなさそうなのですが。

**Comment by muojp** [comment]
仰るとおりで、すっかり失念していたのですがlocale.ymlにて以下の指定をおこなっています。

```
locale: ja
chapter: ""
chapter_postfix: ""
chapter_quote: "%s"
format_number: "%2$d"
format_number_header: "%2$d"
```

章番号を飛ばして図番号だけを書き出したいケースでこのように指定しています(具体的にはBlogger用のHTML出力)。 `format_number` の扱いが2.0までに変わったのかな、というのが現在の推測です。
しかしここの挙動はtest/test_i18n.rbの `test_custom_format_numbers` でおさえられているように見えるので、もう少々ちゃんと追ってみます。

**Comment by kmuto** [comment]
I18nの挙動として、引数を受けたら必ず使わないとダメで、そうでない場合は暗黙にエラーとしてそのまま文字列を返すみたいです。たとえば

```
"%2$d-%1$d"
```

とすると動く。

**Comment by muojp** [comment]
なんと、ありがとうございます。完全に追っかけ忘れてましたが年始にかけて見てみます!

**Comment by muojp** [comment]
その後に調べたところ、ご指摘のとおり 2a33f9b611fb521851da1f8af422264f278ffe69 610732d13474d36819755b4f29daa02d72631c30 での引数マッチング検証によるものだと確認できました。
「チャプター番号を読み捨ててblog用の出力を得るために一部の引数を読み捨てる」という私のformat_number用法がおそらくRe:VIEW的には特殊なので、review-ext.rbにてI18nの `t` メソッドを上書きして以前の挙動へ戻すことで対処しました。

ありがとうございました。 🙇

**Comment by kdmsnr** [comment]
ああ、frmtの%の数がargsより少ないときはOKですね。修正します。
