### ISSUE TITLE
latexbuilderでinline_brは\\よりも\parのほうがよい?

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#668]
表内で使うときに\だと行区切りになってしまう。
\parにするとほかで何か問題はあるだろうか。

**Comment by kmuto** [comment]
とりあえず、セル内で改行したい場合は\parじゃないと困ると思いますがどうでしょう。

**Comment by munepi** [comment]
@kmuto 
`\newline` か `\par` （ `\endgraf` ）になりそうですが、セル中の改行は別名の `\ccr` （←cell `\cr` の意味として）とかRe:VIEW における表中セル内専用改行 `\reviewXXX` （←tabular 中のみ有効、場合によっては、セルタイプごとにも挙動が変えられる）（XX: br とか cr とか inlinebrとか inlineparとか）とか何か別名にしておけば、 `\reviewXXX` を `\newline` とか `\par` とか改行を含む指定の `\csname` に割当やすいかもしれません。

**Comment by kmuto** [comment]
Re:VIEW側でbrタグが「セル内かどうか」を判断するのが難しそうなんですよね…。正確には、できなくはないけどツリーを持ってない現状版実装だといろいろ汚くなりそう。

**Comment by takahashim** [comment]
`\\`と`\par`の区別はちょっと不明ですが、現状セル内での改行には`shortstack[l]`を生成しています（たまたまこれで上手く行ったというだけで、他に良い方法があれば変更してもよいかもです）

セル内かどうかの判別については、「テーブル内」でよければtable_beginとtable_endで状態フラグを立てる形になりそうです。

**Comment by kmuto** [comment]
shortstack[l]だとポジションをlに指定しちゃうから後々あまりよくないような。
コード見たらダブルバックスラッシュを置換してるんですね。とするとこれを単に``\newline``にすればよいかも？

**Comment by munepi** [comment]
（Re:VIEW Meeting 2017 Autumnに向けて、）

 * `\usepackage[dvipdfmx,table]{colortbl}%requires array package` を読み込む前提で、
 * Re:VIEWに嬉しい、 改行可能なセルタイプを別途定義して、
 * 前述のようなセル内改行コマンド `\ccr` を定義する

のが良いと思います。

**Comment by kmuto** [comment]
列幅指定でのLCRを追加および列幅指定のときには表内での改行をnewlineを使うようにしました。おおむねこれでうまくいくはず。
