### ISSUE TITLE
htmlbuilder#result を細分化したい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#670]
@body（@output.string）をreview-extでちょっといじりたい、というときに触われるのはresultのタイミングだけなのだけど、現状ちょっとメソッドが長くてこれをオーバライドするのがためらわれる。

**Comment by takahashim** [comment]
#690 で素朴に分けてみました（前半部分はlayout_fileを求めるためのものだったのでした）。
`layout_file`はローカル変数からメソッドに変わっていますが、一回しか呼ばれないのでこれでいいかな？　という感じです。

**Comment by kmuto** [comment]
ありがとうございます、だいぶすっきりしますね。
next, prev, tocまわりは分離しないほうがよさそうでしょうか。

**Comment by takahashim** [comment]
ここで使っているインスタンス変数はtemplateに渡す用なので、何を渡すかを陽に指定しておいた方が良さそうです

**Comment by kmuto** [comment]
了解です。これでよいかと

**Comment by takahashim** [comment]
ではマージしておきます

**Comment by takahashim** [comment]
マージしたので閉じておきます
