### ISSUE TITLE
`rake test` error since #662

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#672]
https://github.com/kmuto/review/pull/662 のマージ以降、私のローカルでrake testが途中で止まって正常に終了しません。
@kmuto さんのところでは動いてますか？

**Comment by takahashim** [comment]
PDFMakerCmdTest (test_pdfmaker_cmd.rb) でビルドしたときにimages/latex/imgsample.xbb ができてなくてlatexがエラーになっているようです。

**Comment by kmuto** [comment]
あら、それはすみません。確認します

**Comment by kmuto** [comment]
んー、なんでこれで挙動が変わるのかよくわからない…そもそも前もなんでxbbなしに動いていたんだろう

**Comment by kmuto** [comment]
なるほど、includegraphicsの値が変わっちゃうのか。

**Comment by kmuto** [comment]
フック用に別の変数を用意し、@basedirの値を前の相対パス（たいていは「.」）に戻しました。

**Comment by takahashim** [comment]
お、動くようになりました！　ありがとうございます
