### ISSUE TITLE
listnum と emlistnum で開始行番号を指定できるようにしたい

### ISSUE THREAD

**Issue by anchan828** [kmuto/review#685]
技術書などでサンプルコードを掲載する際に、一部を抜き出して掲載することがあります。

その際に listnum か emlistnum で実際のサンプルファイルの行番号を指定したいです。

↓は FbxImporter.cs ファイルの 9行目から19行目を抜き出したものです。現在はキャプションに行番号を記載しています。

```
//emlistnum[Assets/Editor/FbxImporter.cs line 9-19]{
    // 1.Project内からPrefabのguidを取得
    var guids = AssetDatabase.FindAssets("t:Prefab");
    // ProjectにPrefabがなければ処理を中断
    if (guids.Length == 0) return;

    // 2.FbxReplacementComponentをもつPrefabを取得
    var replacementComponents = guids.Select(guid => AssetDatabase.GUIDToAssetPath(guid))
      .Select(path => AssetDatabase.LoadAssetAtPath<FbxReplacementComponent>(path))
      .Where(component => component != null && PrefabUtility.GetPrefabType(component) == PrefabType.Prefab);

    if (replacementComponents.Count() == 0) return;
//}
```
<img width="397" alt="ss 2016-12-03 21 49 44" src="https://cloud.githubusercontent.com/assets/694454/20859434/7751bf24-b9a2-11e6-8a9e-16cbe73a135b.png">

**Comment by kmuto** [comment]
開始行番号を変えるのはできそうですが、（中略）とか入れたくなりそうなときにどうしようという悩みがあります。
手元の類似のケースでは、プリプロセッサ側にやや複雑めな処理をカスタムで追加していました。

**Comment by takahashim** [comment]
> （中略）とか入れたくなりそうなときにどうしよう

それは現状でもどうにもならないので、開始行番号指定はあってもよいかもしれません（あまり積極的ではないですが）。
問題は実現方法をどうするかですね…

* 引数増やす
* 何かしらのディレクティブ的なものを追加する
* その他

**Comment by kmuto** [comment]
引数はオプション記法ができるまでもう増やしたくないので、直後のものに影響する//tsize的なディレクティブがよいかなと思います。

**Comment by kdmsnr** [comment]
``//listlinenum[9]`` ですかね。もしかすると終了番号もいけるかも ``//listlinenum[9,19]`` 。

**Comment by takahashim** [comment]
#688 で対応してみました。いろいろあって先頭にlistという名前が入ると不幸になりそうだったので、`//firstlinenum[...]`という名前になっています。終了番号は対応が厳しそうだったので入れてません。

HTML/LaTeX/InDesign（含むhighlight）に対応してみたつもりですが、InDesign対応はこれであってます？＞@kmuto

**Comment by kmuto** [comment]
よさそうに見えます。

**Comment by kmuto** [comment]
#688 にて対応済みですね。
