### ISSUE TITLE
review-ext.rbに「会話している様子」をあらわす記法と表現を追加したいがやり方がわからない

### ISSUE THREAD

**Issue by mhidaka** [kmuto/review#687]
次のようなキャラクターの掛け合いがある文章で、特別なマークアップをしたいです。
現在の `review-ext.rb` ではどのように処理するのが適切なのかわかってません。

```
日高ともちこは会議室に移動した。
「もちこさんには次期スマート冷蔵庫用の食材管理アプリ開発チームに参加してもらいます。スマート冷蔵庫のOSにはAndroidを採用していて、アプリは普通のAndroidアプリです」
「はい」
「実は前のバージョンのアプリの開発者が退職してしまって、、、たっくすというものが引き継いだのですが、なにをやっているのかよくわからない、どうして動いているのか謎だ、というのです。前のバージョンは不具合も多く、次のバージョンは作り直そうと思っています」
「はい。（これはなかなか...）」
「次のバージョンではこのようなことが起こらないよう、拡張性・柔軟性のあるものにしたいのです。そこで、もちこさんにはまず次期バージョンの開発方針を決めていただきたいです。前バージョンと現状の仕様についてはたっくすから聞いてください」
「わかりました。まずはたっくすさんと相談します」
「よろしくお願いします」
```

現時点では `//talk{ ... //}` を新規に作り、行の最後に自動的に@<br>{}を挟むようなイメージで色々さわってみたのですがなかなか。実装部のヒントになる部分とかあると助かります…

```
ReVIEW::Compiler.defblock :talk, 0..1
class ReVIEW::LATEXBuilder
  def talk(lines)
      latex_block 'quote', lines
  end
end
```

いまは全体をquoteにおきかえてますが、別装飾をしつつ、行をとりだして改行を入れ込みたい・・

**Comment by kdmsnr** [comment]
最終的な出力イメージがあるとよさそう

**Comment by kmuto** [comment]
「自動的に…」のところでbrがGit Markdownで消えてるけど、「新しいブロック要素を作りたい」「空行段落でなく、listなどと同様に改行は改行として使いたい」ということかな。

角さんの言うとおり、希望の見た目をポンチ絵でもいいので何か例示があればTeXnicianが教えてくれそう。

**Comment by mhidaka** [comment]
やりたいのは、こんなかんじのレイアウトです！
![image](https://cloud.githubusercontent.com/assets/322019/20914236/8b8d509a-bbc1-11e6-8410-8687d3f9702a.png)

**Comment by kmuto** [comment]
「ひだか」「もちこ」はリテラルか何かの補助情報が必要になりそう（常に「ひだか」で始まるとは限らないかもしれないし、3人目が出てくるかもしれない）。
名前部分をセリフの上下センターにするなら、longtableでケイなしにするかんじかなぁ。

**Comment by mhidaka** [comment]
なるほど。 
```
//talk[ひだか]{
本文
//}
```
またはfootnoteのように
```
//talk[ひだか][本文]
```
が良さそう、ということですね。
上下センターは思わずやっただけでして、上揃えで問題無い気がします。本文の折り返しが綺麗なほうがうれしい・・・。ん？？？これ表でやればとりあえずは実現できるのか？

**Comment by kmuto** [comment]
talkを全部囲むとだるそうなので、review-ext.rbで単純に文字探索して、``ひ「…``  ``も「…``のように書いておいたのを置換するかんじかな。ちょっと例を作る。

**Comment by kmuto** [comment]
とりあえずtalk環境の枠組としてはこんなかんじとか？ 細かいところはreview-ext.rbをいじるなり、ちゃんと環境を作るなりすればいけるはず。ページをまたげるようにlongtableをsty/reviewmarco.styのusepackageで呼び出すようにしてる。

[a.zip](https://github.com/kmuto/review/files/633106/a.zip)

**Comment by mhidaka** [comment]
ありがとうございます。ためしてみてフィードバックします・・・！

**Comment by mhidaka** [comment]
![image](https://cloud.githubusercontent.com/assets/322019/20937004/56abc156-bc28-11e6-8020-b6b9d6bd0f32.png)
一旦こんな感じでおちつきました。頂いたファイルをそのまま適用したかんじです。
もうすこしレイアウトやマージンを調整していこうとおもいますー

**Comment by kmuto** [comment]
コモンな要素にはならなそうですし、closeしてもよいでしょうか？

**Comment by mhidaka** [comment]
おっとすいません、とじそこねてました。ありがとうございました
