### ISSUE TITLE
review-ext.rb で画像を表示する処理を行いたい

### ISSUE THREAD

**Issue by anchan828** [kmuto/review#691]
review-ext.rb 内で `image` を使って画像を表示しようとしたところ次のエラーが出力されました。

```
review-pdfmaker: warning: compile error in test.tex (ReVIEW::KeyError)
review-pdfmaker: warning: not found key 'ss01' for ReVIEW::Book::IndepImageIndex
review-pdfmaker: error: compile error, No PDF file output.
```

review-ext.rb
```review.ext.rb
ReVIEW::Compiler.defblock :test, 0..3

class ReVIEW::LATEXBuilder
	def test(lines, id = nil, caption = nil, metric = nil)
		image(lines, id, caption, metric)
	end
end
```

test.re
```test.re
//略

//test[ss01][テスト]{

//}
```

エラーを見る限り、インデックスのリストにIDを登録するのかな？とは想像できたのですが、登録する方法がわからず、 image を使わないやり方で対処していました。

```
puts '\begin{reviewimage}'
puts "\\includegraphics[width=0.8\\maxwidth]{#{@chapter.image_index.image_finder.find_path(id)}}"
if caption != nil
	puts "\\caption{#{caption}}"
	puts "\\label{image:#{@chapter.id}:#{id}}"
end

puts '\end{reviewimage}'
```

ですがこれだと `@<img>{}` が正しい出力を行わない（インデックス登録されてないのでズレる）ので悩んでいます。 
何か対処法などありますでしょうか？

**Comment by takahashim** [comment]
うう、ここはめっちゃバッドノウハウなところなのですが、画像については画像ファイルの探索のしくみと`@<img>{}`での参照のしくみがあって、そこをうまいこと使う必要があります。

そして結論を言うと、`@<img>{}`の画像参照の対象となる新しい画像出力記法を定義するには、記法名を`imagefoo`のように`image`で始まるように命名していただけると良さそうです。

### review-ext.rb

```ruby
ReVIEW::Compiler.defblock :imagetest, 0..3

module ReVIEW
  class LATEXBuilder
    def imagetest(lines, id = nil, caption = nil, metric = nil)
      image(lines, id, caption, metric)
    end
  end
end
```

### test.re

```review
= imagetestのテスト

//imagetest[logo][ロゴ]{
//}

先ほどの@<img>{logo}はテストのロゴ画像です。
```

### 結果

![2016-12-16 20 47 48](https://cloud.githubusercontent.com/assets/10401/21261799/fcc256b8-c3d0-11e6-922c-62ec95f30750.png)

**Comment by anchan828** [comment]
ありがとうございます！
無事エラーなく採番も正しく記述されているのが確認できました。

バッドノウハウであることを頭に置きつつこの方法で対応したいと思います。
ありがとうございました。
