### ISSUE TITLE
HTMLBuilder: remove error/warning messages in HTML

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#706]
cf. #705
HTMLBuilderのみ、`HTMLBuilder#error_messages()`と`HTMLBuilder#warning_messages()`というエラーや警告を生成するHTML本体に突っ込むメソッドがあるが、本来ログに吐くべきことでHTMLで表示されてもうれしいことはほとんどないと思われるので、この機能ごと削除したい。

**Comment by kmuto** [comment]
はい、削除してよいと思います。

**Comment by takahashim** [comment]
よく見たらidgxmlbuilderにもありました（TOPBuilderのは壊れてたので削除しました）。

**Comment by kmuto** [comment]
昔にHTMLBuilderをコピったときの残りかと…。IDGXMLだとエラーになったらそもそも組んじゃだめなわけで、この機能は使ってないです。

**Comment by kmuto** [comment]
これcloseしていいですよね。

**Comment by takahashim** [comment]
はい、問題ないです 🙆
