### ISSUE TITLE
rakeのテストがいろいろ動かない？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#709]
```
% rake --version
rake, version 10.3.2

% rake
/usr/bin/ruby2.1 test/run_test.rb
/usr/lib/ruby/2.1.0/test/unit.rb:55:in `process_args': invalid option: --max-diff-target-string-size=10000 (OptionParser::InvalidOption)
	from /usr/lib/ruby/2.1.0/test/unit.rb:832:in `process_args'
	from /usr/lib/ruby/2.1.0/test/unit.rb:837:in `run'
	from /usr/lib/ruby/2.1.0/test/unit.rb:844:in `run'
	from test/run_test.rb:10:in `<main>'
rake aborted!

(test/run_test.rbのargvを空に)
% rake
[334/335] ZipExporterTest#test_export_rubyzip = 0.00 s                  
  3) Error:
ZipExporterTest#test_export_rubyzip:
NoMethodError: undefined method `assert_true' for #<ZipExporterTest:0x00000003068f08>
    /home/kmuto/review/test/test_zip_exporter.rb:91:in `test_export_rubyzip'
```

**Comment by takahashim** [comment]
あー、ひょっとしてminitestの方が動いてるんでしょうか。Test::Unitの方を使ってるのでした
https://github.com/test-unit/test-unit/
参考: http://www.clear-code.com/blog/2014/11/6.html

**Comment by kmuto** [comment]
Debian stableで、テストのためだけにgemが必要というのは嫌だなぁ…

**Comment by kdmsnr** [comment]
travisの2.1.5では動くんですねえ（手元ではダメだった）

**Comment by kdmsnr** [comment]
bundlerがあれば動くみたいですけど、あれは gem でインストールしないとダメなんですっけ

```ruby
begin
  require 'bundler'
  Bundler::GemHelper.install_tasks
rescue LoadError
  # ignore if bundler does not exist
end
```

**Comment by takahashim** [comment]
どうなんでしょう。gemは2.xで標準になりましたが、bundlerはまだですね（将来取り込まれるかどうかも不明）

**Comment by kmuto** [comment]
（rakeでリモートネットワークからインストールがなされるのは個人的にはとても気持ちが悪いのだけど、今のところ実害はないのでよいか…）

非互換障害となっている、--max-diff-target-string-size=10000とassert_trueは、使わないとどうにもならないのでしょうか。test/unitのバージョンを判断して分けるしかない？

**Comment by takahashim** [comment]
別に使わなくても致命的ではないのですが、minitestの方がバージョンによって非互換がありそうなのでminitestを使わせないようにしたいところなのでした

**Comment by takahashim** [comment]
あー、でもassert_trueはいらないですね。これはとっておきます

**Comment by kmuto** [comment]
あぁ、test/unitはそもそも標準ライブラリから落ちたのか… ではgemでも仕方ないか。
Debian stableだとruby-test-unit 3.0.1が利用できるようなので、これで使えさえすればやむを得ないとしましょうか。

**Comment by takahashim** [comment]
2.2か2.3で、標準添付なbundled gemとして両方が配布されるようにので、ネットワーク越しには取ってこなくても良い形になったはずです（Debianではどういう扱いになるんですかね…

**Comment by kmuto** [comment]
Debian次期リリース版の環境で試したところ、rubyパッケージ（2.3）をインストールしたときに依存関係でruby-test-unit 3.1.7が自動インストールされました。ならば問題ないかな。
とりあえず3.0.1でダメなところがあったら報告します。

これは閉じるか。
