### ISSUE TITLE
makerhelperでのtest_copy_images_to_dir_convertの実行テストエラー

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#712]
ImageMagickのない環境で、test_copy_images_to_dir_convert(MakerHelperTest)のテストがスキップされずに失敗する。

あと、このsystem("convert")の書き方はいろいろよくない気がする。パスにスペースがあると詰みそう。
RMagickをoptionalで入れるようにしてそこで変換する？

（そもそもこの機能はどの程度ユーザーに使われているのだろう？）

**Comment by kmuto** [comment]
エラーには対処済み

**Comment by kmuto** [comment]
convert -versionがSTDERRに出てキモいことがわかったので直す

**Comment by kmuto** [comment]
STDERRじゃなくてSTDOUTだった。

```
system("convert -version > /dev/null")
```

はひどいかな…

**Comment by takahashim** [comment]
#718 だとconvertがない場合、テストがfailしているわけではないのに`sh: convert: command not found`が出力されちゃいますね…

**Comment by takahashim** [comment]
コマンドの存在チェックだけなら、

```ruby
if /mswin|mingw|cygwin/ !~ RUBY_PLATFORM && (`convert -version` rescue nil)
```
とか、`require 'open3'`してから、

```ruby
if /mswin|mingw|cygwin/ !~ RUBY_PLATFORM && (Open3.capture2("convert -version") rescue nil)
```

くらいがよいかもです。

**Comment by kmuto** [comment]
上のやり方にしてみたのですが、Avoid using rescue in its modifier formで怒られちゃいました… #718

**Comment by takahashim** [comment]
まじっすか。それはrubocopの方をなんとかしたい

**Comment by takahashim** [comment]
たぶんこれでいけるかと

**Comment by kmuto** [comment]
ありがとうございます！
