### ISSUE TITLE
latextsize、tsizeのドキュメントが必要？

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#716]
よく使われているわりにdoc/formatに記述がない。

個人的にはlatextsizeもtsizeももっとマシな方法がないか（そもそもフォーマッタ側でもっとインテリジェントにならんのか）という気がしていますが…。あと、PEG化したらオプションで取るほうがいいよなと思っていましたがまだ先になりそうなので、実用性を考えて掲載してしまったほうがよさそうです。

latextsizeはpよりも生のtable設定（cやrや|有無など）を入れられたほうがいいのかなと思いつつ。

tsizeのビルダ選択機能もマージしたいです。

**Comment by kmuto** [comment]
昔のissue #196 で、ビルダ選択はやめていたのだった。でもHTMLでも必要になることありそうなんだよなぁ（実際今拡張した状態のものを使ってる）。

**Comment by takahashim** [comment]
とりあえずtsizeで指定するものは何か（長さか割合か、長さなら単位は何か）が揺れてしまうのがユーザから見てわかりにくいなあと思っているのですが、まあ仕方ないところですかね…。

**Comment by takahashim** [comment]
そういう意味では開き直って//tableoptionみたいな名前にしてbuilder別に指定できるようにするのが良いんでしょうか

**Comment by kmuto** [comment]
tsizeを実質的に利用するのはlatexかidgxmlで、どちらも%で指定することはなく、mm以外の単位を使う可能性はほぼないのではと思います。htmlはstyle属性を使いたくないとしてclass属性にするとcss側の記述負荷が高くなるだけになりそうだし(tableのidに基いてchildで指定したほうがよさそう)、textのほうは幅指定を入れたところでDTPオペレータ側ではほぼ無価値の情報。

tableoptionのほうは文字列が長いので編集者/DTPオペレータの立場として面倒というのもあるのですが、複数の指定を入れたいときの書式とその解析に困りそうな気がします。

**Comment by takahashim** [comment]
む、昔HTMLで%指定に置き換えてたケースもあったのですが…というマイナーな事情（現状では数例だけで、それ以外はHTMLでは無視するようにしてました）はさておき。

LaTeXとInDesginではmm表記で統一、ということでいいんですかね。InDesignの方はわかりませんが、LaTeXの方は若干の機能不足を感じないでもなかった（のでlatextsizeを使ったりしてた）のですが、

* 版面の物理サイズを期待するbuilder(LATEXBuilder, IDGXMLBuilder)についてはmmで解釈する
* 版面の物理サイズを規定しないbuilder(上記以外)であれば無視する

というセマンティクスで統一できそうであれば、tsizeはそういうものとするのでもよいかと思いました。

（TEXTBuilderで表を作ったことはないので、どうするべきかよく分からず）

**Comment by kmuto** [comment]
#720 にてtsizeのドキュメントを入れました。
latextsizeの機能もtsizeで実質的に内包しているのと、latextsizeは現状では別のビルダではエラーになってあとあと困りそうなので、とりあえずlatextsizeについては言及は入れていません。
