### ISSUE TITLE
html,idgxml,markdownのビルダからul_itemメソッドを除去

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#727]
compilerではul_item_beginメソッドからul_itemを単純に呼び出している。
これに対し、html, idgxml, markdownはul_item_beginをオーバライドして表現もそこに入れてしまっているので、ul_itemメソッドは決して呼び出されない不要なものとなっている。

なお、latexはul_itemをオーバライドしているのでこのままとしておく。

cf #726

**Comment by takahashim** [comment]
これ、ちょっと良くわからなかったのですが(compilerではul_itemを呼んでなさそう)、「compilerではul_item_beginメソッドからul_itemを単純に呼び出している。」は「builder(ReVIEW::Builder)では〜」であってますか？

**Comment by kmuto** [comment]
あ そうです。いずれにしても#726のでマージしたのでcloseですね。
