### ISSUE TITLE
rawタグ内で\nを改行変換するようにしているがTeXのタグ(\nobreakとか)を入れたいときに困る

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#730]
- 案1：\n を特別扱いするのをやめる。じゃぁかわりに改行入れたいときにはどうしたらよいか、を考える必要（特にIDGXML, TOPでは必要になる場面あり）。
- 案2：latexビルダだったときには\nを特別扱いしない。latexでrawを使って改行文字をどうしても入れたい場面はなさそう。ただビルダ間で若干挙動が違うのが気持ち悪い？

**Comment by yuw** [comment]
改行抑制をたとえば@<nbsp>{}といった感じのタグで入れることができればよいかもと思いはじめました．

タイポグラフィカルにですが，例えば次のような場面で改行抑制したくなります．
# 実際そういった要求があったりもします

- 省略のピリオドの直後（ex.: p. 123）
- 図版等の参照の“図”の直後（ex.: 図1.1）

図版等は@<img>{...}等がLaTeXのマクロに渡りますので，その定義中に\nobreakを必要なら書けばよいだけですが，省略のピリオド直後といった箇所では直接何かを入れないといけない現状であると認識しています．

**Comment by takahashim** [comment]
（↑上のコメント、`@<img>{...}`のところが見えなくなっていたのを修正しました）

**Comment by takahashim** [comment]
仕様的には`\`をエスケープ文字にする（`\`文字を使うには`\\`と入力する必要がある）インラインを追加するのが筋がよいかも…という気持ちです

**Comment by kmuto** [comment]
TeXでいっぱい入れることがあるので、エスケープだと\\だらけになって編集DTP作業がきついんですよね…パーザ的には現状のは困りそうなのは理解しているんですが。

**Comment by takahashim** [comment]
TeXの場合、

* そもそも`}`がTeXの記法とRe:VIEWインラインの終端（`@<foo>{}`の最後の文字）とで衝突してる
* TeXの`}`を使うために`\}`と`\`でエスケープすることにする（この時点で美しくないのはさておき）と、TeXでも`\`を使う必要があるので衝突する

という辺りがどうにもならないのが厳しいところです

**Comment by kmuto** [comment]
- ``\``をエスケープ文字にするを基本
- （主にLaTeX向けに）ほぼ全部（@rawの場合は``\}``、//rawの場合は``\]``はやむをえないとして）リテラルに見るように切り替えるYAMLパラメータ

だと負債になっちゃいそうですかね…

**Comment by kmuto** [comment]
改行抑制はTeX以外では使えないのでRe:VIEWに命令を追加するメリットが薄いのと、``\n``から始まるTeXコマンドはほかにありそう（カスタムだけど``\nobashi``と使おうとしてダメなことに気付いて``\hiroge``としたものがある）なのでした。

**Comment by takahashim** [comment]
設定でparserを切り替えるのはあんまりおすすめできなさそうです…。
それよりは、使いたい場面は少なくてもセマンティクスが明確な別インライン記法を作ったほうが、使う人にも実装する人にもすっきりするんではないかなーと思っています。

**Comment by kmuto** [comment]
なるほど。新たに作るとするとどういう名前がよいのだろう。短く、rawと混在しないもの。

**Comment by kdmsnr** [comment]
``"\\n$"`` を置換します？

**Comment by yuw** [comment]
> "\\\n$" を置換します？

これは`$`が直後に明記されたとき改行にするって感じですか？

**Comment by yuw** [comment]
新たに作る場合，escape …だとRubyに寄りすぎでしょうか．

**Comment by kdmsnr** [comment]
あ、すみません。行末を意味してました。→ `/\\n$/`

**Comment by kdmsnr** [comment]
おっと、inline_raw もあるのか。。。ダメですね。

**Comment by takahashim** [comment]
> 新たに作るとするとどういう名前がよいのだろう。短く、rawと混在しないもの。

* `@<nraw>{...}`
* `@<rawstr>{...}` 
* `@<str>{...}`
* `@<data>{...}`

とかでしょうか。

**Comment by kdmsnr** [comment]
tagとか？

**Comment by kmuto** [comment]
ちょっと長いけど高橋さんのrawstr、あるいはdataがよさそうに思いました。ブロック、インラインともに同じ名前で。

verbatimというのも候補としていただいたのですが、TeXのそれの挙動になるような誤読をされるのは避けたい。

**Comment by takahashim** [comment]
ブロックについては、

```
//data[有効になるビルダーの指定・省略時は全ビルダー]{
（…ここに書く…）
//}
```

みたいに書けるようにしたいですね…（本当は`//raw`でもこれをできるようにしたい）。

**Comment by takahashim** [comment]
名前ですが、`//embed{` ... `//}`がいい気がしてきました。

**Comment by kmuto** [comment]
あ、いいねそれ。

**Comment by kmuto** [comment]
embedが入ったのでclose
