### ISSUE TITLE
質問：PDFにsubtitleは入れられますか？

### ISSUE THREAD

**Issue by uchan-nos** [kmuto/review#742]
gemで入れたRe:VIEW 2.1.0を使っています。
PDFのタイトルページに、主題と副題を入れたいのですが、できますでしょうか？
こんな感じの副題を入れたいです。

「Effective Modern C++ ―C++11/14プログラムを進化させる42項目―」

config.ymlのドキュメントを見ると「NEW subtitle (str): サブタイトル」とあり、ちょっと期待したのですが、PDFには効果がないようでした。

**Comment by kmuto** [comment]
お返事が遅くなりました。たしかにsubtitleについては今LaTeXレイアウトで無視しちゃっていますね。
とりあえず、Re:VIEWのgemにあるtemplates/latex/layout.tex.erbを制作環境のlayouts/内にコピー後、

```
…
    {\Huge <%= escape_latex(@config.name_of("booktitle")) %> \par}%
    \vskip 1em%
    {\Large <%= escape_latex(@config.name_of("subtitle")) %> \par}%
    \vskip 15em%
    {\huge
…
\vspace*{\fill}

{\noindent\reviewtitlefont\Large <%= escape_latex(@config.name_of("booktitle")) 
%>\\ \large <%= escape_latex(@config.name_of("subtitle")) %>} \\
\rule[8pt]{14cm}{1pt} \\
…
```
というかんじでsubtitleの追加を行い、config.ymlのほうでは
```
subtitle: ―C++11/14プログラムを進化させる42項目―
```
としておけば、目的の結果が得られるかと思います。

**Comment by uchan-nos** [comment]
お返事ありがとうございます。頂いた情報を元にやってみたところ、うまく行きましたのでご報告します。一点、最終ページ（裏表紙というのでしょうか）の書名にもサブタイトルを表示させたかったので、追加修正してみました。

まずは表紙のタイトル部分の修正（layout.tex.erb 260行目付近）：

```
    {\Huge <%= escape_latex(@config.name_of("booktitle")) %> \par}%
    \vskip 1em%
    {\Large <%= escape_latex(@config.name_of("subtitle")) %> \par}%
    \vskip 15em%
```

最終ページの修正（layout.tex.erb 330行目付近）：

```
{\noindent\reviewtitlefont\Large <%= escape_latex(@config.name_of("booktitle")) %>}
\vskip 0.1em%
{\reviewtitlefont <%= escape_latex(@config.name_of("subtitle")) %>} \\
```
