### ISSUE TITLE
layout.tex.erbでsubtitleを利用できるようにする

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#745]
ref #742 

- 大扉、奥付で使用
- 大扉での副題の大きさはLargeでいいだろうか。書名と副題の間は1emでいいだろうか
- 大扉で著者名はそのまま下げて15emのままでいいだろうか、それとも副題分の高さは削るべきだろうか
- 奥付での副題の大きさはlargeでいいだろうか

**Comment by takahashim** [comment]
サブタイトルをタイトルの前につけたい問題とかはどうしますかね…（無視なら無視という作戦もアリかとは思います）

**Comment by kmuto** [comment]
preとpostの両方を用意する？ というのも設定がちょっとゴチャゴチャになりすぎる気もしますね。本題の上に置く/下に置くのフラグを用意する？

**Comment by takahashim** [comment]
`\reviewtitle`と`\reviewsubtitle`を用意しておいて、通常はsubtitleを下ということにしておいて、あとはlayout.tex.erbで頑張れ、というのがいいですかね…

**Comment by kmuto** [comment]
HTMLのほうも同じ問題にあたりそうなので、どうしたものか…。HTMLのほうはmaker内で作っちゃってるから、変えずらいよね。

**Comment by kmuto** [comment]
そういう意味ではheadsubtitle みたいに「前につける」サブタイトルパラメータを別途用意するのがよいだろうか。（両方使う、という本もなくはないし）

**Comment by takahashim** [comment]
電書協・デジコミ協　共通書誌情報だと「前サブタイトル」「後サブタイトル」というものがあるようです。
http://ebpaj.jp/cmspage/wp/wp-content/uploads/2015/02/kyotsushoshi_ver20.pdf

EPUB3だとdisplay-seqというので制御することになっているのですが、古いリーダだとサポートされてなかったようです。むむむ…。
https://www.safaribooksonline.com/blog/2011/05/31/subtitles-in-epub-3/
http://imagedrive.github.io/spec/epub30-publications.xhtml
http://www.web-cte.co.jp/kozakuralab/?p=1875

**Comment by takahashim** [comment]
前サブタイトル対応はさておき、とりあえずこちらはマージしておきますかね…
（ちゃんと対応するなら、おそらくsubtitleの値が「文字列」だけじゃなく「ハッシュの配列」を許すようにして、前者なら単独の後サブタイトル決め打ち、後者なら順序属性をハッシュの形で持ったサブタイトル情報が配列内に列挙、みたいな感じで実装することになるんじゃないかなーと思います）

**Comment by kmuto** [comment]
はい、後側につけるほうはとりあえず入れていいかなと
