### ISSUE TITLE
version 2.2.0

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#750]
そういえば今月リリースでしたっけ…？

**Comment by kdmsnr** [comment]
ハッ:astonished:

**Comment by kmuto** [comment]
あと入れられそうなのは #756, #757 くらい？

**Comment by kmuto** [comment]
あとは #655 がなんとかなるかどうか、くらいですかね。
リリースしてよい状態にはなってきたかと。

**Comment by takahashim** [comment]
pxrubrica入れておきましょうか。
あとjumoline.styがなくて`@<u>{}`がエラーになってた人がいたので、こちらも入れたほうがよいかもです。

**Comment by kmuto** [comment]
pxrubrica、jumolineはどちらもUbuntu/DebianのTeXLiveには入ってなさそうですね。利用前提だとDocker環境などで困る気がします。コメントで入れておく？

**Comment by takahashim** [comment]
と思ったら、ファイル自体は入ってるけど`review-init`コマンドではコピーされない、という問題かも？

**Comment by kmuto** [comment]
vendor/jumolinesですね。jumolineのライセンスはlppl.txtだそうですが、Re:VIEW内収録で配布するからにはlppl.txtを中に入れて、review/README.mdにも書いておいたほうがいいのでしょうか。

**Comment by takahashim** [comment]
確かにlppl.txtも入れてREADMEに書いておいたほうが親切そうですね。
あとpxrubricaはtexlive-lang-japaneseに入ってませんか？
https://packages.debian.org/jessie/tex/texlive-lang-japanese

**Comment by kmuto** [comment]
あ、検索方法まちがっていました。確かにpxrubrica入っていますね。じゃぁ問題ないか。

**Comment by kmuto** [comment]
まずは #762 でlppl.txt設置とjumolineの有効化を試みます。が、usepackageで有効にするとjumolineをコピーしていない既存環境で問題が…

**Comment by kmuto** [comment]
とりあえずjumolineは対処済み。
pxrubricaはどうしましょう、含めます？

**Comment by takahashim** [comment]
pxrubricaは先送りでもいいかもです、と思ったけどそもそもChangelog書いてなかった…

**Comment by kmuto** [comment]
えーと、あとどうしましょうか。ChangeLogを書けばよい？

**Comment by takahashim** [comment]
すみません、ChangelogじゃなくてNEWS.mdは鋭意作成中です…今週末にはなんとかする予定

**Comment by takahashim** [comment]
リリースしましたっ 🚀

**Comment by kmuto** [comment]
アリガトウゴザイマス！
