### ISSUE TITLE
config.ymlにbackcoverを指定しても裏表紙が出ない

### ISSUE THREAD

**Issue by dmiyakawa** [kmuto/review#765]
v2.2.0で再現。v2.1.0でも発生しているような気がします。

サンプル
https://github.com/dmiyakawa/review_v220_backcover_missing

(debug=true, book-pdf/, book.pdf を保持しています)

config.yml にて backcover を指定しているつもりですが、
生成されたbook.pdfには裏表紙 (表4) はくっつかないようです。

**Comment by kmuto** [comment]
config.ymlのサンプルのドキュメントがまちがっているようです。
コード的にもbackcoverがとるのは画像じゃないですね。

- TeXの場合: TeXソース断片ファイル。つまり、もし画像とか入れるならincludegraphicsとかのTeX命令を入れたもの。
- EPUBの場合: 生HTML全体ファイル。

同じパラメータ名なのにデータとしては共有できないという問題もあります。

**Comment by dmiyakawa** [comment]
ソースコードまで確認できていないのですが、covers/backcover.tex 等を作成して指定してみてもうまくいかない感じでした (焦ってやった手前何か間違っているかもしれませんが)

debug=trueによって途中生成されるbook.texに、手動で

```
%%% backcover

\thispagestyle{empty}
\begin{center}
  \includegraphics[width=\textwidth,height=\textheight,keepaspectratio]{./images/cover.jpg}
\end{center}

\end{document}
```

などと入れて book-pdf/ 内で ``uplatex book.tex && uplatex book.tex && uplatex book.tex && dvipdfmx book.dvi`` すれば裏表紙がPDF内に入りました、が、元テンプレートを前提にしたおまじない感が少ししました (特に ``\thispagestyle{empty}`` なしだと最後の章情報が出てしまうみたいです)

**Comment by kmuto** [comment]
もともと裏表紙に限らずベーシックルールに沿わないものを注入するためのものだと思うので、どうしても生LaTeX感がありますね。
ファイルをコピーしてからコンパイルするわけなので、coversに入れちゃうとたぶんまずいと思います。

backcover.tex (config.ymlと同じフォルダ内)
```
\clearpage
\thispagestyle{empty}
\begin{center}
  \includegraphics[width=\textwidth,height=\textheight,keepaspectratio]{./images/cover.jpg}
\end{center}
```

config.yml
```
backcover: backcover.tex
```

で手元では後ろに入ります。

**Comment by dmiyakawa** [comment]
反応が遅れました。上の方法でうまくいくことを確認出来ました。とりあえず、ありがとうございます。
