### ISSUE TITLE
EPUBMaker: add new option `imgmath`

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#773]
mathmlは人類には早すぎたので、数式を画像にするオプションを追加する。

Sphinxを参考にして、latex + dvipngの仕組みをreview-ext.rbで試してみたら動いた（ただしゴミが大量生成される）ので、EPUBMakerにフィードバックする。

**Comment by takahashim** [comment]
参考:

* http://www.sphinx-doc.org/en/stable/ext/math.html
* https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/imgmath.py

**Comment by kmuto** [comment]
内製で類似のを作って保持してはいるんだけど（いくつかのEPUBに使っている）、ベースライン合わせる方法と再利用判定が難問。

**Comment by takahashim** [comment]
#774 で対応してみました

**Comment by kmuto** [comment]
機能自体は求められているものだと思いますので、入れましょう
