### ISSUE TITLE
latexbuilderのincludegraphicsを使っているところで、オプションの指定が必要になりそう

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#791]
http://qiita.com/zr_tex8r/items/a0516f211831a3fc2c0e

graphicxの仕様変更に伴い、Illustratorからの特定ファイルについてはincludegraphicsにpagebox=cropboxを指定する必要がある。全部に指定すればいいわけではなく、自動判定もできないので、特定ファイルを使っていることを原稿執筆者が認識した上でオプションを付ける、という形。

ただ今のid,caption,metricという上にさらに[]で新たにオプションを追加するのは避けたいし、ましてそれがTeX個有のものとなると嫌すぎる感じ。

//lateximageoptions[] とかを入れて後続に渡す…？ `@<icon>`のインライン画像についても悩む。

**Comment by kmuto** [comment]
とりえずなくて大丈夫そう？？

**Comment by kmuto** [comment]
いや、これアカンね。CC途中からで作ったIllustratorは、

- CS6形式保存
- アートボードを紙ではなくオブジェクトサイズに

としても、紙（A4）情報がどうしても残る。これを解消するにはpagebox=cropbox指定をするしかない。
(逆に、すべてにpagebox=cropboxとしておくと何か問題が発生するんだろうか？ fullpagegraphicsとかが困る？)

**Comment by munepi** [comment]
@kmuto さん，

> これを解消するにはpagebox=cropbox指定をするしかない。

結局，これもRe:VIEW側の図版仕様を決めるしかないですね。
一般的なユーザのツールの用途と `/ﾅﾝﾄｶBox` の無理解でもなんとかなるようにするためには， `pagebox=cropbox` の仕様決めうちで十分だと思います（ `/CropBox` が無ければ，`/MediaBox`  を見に行くので）。

現状，latexbuilder.rb で `\includegraphics` に吐いているオプションなどは，全部LaTeXに丸投げでして，必要なコアなユーザだけがLaTeX側のオプションを与えるなり，スタイルファイルを改良することで，特定の処理を済ませるようにしておきたいかなーと。

```
//image -> \reviewincludegraphic

\reviewincludegraphic[オプション]{} <= \includegraphics に inherit する形で実装するだけ!!
```

**Comment by kmuto** [comment]
お返事しそこねてましたが、includegraphics別名だと既存の環境に影響が大きそうなため、pdfmaker/bboxパラメータを導入し、定義されていればextractbbとebbを呼び出しているところでその値を使う、というようにしてみました（某書でさっそく使い始めました…）。
