### ISSUE TITLE
review-compileコマンドの-aオプションについて

### ISSUE THREAD

**Issue by quad9** [kmuto/review#807]
下記、クイックスタート
https://github.com/kmuto/review/blob/readme-md/doc/quickstart.md

において手順通り行い、

> To convert hello.re, you can use review-compile command.
> $ review-compile --target html hello.re > hello.html  ## generating HTML
> $ review-compile --target latex hello.re > hello.tex  ## generating LaTeX
> $ review-compile --target idgxml hello.re > hello.xml ## generating XML for InDesing

ここまでは難なく出来ました。次に

> You can convert all *.re files in catalog.yml with -a option.

の箇所で、複数の「.re」ファイルを作成し、catalog.ymlに増やしたファイル名も追記。

> CHAPS:
>   - hello.re
>   - hello2.re
>   - hello3.re

その上で、記載されているオプションをつけてコマンドを実行しました。
$ review-compile --target html -a

ところが、これが受け付けられないオプションであるとのエラーが帰ってきました。
review-compile: error: invalid option: -a

なお、複数の「.re」ファイルを作成せず、catalog.ymlにもファイル名を追記しない初期状態でやっても同じエラーが帰ってきます。

----- 環　境 -----
MacOS 10.12.6
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
review2.3.0
rbenv 1.1.0
Homebrew 1.2.2
Homebrew/homebrew-core (git revision d467e; last commit 2017-06-08)

**Comment by kmuto** [comment]
お手数おかけします。
-aは使用用途がほとんどないので削除したのですが、英語版quickstartのほうに説明がまだ残ってしまっていました。（https://github.com/kmuto/review/blob/readme-md/doc/quickstart.ja.md からは削除されています）

quickstartのそのあとの説明にあるように、EPUBを作るときはreview-epubmaker config.yml、PDFを作るときはreview-pdfmaker config.ymlでまとめて生成しますので、「-aオプションでまとめて作る」ことについては無視してください。

**Comment by kmuto** [comment]
残っていないなと思ったら、readme-mdは古いブランチでした。混乱を招くだけなので削除します。

ドキュメント最新を参照されるときは、
https://github.com/kmuto/review/wiki
に最新側(master)へのリンクがありますので、こちらを利用してください。
