### ISSUE TITLE
PDF作成時にリンクの枠線を消したい

### ISSUE THREAD

**Issue by vvakame** [kmuto/review#808]
```
\begin{document}
```
の後に
```
\hypersetup{hidelinks}
```
的なヤツを突っ込むオプションがほしいです。

catalog.ymlのpdfmakerの下に hidelinks: boolean 的なのを生やす対応でよさそうだったらその内容で実装してPR送ろうかなと思っています。

**Comment by vvakame** [comment]
背景：印刷所に作ったデータ入稿しようとしたらこの枠線グレスケ化したら出なさそう と言われて、えっ出るんだ！消したい。ってなった。

**Comment by takahashim** [comment]
いやー、これは他のhyperrefのパラメータをいじりたい場合もあるでしょうし、*.styで変更してもらった方がいいんじゃないでしょうか…。

**Comment by kmuto** [comment]
とはいえ、普通はhyperrefのパラメータなんてわからないし、入稿エラーにつながりそうなのはなるべく明確に設定できるといいかなと思いました。
#809 で提案。

**Comment by kmuto** [comment]
本当はクラスファイルを提供して、texoptionsパラメータのほうで全部設定できるのが理想かなぁ。

**Comment by takahashim** [comment]
「hyperrefのパラメータなんてわからない」という人向けには印刷用のスタイルを提供するべきで、とりあえずリンクの枠線だけ消すオプションというのはHTML/EPUBとも非対称だしおすすめできないと思っております。

**Comment by takahashim** [comment]
↑言い換えると「CSS組版用にリンクの下線を消すオプションをconfig.ymlに追加する」というのと同等に見える、ということです。

**Comment by kmuto** [comment]
なるほど。では逆に印刷用のスタイルの提供はできるでしょうか？
レイアウトを選択する仕組みも必要になる？

**Comment by takahashim** [comment]
それについては、review-initのオプションでgithubとかのURLを指定すると、そこにあるファイル群を元に初期プロジェクトファイルを生成できる、という技を先週思いつきました。

が、もうちょっと具体的な方法を詰めないと(実際に指定するURLはどういうので、プロトコルはgitなのかhttpなのか、ファイルはどこまで指定できるのか)…というところです。

**Comment by takahashim** [comment]
まあ手っ取り早くは https://github.com/TechBooster/C89-FirstStepReVIEW-v2/blob/master/articles/sty/techbooster-doujin.sty をコピって使ってね、というところなのですが…というか、なんでこのスタイルはhidelinksになっていなんだろう？？

**Comment by znz** [comment]
> それについては、review-initのオプションでgithubとかのURLを指定すると、そこにあるファイル群を元に初期プロジェクトファイルを生成できる、という技を先週思いつきました。

初期化時にファイルを指定して、というと [Rails のアプリケーションテンプレート](https://railsguides.jp/rails_application_templates.html) を連想したので、参考にすると良さそうに思いました。

**Comment by vvakame** [comment]
🐑はAcrobatで加工するときに消してると言ってた気がするのでやり方の存在を知らなかった可能性が微レ存… @mhidaka

**Comment by munepi** [comment]
すごい遅い反応で申し訳ないですけれども…、

> 背景：印刷所に作ったデータ入稿しようとしたらこの枠線グレスケ化したら出なさそう と言われて、えっ出るんだ！消したい。ってなった。

これは、印刷所さんがアレなのかもしれませんが…。
そんな調子だと、PDFデジタルトンボ（ `/ﾅﾝﾄｶBox` たち）すらも、実線として印刷されてしまいかねませんね。

From @kmuto: 
> 本当はクラスファイルを提供して、texoptionsパラメータのほうで全部設定できるのが理想かなぁ。

Re:VIEWで用途別仕様を決めてしまうというのも一つですね。
とは言っても、以下のおもに2通り（プレビュー用は、たぶん要らない）だと思います。

 * 印刷用：紙媒体の印刷仕様PDFを生成
    - hyperref: draft
 * 閲覧用：PDFビューワーの閲覧仕様PDFを生成
    - hyperref: 有効、hidelinksオプションは好みが分かれるところだけれども、これもRe:VIEW側で標準仕様を決めればよさそうです。
 * プレビュー用：非商業用フォントな環境でとりあえずフォントを埋め込んだだけのPDFを生成
    - hyperref: draft or 有効

わたし個人的には、こちらのほうが好みで、例えば、版下オプション cameraready=<value>として、以下のとおりです。

 * cameraready=print: 印刷用（デフォルト値）
 * cameraready=pdf: 閲覧用
 * cameraready=preview: プレビュー用


一方で、
From @takahashim 
> 「hyperrefのパラメータなんてわからない」という人向けには印刷用のスタイルを提供するべきで、とりあえずリンクの枠線だけ消すオプションというのはHTML/EPUBとも非対称だしおすすめできないと思っております。

でおっしゃるとおり、（完全に！！）一理ありで、これを Re:VIEW の仕様としてしまって良いと思います！

**Comment by vvakame** [comment]
アレじゃない印刷所だとどういう反応になるんだろ…(NO知識マン
枠線有りデータ、電話口に出た営業さん（？）が「オペレータさんに消せるか確認してみますねー」ってなって、電話こなかったのでデータ差し替え無しで多分無事に刷られた予感がします。
刷り上がりが見れるのは11日。

---

ここまで読んだ感じの僕の気持ちは

1. 1ソース マルチユースだと嬉しいのでPDF出力形態毎に別プロジェクト作れとかは辛そう
2. review叩いたらPDF出来た的メンタルモデルはあまり崩したくない
  * latexとかの存在はあまり知らなくてもいいほうが嬉しい
  * 深く使うのにlatexしないといけないのは仕方ないかもしれないけど印刷用とか電子閲覧用のPDF出し分けは深い利用方法じゃないくくりだと嬉しいな…
3. 出力変える時にファイルの変更無いほうが嬉しいな
  * コマンドラインだけでepubとpdfの出し分けができるのと同じレベルであってほしい
  * リポジトリの状態に出力モードが依存するのは微妙だよねみたいな気持ち
4. たかはしさんのテンプレプロジェクト案は良いと思う
  * TechBoosterも毎回プロジェクト作る時に既存プロジェクトのコピーから初めてて毎回アレだなーと思っている

**Comment by takahashim** [comment]
@znz 確かにRailsのアプリケーションテンプレートに近い気もしますが、あちらは生成方法をDSLで表現するような（一種動的な）ものですよね。
Re:VIEW使うひとにDSL覚えたりしてもらうのも大変そうですし、もうちょっと静的なファイル（YAMLとか…？）で指定できるようにしたい気もします。

**Comment by mhidaka** [comment]
テンプレ的な話が広がるようなら議論の場をととのえてIssue化してもらえると参加しやすくて嬉しいです

**Comment by suzukin** [comment]
テンプレの話は https://github.com/thinkitcojp/tibooks-maker でやってきたこともあるので議論したいところではあります。次回Re:VIEW developers meetingはいつでしょう？ｗ

**Comment by kmuto** [comment]
meetingはそろそろやりたいのですが、issueで調整というのも変なかんじなのでどうしたらいいですかね… 高橋さんのrubykaigiが終わってから？

**Comment by vvakame** [comment]
#818 で話されてほしいやつ

**Comment by takahashim** [comment]
とりあえず #1033 で、デフォルトではリンクの枠線を表示しないようになりました
