### ISSUE TITLE
複数のテンプレートをRe:VIEW本体で抱える検討

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#812]
cf #808 

複数のlayout.tex.erbをRe:VIEW本体で提供しようとする場合、ReVIEW::Template::TEMPLATE_DIRから選ぶための設定方法が必要になる。
今はlatex/layout.tex.erbきめうち。

**Comment by takahashim** [comment]
どちらかというと、将来的にはlayout.tex.erbは最小限のもので固定にして、*.styに全て追いやる方がいいのかなという気もしております。

**Comment by kmuto** [comment]
styファイルはreview-init時に作業フォルダにコピーする? それともreview-pdfmaker実行時にRe:VIEWのlib/templatesからコピーする?

前者だと既存環境では動かなくなるのとバグ修正を伝播できないですが。後者だとカスタマイズしたいときにどうしようかという問題があります。

**Comment by takahashim** [comment]
前者でしょうねえ。
既存環境のものについては互換性がなくなってしまうかもです。

**Comment by kmuto** [comment]
うむむ。自分の制作範囲だとlayouts/、sty/はもともとごっそり入れ替えているので影響は少ないですが。

layouts/, sty/が存在しない/空の場合はpdfmaker側でコピーかなぁ。

**Comment by kmuto** [comment]
jlreq版スタイルを作ってみていますが、今後どのくらいの単位でsty分割したらよいか悩み中。いまのところ、

- プリアンプルまわりでlualatex/uplatexでどうしても共通化できないものがある。
- フォント設定部分は分離したいかなー（ただこれもlualatex/uplatexで全然違う）。
- noteやコラムなどの囲み記事、listやemlistなどのリスト部分の表現実装は人によって好みが分かれそうなので分離したほうがいいか。
- あまり分割しすぎると変なCMSみたいになってよろしくない。

**Comment by kmuto** [comment]
https://github.com/kmuto/exp-review-cls で実験していますが、
config.ymlのパラメータをstyに渡すプロセスが厄介です。

- keyval化したtexファイルを読ませる。keyval化の作業がまず煩雑で、取り出しもわかりづらそう。
- styのほかに、sty.erbも許容する。最初にerb実行してからビルドフォルダに放り込む、とか。

**Comment by kmuto** [comment]
「Re:VIEWシステム側はこういうフォルダ構成になっていて」→「review-initではこういうオプションで選択できて(?)」→「プロジェクトフォルダはこうなる」というおおまかなイメージはないでしょうか。

クラスファイルはまにあわないにしても、現状のjsbook系データをこの形にする準備はしたいのですが。

**Comment by takahashim** [comment]
将来的には、

* `*.re`を別ディレクトリに置く
* `review-init --template https://example.com/templates/template.yml`みたいな感じでディレクトリ構成のYAML（or JSON?）ファイルを持ってくるか、`review-init --template https://example.com/templates/template.zip`みたいな形でテンプレートファイルを持ってくるかする

みたいな感じでしょうか…。

Sphinxのテーマ http://www.writethedocs.org/guide/tools/sphinx-themes/ やgitbookのテーマ https://github.com/GitbookIO/theme-api (例: https://github.com/nijikokun/clarity ) をみた感じでは、わりとベタな感じなので厳しい気分になりました。

**Comment by kmuto** [comment]
- 「*.reを別ディレクトリに置く」は今作りかけのdraftdirみたいなパラメータを追加するかんじでしょうか。#938
- LaTeXのテンプレートの選択は #950 で実装してみましたが、LaTeXのみの想定＆フォルダ指定 でした。URLならそっちを拾う・zipを展開する もできそうではありますが、LaTeXもHTMLもとなるとパラメータや展開するファイル群などいろいろ考慮が必要そうです。

**Comment by takahashim** [comment]
#938 はそんな感じになるかと思います。実装はFile.joinを使った方が良さそう

**Comment by takahashim** [comment]
#950 はあんまり良く分かってないんですが（すみません）、erbは1個だけ+素のstyじゃ難しいんでしようか…？

**Comment by takahashim** [comment]
pdfmakerのこの辺でやりたいことは、詰まるところRubyの世界とLaTeXの世界とでの（主にconfig.ymlの）情報の受け渡しと、その情報を元にしたLaTeXの処理で、前者についてはlayout.tex.erbで実現して、後者についてはLaTeX（*.sty)のみでできるといいんですが、実際LaTeXだけでできるかどうかがちょっと自信ないです

**Comment by kmuto** [comment]
#938 についてはFile.join化してみました。ただFile.joinだと`./.`はそのままにしちゃうんですね。Pathnameのcleanpathまで使うのは大仰すぎるように思えたので、draftdirデフォルトを空文字列にして通すようにしました。

ymlの内容を定義しておいてマクロだけでなんとかならないかというのは #864 で苦闘してみたのですが、クラスファイル側にその準備がないと無理だと思いました。

**Comment by takahashim** [comment]
> ただFile.joinだと./.はそのままにしちゃう

むーん、そうなんですね。失礼しました。
`Pathname.new("foo").join(".","bar")` だと正規化してくれるみたいですが、`to_s`つける必要あるし、ちょっと冗長なので、File.joinで十分そうです。

**Comment by takahashim** [comment]
layout.tex.erb 全体は https://gist.github.com/takahashim/30e3148ff306f0ec2019932e6738d9ec こんな感じとかにすると、`\begin{document}`〜`\end{document}`からはRubyの埋め込みがなくせそう。その代わり文書構造は決め打ちになります（ある程度hook部分でいじれるけど）

**Comment by kmuto** [comment]
なるほど… ちょっとその方向で書いてみましょうか。

**Comment by takahashim** [comment]
少し考えてみたのですが、もしかしたら`\begin{document}`〜`\end{document}`内での埋め込み自体は避けなくてもいいのかなあ…という気もしました。
（この方法だと、例えば最後の手段として*.styの中で`\renewcommand{\revewcreditfile}`で書き換えできるので自由度が高まるかも、という気持ちだったのですが、それで救える場面が少ないんなら別に埋め込み自体は忌避しなくてもよいか、ということです。）

**Comment by kmuto** [comment]
作ってるときでも困ったことなんだけど、配列とかハッシュみたいなものはどう表現しよう問題があるんだよねぇ。
とりあえず今のjsbookの互換で単純文字列化しておく？

**Comment by kmuto** [comment]
プリアンプル内で生なerbで条件式分岐している箇所は以下のところですが、どう代替しましょうかね…

```
<%- if @texcompiler == "uplatex" -%>
\usepackage[deluxe,uplatex]{otf}
<%- else -%>
\usepackage[deluxe]{otf}
<%- end -%>
```

```
<%- unless ["utbook", "tbook"].include?(@documentclass)  -%>
\usepackage[top=10zw,bottom=12zw,left=10zw,right=10zw]{geometry}
%\usepackage[top=5zw,bottom=5zw,left=1zw,right=1zw]{geometry}
<%- end -%>
```

```
<%- if ["utbook", "tbook"].include?(@documentclass)  -%>
\newcommand{\headfont}{\gtfamily\sffamily\bfseries}
\usepackage{plext}
<%- end -%>
```

```
<%- if config["highlight"] && config["highlight"]["latex"] == "listings" -%>
<%-   if config["language"] == "ja" -%>
\usepackage{listings,jlisting}
<%-   else -%>
\usepackage{listings}
<%-   end -%>
\renewcommand{\lstlistingname}{<%= escape_latex(I18n.t("list")) %>}
(この先まだずらずら)
<%- end -%>
```

```
<%- if @config["toctitle"].present? -%>
\renewcommand{\contentsname}{<%= escape_latex(@config["toctitle"]) %>}
<%- elsif I18n.t("toctitle") -%>
\renewcommand{\contentsname}{<%= escape_latex(I18n.t("toctitle")) %>}
<%- end -%>
```

```
<%- if @config["texstyle"] -%>
<%-   [@config["texstyle"]].flatten.each do |x| -%>
\usepackage{<%= x %>}
<%-   end -%>
<%- end -%>
<%- if @config["makeindex"] -%>
\usepackage{makeidx}
\makeindex
<%- end -%>
```

**Comment by takahashim** [comment]
LaTeX側で扱えるのは文字列が基本になるかと思うので、LaTeX側で使うための文字列を一通り用意しておくのがいいのかなと。ループとかがなければ。
あとは`\ifx`とか`\ifdefined`とかでいけるといいんですが。と思ったけどifthenパッケージの方がいいんでしょうか？

**Comment by kmuto** [comment]
ifx,ifdefinedでもいいんだけど、特にifxは読みにくいなぁと思っていて、制御構文の可読性+baseのTeX環境で使えるの点でifthenパッケージはわりと使いやすいのでは、と思いました。
全部にelse句が入るのがちょっとアレだけど。

**Comment by kmuto** [comment]
あとは

- packages部分を切り出してユーザーのstyにコピーするとして、単一のstyにする？ 機能ごとに分ける？
- document内はどのくらいstyに移動をがんばる？
- titlepage, coverimageの分離はこの機会に入れる？

あたりでしょうかね。
chaptermarkをいじるのは本来はクラスファイル側がカバーしたほうがよいことだろうなぁ…。

**Comment by kmuto** [comment]
yamlからの変換・command定義まわりはpdfmaker.rb側でやってあげて、layout.tex.erbでは `<%= define_texconfig%>` みたいにしておいたほうがよいのかなと思っています。

ifdefinedを有効活用しようとすると、「最初から定義しない」の挙動が必要になって、それをlayout.tex.erbで書くのは冗長すぎるかんじがしています。

**Comment by takahashim** [comment]
`*.sty`については、

* review-initを実行すると、Re:VIEW標準の*.styがプロジェクト用ディレクトリのsty/以下に入る
* 上記で生成された*.styは基本ユーザがいじらないことにする。それ以外にユーザ用の空のstyを用意して、そこはユーザが自由に変更できるようにする（以前  kauplanさんが書いてたようなパターン）
* Re:VIEWのマイナーバージョンがあがって変更が入った場合にはsty/以下を更新版で差し替えてもらう（？？）、あるいはreview-pdfmakerで上書きするオプションを用意する（？？？）

みたいな管理方法がいいんですかね…。

> titlepage, coverimageの分離はこの機会に入れる？

はい、このタイミングで入れた方がよさそうです。

> chaptermarkをいじるのは本来はクラスファイル側がカバーしたほうがよいことだろうなぁ…。

https://gist.github.com/takahashim/30e3148ff306f0ec2019932e6738d9ec 
でも書きましたが、 frontmamatter/mainmatter/appendix/backmatterの前には全部hookを入れて、chaptermarkとかはそこでいじるというのでどうでしょう。
（この章だけ変えたい、というのは*.reに`//embed`を入れてもらうということで）

**Comment by kmuto** [comment]
うーん、「いじらない」ものならユーザ環境に提供するよりはRe:VIEW template directoryからビルド時にコピーすればいいということになるような。

pdfmakerで上書きは気持ちが悪いので、やるならinit、あるいはRakefileですかねぇ。間違えるとプロジェクトのファイルを壊しそうなのが不安か。

**Comment by takahashim** [comment]
バージョンアップしても既存プロジェクトが壊れにくい方法にしたいところです、はい。

**Comment by kmuto** [comment]
defineの構文は「とりあえず現状のをなんとかすべく」入れたものなので、今後のバージョンアップでまたごそっと変わるかもしれません。そうすると、それに基づいていたstyをプロジェクトに配備してしまうと厄介なことになるのを懸念します。

あと、1つのstyにするのか、カスタマイズ用に複数置くのか、TeXエンジンごとの違いはどうするのか、といったあたりも問題でしょうか。
ユーザー設定環境については、reviewmacro.sty の内容を基本styのほうに含めて、reviewmacro.styを空にしておく だと影響は少ないんでしょうかね。

**Comment by kmuto** [comment]
#1105 と #1117 にて対応
アップデートは別issueを立てる
