### ISSUE TITLE
Re:VIEW Meeting 2017 Autumn

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#818]
We will hold a meeting about Re:VIEW. ( https://twitter.com/kmuto/status/910744367635226624 )

## Agenda

* layout template
    * support multiple layouts (複数レイアウトを切り替え)
    * use only style files instead of layout template (`*.tex.erb`捨てて`*.sty`に押し込む)
    * #812 #811 #808 
    * 今よりもカスタマイズしやすいクラスファイル、スタイルファイルの制作。判型・版面・書体まわり
* LaTeX matter
    * support LuaLaTeX ? (上記と関連して*.styに集約すればいけそう？) #451
    * 縦書き出力時の問題 #695 
    * inline_brの処理（表内） #668 
    * ルビ #655 
    * jlistingのalternative? #635 
    * column内tableの消失 #222 
* and so on (その他何かあれば)
    * CSSディレクトリ #631 
   * HTMLのid #551 
   * HTMLでrougeをデフォルトにする? #485 #491 

## Date

* 10月27日(金) 19:00

## Place

* インプレスグループ23F会議室

https://connpass.com/event/68001/

**Comment by kmuto** [comment]
会場は @suzukin さんにお願いしてもよいでしょうか。時期・時間が問題ですね。
Twitterで挙げたように@kmuto は
10/6夜, 10/7, 10/27夜, 10/28, 11/2夜, 11/3, 11/4, 11/10夜 くらい。

TeXのことが多くなりそうなので、@munepi さんにもいてほしい。
Techboosterのひとたちの意見もほしいとなると、@vvakame さんか @mhidaka さん?

**Comment by takahashim** [comment]
とりあえず10/27夜か11/2夜あたり？

**Comment by suzukin** [comment]
* 10月27日 19：00～
* 11月2日 19：00～

で、とりあえず10人部屋（モニター、ホワイトボードあり）を抑えときました。もしそれ以上増えるようなら別途調整しますー
http://www.impressholdings.com/info/profiles/map.htm

**Comment by kmuto** [comment]
会場ありがとうございます。私は10/27、11/2どちらでも大丈夫です。

**Comment by 7gano** [comment]
PEAKS（https://peaks.cc）というサービスをやっています、永野と申します。
Re:VIEW使わせていただいておりまして、今後もすごい使うので混ぜていただいてもよろしいでしょうか。
（こういうのあったらいいなみたいな意見が出せるかもレベルですが）

**Comment by kmuto** [comment]
@7gano さん、もちろんどうぞー

**Comment by 7gano** [comment]
@kmuto ありがとうございます！楽しみにしています

**Comment by 7gano** [comment]
10月27日 19：00～
11月2日 19：00～
どちらでも行けます。

**Comment by mhidaka** [comment]
10月27日 19：00～ 日本にいます！
11月2日 19：00～ 日本にいません！

**Comment by yuw** [comment]
LuaLaTeX化を推したいので参加したいです！

**Comment by suzukin** [comment]
鈴木＠会場担当です。mhidakaさんが27日のみとのことですが、 @munepi さんご予定いかがでしょうか？

**Comment by vvakame** [comment]
どちでも大丈夫です！

**Comment by munepi** [comment]
わたしも 10/27, 11/2ともに参加可能です！
わたしは、両日開催でも…、もちろんOKです :-)

**Comment by kmuto** [comment]
では10/27(金) 19:00、インプレス にて、で確定しましょう。
@suzukin さん、会場ありがとうございます！

**Comment by suzukin** [comment]
いちおうconpassも立てましたー
https://connpass.com/event/68001/

**Comment by huideyeren** [comment]
遅ればせながら参加させてください。

**Comment by kmuto** [comment]
おつかれさまでした、本日の議事録です
[reviewmtg1027.pdf](https://github.com/kmuto/review/files/1422341/reviewmtg1027.pdf)

**Comment by takahashim** [comment]
https://github.com/kmuto/review/wiki/Re:VIEW-%E9%96%8B%E7%99%BA%E8%80%85%E4%BC%9A%E8%AD%B0-2017-Autumn-%E8%AD%B0%E4%BA%8B%E9%8C%B2

ざっくり転記しておきました

**Comment by vvakame** [comment]
そういえば会では思い至らなかったですがsemver文化圏の人間としては話された内容が色々入るのであれば次期versionは3.0でいいような気がします

**Comment by yuw** [comment]
jsbookのfreezeとlayout.tex.erbの廃止が成されれば，メジャーバージョンの更新に充分な理由になると思います．
