### ISSUE TITLE
EPUBでの画像サイズに警告したい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#819]
某電書仕様により、縦横ピクセル積が 4,000,000 以上は禁止となっている。
Re:VIEW側でリサイズまで面倒を見る必要はないが、警告を出すようにはしたい。

RMagickがあればチェック、とする？

**Comment by takahashim** [comment]
Ruby的には https://github.com/toy/image_size とかで何とかしたいところ…

**Comment by kmuto** [comment]
なるほど、これは軽量でいいかも。

**Comment by kmuto** [comment]
gemの image_sizeとnewer_image_size、とは…

**Comment by kmuto** [comment]
#820 で解決
