### ISSUE TITLE
rubocopに怒られるところを直していきたい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#823]
クォテーション、ブロックの書き分け、キャメルケースの破棄などに手を入れていきたいと考えています。ほかの修正が入らないうちに一気にやってしまうのがよさそう？

**Comment by takahashim** [comment]
クォテーションの統一はしなくてもよい（雰囲気で使い分けたい）ような…。
ブロックの書き分け（Style/BlockDelimiters）は統一しても良さそう。
「キャメルケースの破棄」って何でしたっけ？

**Comment by kmuto** [comment]
camelcaseはmaker系書き換えのときになくなってましたね。

quoteについてはとりあえずrubocop指示のもと' " の使い分けにしたあとにwarning程度にするのがいいんじゃないかなというかんじです。

**Comment by kmuto** [comment]
respect_rubocopブランチでごりごり書き直し中…

**Comment by takahashim** [comment]
うーん、例えばStyle/StringLiteralsは`"..."`を`'...'`の変更をするメリットが感じられないのでだいぶネガティブなのでした

**Comment by kmuto** [comment]
でもStringLiteralsのおかげでrstbuilderのところで一部のstrが変数展開されていないことに気付きましたヨ :)

どっちにしろ以前から入り乱れていたので、ひとまずはチェックのためにも作業進めます。

**Comment by takahashim** [comment]
むむ、そうなんですね。
文字列については、

* 基本は `"..."`で統一
* エスケープが辛くなったら `'...'`を使う
* interpolation使ってるけどエスケープで辛くなったら%Q系を使う

が好みなので、ルール化が難しいのでした。

**Comment by kmuto** [comment]
#827 で作業ちゅう。読みやすくなったところもあればいまいちどうだろうというところも。

途中でいくつかRe:VIEW自体のバグを見つけたりしています。

**Comment by kmuto** [comment]
やっと通りました…

とりあえず手元でいろいろ実験した限りでは、挙動は同じまま動いているように見えます。

- review-epub/pdf/web maker
- review-compile
- review-validate
- review-init
- review-vol
- review-index
- review-catalog-converter
- review-preproc

**Comment by kmuto** [comment]
マージしました。

とりあえずrubocopさんに従って変えていきましたが、これはイヤだというルールについては戻してOKです。
