### ISSUE TITLE
PDFMaker: fix attr `coverfile` and `titlefile` in config.yml

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#839]
config.ymlでの`coverfile` や `titlefile` について、EPUB等と扱いが違うようなので整理が必要そうです。

**Comment by kmuto** [comment]
たしかに。想定挙動はEPUBのほうが正です。

- cover: 表紙の生ファイル(.htmlまたは.texの断片)。
- coverimage: 表紙画像。cover:での明示指定がないときはこの画像を表紙として使う。
- titlepage: 大扉を入れるかどうか。true/null。デフォルトはtrueに
- titlefile: 大扉の生ファイル(.htmlまたは.texの断片)。指定がなければ内部ロジックで大扉を生成する

- 表紙と大扉は別のもの。
- cover: null, coverimage: nullなら表紙は入れない。

**Comment by kmuto** [comment]
#863 で対処済み
