### ISSUE TITLE
FIXME:TeXのキャプションfootnote問題

### ISSUE THREAD

**Issue by munepi** [kmuto/review#841]
https://github.com/kmuto/review/blob/04fd065e67d47f7749b439bed26c9b2e5b323b2b/test/syntax-book/ch02.re#L69

@kmuto さん、
これの本質的なLaTeX再現例は、以下のとおりです。

```latex
\documentclass{ujarticle}
\begin{document}
\begin{figure}
\caption[図目次をオレは使わん！]{キャプションに脚注\footnotemark を入れるなどありえない！}
\end{figure}
\footnotetext{キャプション内に脚注を入れるなどご法度ですぞ！}
\end{document}
```

つまり、

```
\caption{キャプション} => \caption[キャプション]{キャプション}
```

となって、図目次（.lof）に \footnotemark のような“脆い”csnameが混じってしまうことに依ります。
それゆえ、

```
//image[ball][ボール@<fn>{madebygimp}]{
}
```

からのLaTeX変換のキャプションは、

```
\caption[ボール]{ボール\footnotemark}
```

で十分です。

**Comment by kmuto** [comment]
「現在captionの中かどうか」という判定をどうしたものか…。
caption（や同様の症状が発生しそうなもの）だけ特例で記憶させる？

captionのcompile_inlineに引数を増やす？

**Comment by kmuto** [comment]
#858 で環境を見ることはできるようにしているのですが、表現やクラスファイルやTeXコンパイラによっては \protect\footnotemark 決めうちじゃないほうがよいという可能性はありますかね。

でもたとえばクラスファイルによって違うとなると、latexbuilder側でfootnoteにするか、footnotemark/textにするかの判断をしているわけで、どうしたものか…。

**Comment by kmuto** [comment]
#858 で\protect\footnotemarkにしてみました
