### ISSUE TITLE
latexbuilderでtexequationが余計な空行をいれてしまう

### ISSUE THREAD

**Issue by yuw** [kmuto/review#842]
デフォルトとしては次のどちらかの方が望ましいと思います．
1. 空行は入らない
2. 空行の後に```\noindent```を入れる

現状は
```
ほげほげ
//texequation{
\sum_{i=1}^nf_n(x)
//}
ふがふが
```
という入力に対して，TeXファイルの方に
```tex
ほげほげ

\begin{equation*}
\sum_{i=1}^nf_n(x)
\end{equation*}

ふがふが
```
のように，equation*環境の前後に空行がはいります．
これは不用意な段落の変更で，このままでは別行立て数式の上下のアキが不正なものになり，特に直後が空行が無いにも関わらず，段落の開始になってしまいます．

もちろん```//noindent```を前後で用いることによって，正しいアキを得ることと出力上改段落を抑制することができますが，この```//noindent```をいちいち入れるのは正直煩わしいというのもあります．

入力としても『Re:VIEW フォーマットガイド』にある“段落（本文）の間は1行空けて表現します。空けずに次の行を記述した場合は、1つの段落として扱われます。”に矛盾せず，直感に沿うのではないかと思います．

**Comment by kmuto** [comment]
ありがとうございます。

paragraphの処理が先に来て、これが前後blank（空行）を入れちゃうんですよね…。二重blankを防ぐ仕組みはあるものの、先読みして「次の要素が〜なら」という処理をしようとするとまじめにパーザをがんばらないとだめかな。

迂闊にやると「ふがふが」の前に空行があってもつながってしまう、ということになりかねないので、悩ましい……。

**Comment by takahashim** [comment]
これはparser以前にdocument modelを拡張しないといけない問題ですね…。

Re:VIEWフォーマットガイドで想定しているのはインラインの記法が来る場合で、一般的にブロックが来た場合はそこでパラグラフは終了します。これは、

```
foo
//image[]{
...
//}
bar
```

などとなった場合に画像がパラグラフの中に入らないのと同様です（`@<icon>{...}`ならば入ります）。

パラグラフの内部にブロックを許すには、要素内のブロックになりうるブロック種類とそうならないブロック種類を何らかの方法で決めるようにしないといけなさそう。真面目に対応しようとするとDTD or RELAXNGみたいなもので、要素同士の入れ子の関係を定義する必要がある（しかも拡張可能にしないといけない）ので、短期的には避けたいところです。

**Comment by yuw** [comment]
現実的には```//noindent```を適宜いれるようにreファイルを事前に加工するスクリプトをつくるくらいですかね

**Comment by kmuto** [comment]
現状の構造上難しいのと、TeXに寄りすぎる文法になりそうなので申しわけないですがwontfixにて。
