### ISSUE TITLE
secnolevel > toclevelのときにtoclevel以上のレベルの見出しが目次に抽出される

### ISSUE THREAD

**Issue by kokuyouwind** [kmuto/review#846]
config.ymlでsecnolevelをtoclevel以上の値にした場合、toclevelを超えるレベルの見出しがセクション番号なしで表示されます。

テストに使用したのは以下の.reコードです。
```
= レベル1
== レベル2
=== レベル3
```

`toclevel: 1, secnolevel: 2`ではレベル2までの目次が出力されます。

![15f4efcf85bb0f945dcff9a6](https://user-images.githubusercontent.com/1789266/31952201-088d944a-b91b-11e7-9085-2d597cfa60a2.png)

`toclevel: 2, secnolevel: 3`ではレベル3までの目次が出力されます。

![15f4efe54007ae9afc40ca68](https://user-images.githubusercontent.com/1789266/31952321-481c7c8e-b91b-11e7-9a32-4b64388bc37d.png)

`toclevel:1, secnolevel: 3`ではレベル2までの目次が出力されます。
secnolevelまでが出力される、というわけではないようです。

![15f4effb3d807781b0f90c9b](https://user-images.githubusercontent.com/1789266/31952485-a263f258-b91b-11e7-9397-0295ebf80755.png)

なお、いずれもtexソースコードではtocdepthとしてtoclevelが設定されていました。
このためtex側の仕様/バグかもしれませんが、secnolevelまわりの挙動を追えていないためこちらに報告させていただきます。

**Comment by yuw** [comment]
```toclevel```→```\tocdepth```に従って正しく動作しているように見えます．
正確には参照されているjsbook.clsの話になりますが，
LaTeXとして，節に対応するレベルは1，項に対応するレベルは2として利用されています．
ちなみに，章に対応するレベルは0です．

**Comment by kmuto** [comment]
「secnolevel」は、TeXとは関係なく、その見出しに採番するかどうかのレベルを設定するものです。
たとえば「=== タイトル」があったとして、

- secnolevel: 2 「タイトル」
- secnolevel: 3 「1.1.1 タイトル」

なのですが、これで変なところがあるでしょうか。

**Comment by kokuyouwind** [comment]
すみません、例示が適切ではありませんでした。
`toclevel: 1, secnolevel: 1`では「第1章」のみが出力されます。

![15f540c52072238d3d06c0dd](https://user-images.githubusercontent.com/1789266/32006029-a958aab6-b9e0-11e7-8a9d-fad770652797.png)

これに対し、`toclevel: 1, secnolevel: 2`では節までが見出しに表示されており、`toclevel`を変えていないにもかかわらず目次として抽出するレベルが変わってしまっています。

![15f540cf6823f98ff4d5b567](https://user-images.githubusercontent.com/1789266/32006123-e11d8520-b9e0-11e7-8adf-2217e68d349a.png)

> LaTeXとして，節に対応するレベルは1，項に対応するレベルは2として利用されています．
> ちなみに，章に対応するレベルは0です．

言われてみるとたしかにその通りなのですが、`toclevel: 1, secnolevel: 1`で章のみ、`toclevel: 2, secnolevel: 2`で章～節が目次に抽出されていたため、Re:VIEWでは章に対応するレベルが1という扱いになっているのかと思っていました。
ちなみに`toclevel: 0, secnolevel: 0`では第1章の章名すら出力されず、真っ白な目次ページが生成されました。

**Comment by kmuto** [comment]
なるほど、理解しました。TeXでsection*のように展開しているので、TeXの挙動としてこうすると目次から抜けますね。これはaddcontentslineをつっこむしかないかな…

**Comment by kmuto** [comment]
いや、入れているんだけど状況によってうまく入っていない、というバグですね。

**Comment by kmuto** [comment]
すみません、もう1つ勘違いをしていました。おおむね直すべきところはわかったので対処を考えます。

**Comment by kmuto** [comment]
シンプルにtocdepthは-1する必要があるだけだった…。PR#854 で修正予定です。

**Comment by munepi** [comment]
config.ymlの仕様を見ると、「toclevel (int): 目次抽出レベル。最低1」とありました。

#854 の変更の意図は、以下のように理解しておきました。

 * 章 `\chapter` から始まる場合： toclevel: 1（最低値）→tocdepth=0：章見出しまで出る⇒OK
 * 部 `\part` から始まる場合：toclevel: 1（最低値）→tocdepth=0：部見出し、章見出しまで出る：通常、部を立てる本は、「章を束ねる」⇒OK

ただ、個人的には、hyperrefパッケージを読み込む前提のLaTeXクラスファイルの実装では、「`*`」付きの「`\見出し*`」コマンドを使いたくないかなーと。
標準的なLaTeXの汎用クラスファイルを使う前提では、いちいち `\addcontentsline` をlatexbuilder.rbの変換器側でやらざるを得ないですし、それが仕様であれば、仕方ないですけれども。

仕様をどこに合わせるの良いか、色々と難しいところです。

**Comment by kmuto** [comment]
@munepi ご推察のとおりです。部だけ出して章を出さないという目次はまずありえないですよね。

*については、jsbookを壊さないようにするには現状だとこうせざるを得ないかな…というところです。
このほかRe:VIEWの挙動として、secnolevelによらず

* ``==[nonum]``→``* + \addcontentsline``
* ``==[notoc]``→``*のみ``
* ``==[nodisp]``→``addcontentslineのみ(採番もしない)``

というのがあるので、スタイル側を今とは異なる採番判断方式にすると、このあたりの調整も考える必要が出てきますね。
