### ISSUE TITLE
titlepage: nullにするとcoverimageによる表紙も入らなくなる

### ISSUE THREAD

**Issue by kokuyouwind** [kmuto/review#848]
config.ymlで

```yml
coverimage: cover.jpg
titlepage: true
```
とすると表紙も大扉も正しく表示されるが、
```yml
coverimage: cover.jpg
titlepage: null
```
とすると、大扉だけではなく表紙も作成されなくなりました。
texコード上でtitlepageのブロックが丸々消えているため、tex生成周りの問題かもしれません。

**Comment by takahashim** [comment]
すみません、これは #839 に関連するもののはずです。
まともに直そうとすると互換性が壊れそうなのが厳しい…。

**Comment by kmuto** [comment]
#863 で対処済み
