### ISSUE TITLE
imgmathで吐き出す一時数式ファイルを別フォルダにする

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#856]
images直下に吐き出されると消すのもつらい。
内部フォルダっぽく「images/__review_math__/」とか？

**Comment by takahashim** [comment]
なんとなく`_`で始めたいです。`images/_math/`とか`images/_review_math/`とか。

**Comment by kmuto** [comment]
「おそらくユニークで競合しなさそう」であれば、なんでもOKだと思います。

**Comment by kmuto** [comment]
make_math_image見ていたのですが、「latex」呼び出しなので日本語不可、dvipngが別途パスのあるところに必要、というのは罠かもしれないと思いました。

そもそもimgmath自体config.yml.sampleにもまだ書いてないのですね。

**Comment by kmuto** [comment]
そういえば、もとのissue提起のときに`__review_math`としたつもりだったけどMarkdown強調使いになってたのか…
