### ISSUE TITLE
「builder_init_fileのあとに呼び出されるメソッド」というのがほしいかも

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#857]
review-ext.rbで、初期化まわりに「ちょっとだけ」何か加えたいときに、builder_initやbuilder_init_fileのオーバライドは大仰だし、Re:VIEWコアが変わったときに追従が面倒なので、`builder#bind`の最後でbuilder_init_ext() （デフォルトは空）を呼び出すようにするとどうだろう。

**Comment by takahashim** [comment]
今は `prepend` という便利なメソッドがあるのでそちらを使うのをオススメしたいですね…。

```ruby
module MyHackModule
  def builder_init_file
    do_pre_job # なんかする
    super
    do_post_job # なんかする
  end
end

class ReVIEW::LATEXBuilder
  prepend MyHackModule
end
```

**Comment by kmuto** [comment]
む、これはいいことを聞きました。
たしかにそれで十分そう。
