### ISSUE TITLE
imgmath生成ロジックの改良

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#868]
- m, texequation呼び出しの都度生成している。
- SHA256 hashで一意化はしているが、重複チェックしていないので、何度も同じものを作っている。
- dvipngの都合で日本語不可。
- プリアンプルなど決めうち。
- latex, dvipngのパスやオプションなど決めうち。

軽量なドキュメントならこれでもいいのかもだけど。

- 重複チェックは存在確認して存在すればスキップすればいいので簡単にできそうではある。
- プリアンプルはconfig.ymlのパラメータで持たせるのはちょっと大変。プリアンプルだけメソッド切り出して、review-ext.rbで上書きしやすいようにする?

「呼び出し都度」「日本語不可」が大きめの問題。dviからでなくpdfまで作って切り出す方法なら日本語もいけるのだが、都度だと無駄な時間がかかる。

- pdfcrop / pdftoppm / ImageMagick / RMagick などを使っていくとした場合、ユーザのインストール負担が重め？ Windowsだとどこまでが許容か。
- htmlbuilderレベルではハッシュパスを入れるだけにしておいて、数式は別のファイルにストックしておき、makerで最後にまとめてコンパイル・切り出し をしたほうが妥当。

**Comment by munepi** [comment]
`latex`を走らせているところを  `2>&1 >/dev/null`ぐらいしないと、現状 epubmaker 実行時に目がチカチカしていますね。

数式中の日本語表示について、別の案件で、メソッド  `make_math_image` を上書きして対処ました。

```
system("uplatex --interaction=nonstopmode --output-directory=#{tmpdir} #{tex_path} 2>&1 >/dev/null && dvipdfmx -o - #{dvi_path} | pdfcrop - #{pdf_path} && magick -density 200 -quality 100 #{pdf_path} #{path}")
```
