### ISSUE TITLE
Book::Chapterなどのinspectがほしい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#870]
デバッグ時にちょっと面倒なので、主要オブジェクトのinspectがほしくなってきました。

**Comment by takahashim** [comment]
`Book::Chapter#inspect`は定義済みですよね…？ https://github.com/kmuto/review/blob/9578df8a019663bee2d72c96b887107016b27026/lib/review/book/chapter.rb#L69-L71

**Comment by kmuto** [comment]
あれ、見方をまちがったみたいです。すみません…
