### ISSUE TITLE
//noteなどの囲み要素内で末尾に空行があると空の段落が作成されてしまう

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#882]
//noteなどの囲み要素について、md2review変換やコメントを入れていたときに末尾の空行が空段落として生成されてしまう。
特にHTML, IDGXMLで顕在化する。

split_paragraphで末尾の空行群を無視したい。

**Comment by takahashim** [comment]
仕様についての疑問なんですが、

```
//emilst{
aaa
bb
c

//}
```

となったときに、最後の空行って勝手に削除されるべきではないと思ったんですが、そうでもないですか？

それはさておきご指摘の症状はmd2reviewのバグかもですが。

**Comment by takahashim** [comment]
それとも`//note`と`//emlist`の挙動を変えるべき、みたいな話なんでしょうか。
いずれにしてもなんでsplit_paragraphの話になるのかがわかりませんでした。

**Comment by kmuto** [comment]
//emlistのほうで消しちゃうのはバグな気がしています。

//noteなどのほうは空段落になると困るので、そっちは取りたい。split_paragraphである必要はないのですが、//noteなどのほうを見ていて一括で直せそうなかんじがしなかったので、そっちをいじっていました。

**Comment by takahashim** [comment]
あー、囲み要素というのはブロックじゃなくてcaptionblockとかのことだったりするんでしょうか？

**Comment by kmuto** [comment]
おっと、そうですね。対象は、note, memo, tip, info, warning, important, caution, notice, quote, bibpaper, lead かな。

**Comment by takahashim** [comment]
そうだったんですね。なんか勘違いしてて失礼しました。じゃあsplit_paragraphの挙動を変えるべきなのかな…。

**Comment by takahashim** [comment]
いずれにしても現状のPR #883は、split_paragraph(lines)を実行すると呼び出した側のlinesの値が勝手に書き換わる（ことがある）仕様なので、修正は必要そうです。
