### ISSUE TITLE
includeがドキュメントに記載されていない

### ISSUE THREAD

**Issue by doublemarket** [kmuto/review#887]
こんにちは、以前[たのしいRe:VIEW](https://techbof.connpass.com/event/48519/)で概要を学んで以来、最近使い始めました。便利な仕組みをありがとうございます。

ソースコードなどをlistなどに入れる時、

```
//list[識別子][キャプション]{
@<include>{任意のファイル名}
//}
```

とすると[任意のファイルをそこに読み込めること](https://github.com/kmuto/review/issues/39)に気づきました。この機能はたくさんのlist/emlist/cmdや、同一の文章を複数回貼るような書籍の場合便利なので、ドキュメントに記載があった方がうれしいと思います。

( #739 はこれと同じことでしょうか？)

**Comment by kmuto** [comment]
角さんパッチが2011年にマージされていたのに気付いていませんでした…（開発者会議あたりで決めたんだっけか）

が、今あらためて見るとちょっと挙動的に嫌かもと思うところがあり、タグ名も変える可能性があります。（issueを別途立てます）

**Comment by kdmsnr** [comment]
listに入れるときはincludeではなくプリプロセッサで対応してください。
ドキュメントには引き続き掲載しない方向で。
