### ISSUE TITLE
@include, //includeの挙動

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#888]
#887 に関連

- compile_inlineあるいはparagraphで処理されており、何でもincludeできるわけではない（preprocと違い、たとえば見出しや表や箇条書きなどを入れられない）という点で、「include」というタグ名はちょっと広く取られすぎるかも？
- `@<include>`をコードの取り込みなどに使おうとした場合、末尾に不要な空行が入る。inline_includeのFile.read結果末尾をchompで削ったほうがいい？

**Comment by kdmsnr** [comment]
- `paragraph` は削除でもよさそうですねえ（おそらく `compiler` までは戻せないので、ひとまず文章挿入のみを処理できるようにした記憶が……）。
- よいと思います。
