### ISSUE TITLE
sample-bookのRakefileのtypo

### ISSUE THREAD

**Issue by seki** [kmuto/review#901]
test/sample-book/src/Rakefile にtypoらしきものがありました。

@@ -46,7 +46,7 @@
 desc 'generate PDF file'
 task pdf: BOOK_PDF
 
-desc 'generate stagic HTML file for web'
+desc 'generate static HTML file for web'
 task web: WEBROOT
 
 desc 'generate EPUB file'

**Comment by takahashim** [comment]
ご報告ありがとうございます！ #904 で対応しました。
