### ISSUE TITLE
LATEXBuilder: リストものはreviewlistblock環境で囲む

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#916]
#913 にも絡むのですが、そもそもの原因はreviewlistやreviewemlistとキャプションが独立していて個別にアキを入れていることにあります。

```
\reviewemlistcaption{foo}
\begin{reviewemlist}
bar
\end{reviewemlist}

\begin{reviewemlist}
foo
\end{reviewemlist}

\reviewlistcaption{リスト1.1: foo}
\begin{reviewlist}
bar
\end{reviewlist}
```

手元のTeX案件ではmunepiさんの進言を受けて、キャプション+リスト系をreviewlistblock環境で囲み、そちらでアキを入れるようにしています。

```
\begin{reviewlistblock}
\reviewemlistcaption{foo}
\begin{reviewemlist}
bar
\end{reviewemlist}
\end{reviewlistblock}

\begin{reviewlistblock}
\begin{reviewemlist}
foo
\end{reviewemlist}
\end{reviewlistblock}

\begin{reviewlistblock}
\reviewlistcaption{リスト1.1: foo}
\begin{reviewlist}
bar
\end{reviewlist}
\end{reviewlistblock}
```

latexbuilder.rb、reviewmacro.sty、layout.tex.erbなどを書き換える必要があり、既存環境を壊さずに移行はちょっと難しそうですが、今後のためには必須の措置です。

**Comment by takahashim** [comment]
これって本当は、

```tex
\begin[caption=foo]{reviewemlist}
bar
\end{reviewemlist}
```

みたいにした方がよかったりしないですか…？（が、こういうのの定義の仕方がわからなかったのと、表現力としてこれでよいのかどうかが自信ないです）

**Comment by kmuto** [comment]
[]でキャプションをkeyval入れるのはたぶんとても辛いことになりそう…。

**Comment by takahashim** [comment]
そうなんですか。でもlistings使う場合はそうなるんじゃなかったでしたっけ？

**Comment by takahashim** [comment]
#1049 で修正しました。
中身は現状なにもしてません。

**Comment by kmuto** [comment]
ありがとうございます、新しいスタイルを作ろうとするときにこれで楽になりそうです。
