### ISSUE TITLE
review-initでdocまわりをコピーする

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#918]
誰も見ないかもしれないdocだけど、gemで入れるという記事はあってもそのドキュメントを参照する方法についてはたいてい載っていないし、Dockerコンテナだとますますアクセスが遠のくので、以下の提案。

- review-init時にdoc/内のmdファイルを作業フォルダのdoc/にコピー。
- --without-docとか付けたらコピーしないようにする?
- imagesはとりあえずreview-generate.pngはそこからは使っていないようなので除外?

**Comment by kdmsnr** [comment]
コピー先が`doc`でいいのかなあと思いましたが（`review-doc`とかのほうがよかったり？）ひとまず #924 を作りました

**Comment by kmuto** [comment]
review-docだとコマンドっぽさがあるかなという気が。しょせん初期フォルダだしdocでいいのではという気持ち。
