### ISSUE TITLE
LATEXBuilder: inline_mの前後スペースは取りたい

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#925]
大きな変更にはなっちゃうんですが、inline_mで

```
    def inline_m(str)
      " ${str}$ "
    end
```

となっていると「`（@<m>{a}）`」とか「`@<m>{a}、`」とかで変なアキが入ったり、禁則が無視されたりとよくないことがいろいろ発生することに気付きました。
どこかの時点で前後スペースは取ったほうがよさそうに思います。

**Comment by kmuto** [comment]
「普通の組版」においては変な現象なので#943を反映したい。
互換性保持したほうがよければ、review_versionを見て2以下とそれ以外を区別する or configフラグを追加、ということになるけど、そこまでやるべきか…？

**Comment by kmuto** [comment]
ということで、それなりに影響はあるかもだけどやっぱり今のスペース入っているのは禍根を残すので、さっさとマージしたいなという気持ちになりました。

**Comment by kmuto** [comment]
#943 にて対応

**Comment by takahashim** [comment]
@kmuto 確認ですが、

* Re:VIEW 2では前後にスペースが入る
* Re:VIEW 3では前後にスペースが入らない

でいいんですよね？（こうなってなさそうなので現在修正中です）

**Comment by kmuto** [comment]
です。
あらら、どっか間違ったかな…

**Comment by takahashim** [comment]
#1050 で修正しました。
