### ISSUE TITLE
テキスト出力モードがほしい

### ISSUE THREAD

**Issue by huideyeren** [kmuto/review#926]
### 概要

書式情報のないテキストファイルを作成する、 ``review-plaintextmaker`` がほしい。

### 理由

書籍からワードクラウドを作成して表紙画像に使いましたが、現状の ``review-compile --target text`` を使用すると書式情報付きのテキストファイルになってしまいます。
また、これらは章ごとに分かれた状態のままです。
なので、手作業で書式情報を除き、手作業で結合していました。

そういった書式情報を含まず、 ``review-pdfmaker`` のようなプレーンテキスト生成機能が欲しいところです。
こうすると、書いた本を自然言語処理に使いやすくなるのではないかと思います。

**Comment by kmuto** [comment]
うーん、レアケースの用法に思えますので、この内容を実装した専用のツールを公式で提供するのは保守などを考えても避けたいです。
自然言語処理でやるといってもreファイルに立ち戻って直そうとしたときにテキストでは元reの位置情報を持っているわけではないですし、結局RedPenのように処理側がre形式のパースに対応するようにしてくれないと実用性が低めになりそうです。

要望の範囲での実装のアイデアとしては、たとえば

- review-epubmakerでEPUBを作ったあとにw3m -dumpで各ファイルをテキスト化して結合する
- pdfmakerの生成PDFをpdftotextする(段落が壊れたり余計なスペースが入ったりするのでイマイチですが、PDFしか元データがない業務ではたまにやります)
- topbuilderをオーバライドするか継承したdamnbuilderを作って、あらゆる書式情報を除く

あたりになるかと思います。

**Comment by kdmsnr** [comment]
（Re:VIEWで原稿作っても出版社から「テキストでくれ」と言われることがよくあります……）

**Comment by kmuto** [comment]
@kdmsnr 
それだと今の装飾が入っているtopbuilderを使うのでいいような。文字だけで画像ファイル名が抜けたりしているのを渡してもしょうがないですよね。

**Comment by takahashim** [comment]
や、テキストだけ欲しいという要求は普通にありそうな気がしますね…。別に画像の情報とかはいらないので。
とはいえHTMLからテキスト引っこ抜けばいいだけと言われるとその通りではありますが。

**Comment by kdmsnr** [comment]
装飾も画像ファイル名もいらないみたいですねえ。

`class TEXTBuilder < TOPBuilder` じゃなくて `class TOPBuilder < TEXTBuilder` にして、TEXTBuilderを装飾なしにしておけば、他の装飾記号を自前で用意することもできそうです。

**Comment by kmuto** [comment]
あまり気乗りしませんが、とりあえずreopenします。

- 生成されるのは結合1ファイル?(そっちのほうが嬉しいときと嬉しくないときの差がある) 章ごと複数ファイル?(「フォルダ」を用意する必要がある)
- noindentの扱いはどうする? (無視?)
- topbuilder / (仮)baretextbuilder の切り替えをmakerでやる?

**Comment by kmuto** [comment]
何か反応はないですかね…

**Comment by kdmsnr** [comment]
> 生成されるのは結合1ファイル?(そっちのほうが嬉しいときと嬉しくないときの差がある) 章ごと複数ファイル?(「フォルダ」を用意する必要がある)

結合ファイルの対応は不要だと思います。必要なら勝手に結合してもらう感じで。

> noindentの扱いはどうする? (無視?)

なしでよさそうです。

> topbuilder / (仮)baretextbuilder の切り替えをmakerでやる?

maker でよいと思います。このとき、前者をtop、後者をtext としたい感じはあります……が、あまりよくないですかね。

**Comment by kmuto** [comment]
textbuilderはすでにあって現状はtopbulderと同一なので、「--target=text」が装飾付きになることを前提としているケースがあるのでは？という懸念があります。注意書きくらいで済むんだろうか。

フォルダはどうしようかな。<bookname>-textあたりだろうか。

**Comment by kmuto** [comment]
とりあえずplaintextbuilder.rbを実装しはじめたところです。ulの●とかolの番号とかddの字下げとかも全部ナシでいいんかな。olの番号くらいは入ってないと困るか。

**Comment by kmuto** [comment]
#930 でコマンドを実装してみました。

**Comment by kmuto** [comment]
review-textmakerを実装しました

**Comment by kmuto** [comment]
装飾なしのものがほしいときには-nオプションを利用してください。
