### ISSUE TITLE
too difficult to read source code cause of rubocop warnings

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#956]
40058a8d80aaf6da4e443cfc1bacf9320115de41 や b2f2aa5a250029e791f4a0c02748db2504402aef などで入ったifやunlessの修飾子のコードがめちゃくちゃ読みづらいので、これについてはどこかのタイミングでまとめてrevertしたいです…（ダブルクォートをシングルクォートにしたりするのは別にいいかと思うので、素朴にgit revertする必要はないですが）

**Comment by kmuto** [comment]
後置if/unless、私はあまり違和感はなかったです（Perlコードなんかで慣れてた）。
辛いところだけ戻す、じゃだめですかね。

**Comment by takahashim** [comment]
そうですね、`next if check_foo(bar)`みたいなものは分かりやすいものも多いので、実際には程度問題というか「辛いところだけ戻す」になるかと思います。

とはいえ元々あったものではなく上記の修正でrubocopに文句を言われて直したような部分については「これはないわ…」みたいなのが散見されたのでした。
具体的には、

```ruby
error "`@<xxx>' seen but is not valid inline op: #{w}" if w.scan(/@<\w+>/).size > 1 && !/\A@<raw>/.match(w)
```

みたいなやつです。

**Comment by kmuto** [comment]
本件はほぼ解決してるはず
