### ISSUE TITLE
インラインrawで「//\}」と出力できない

### ISSUE THREAD

**Issue by takahashim** [kmuto/review#96]
ReVIEWについての記述をするにあたって、LaTeX環境で`@<raw>{|latex| ...}`を使って「//}」と出力したいのですが、LaTeXでは「}」は特殊文字なので`//\}`と出力しなければなりません。
ところが、`@<raw>{//}}`でも`@<raw>{//\}}`でも`@<raw>{//\\}}`でもうまくいかないようです。

これはそもそもどう書くのが正しいでしょうか？

**Comment by unnohideyuki** [comment]
突然ですが、こんばんは。

最近 Re:View を使い始めたのですが、わたしも @<m>{} のなかで {, } が使えないのがつらかったので、改造してみました：
https://github.com/unnohideyuki/review/commit/528cb72b58d738d9e05d518ce3d6376e9e7a6bae

これじゃだめですか？

エスケープはいらなくなったので取っちゃいましたが、残しておいた方がいいのかな…。

**Comment by takahashim** [comment]
@unnohideyuki おお！と思ったのですが、これだと``@<raw>{@<tt>{test\\}}``がエラーになりますね…。

**Comment by unnohideyuki** [comment]
ああ、なるほど。rawではなんでも書けないといけないとすると、この程度の改造ではダメっぽいですね。

**Comment by unnohideyuki** [comment]
あきらめようかなと思ったんですが、やはりあきらめきれず：
https://github.com/unnohideyuki/review/compare/inline-braces

要するに、"@<cmd>{option}" のうち "@<cmd>" の部分は正規言語で、"{option}" の部分は正規言語ではないわけですが、正規言語でないといっても括弧の対応を数えたいだけなので、さほど複雑な解析器にはならないとおもいまして。

現状では、\{ や\} を数えないので、@<raw>{@<tt>{test\\}}はだめですが、@<raw>{@<tt>{test}} はOKになってるはずです。

お手数ですが、確認してもらえると有難いです。

この方式でよいとしても、採用していただくには、現状の仕様とすり合わせる必要がありそうで、かといってエスケープの仕様を残すなら、改造する甲斐もなくなるなぁという。(それ以前のチョンボがなければよいのですが…）

私は、@<m> のなかで {, } が自由に使いたいので、しばらく自分むけにはこれでいってみます。

**Comment by takahashim** [comment]
@unnohideyuki  やりたいことは分かるような気もするのですが、例えば、

「LaTeXで環境の開始を指定するには、`\begin{`と`}`の間に環境名を書きます。」

みたいなことをRe:VIEWで記述するには、

```
LaTeXで環境の開始を指定するには、@<tt>{\begin{}と@<tt>{\}}の間に環境名を書きます。
```

としていたのでした。

unnohideyukiさんの提案では、このような文言が記述できなくなったりしないですか？（実際試してみても上手くいかなくて…）

**Comment by unnohideyuki** [comment]
なるほど。　括弧の対応にカウントしてほしくないケースがあるので、なんらかのエスケープは必要なわけですね。
それなら、いまのままの仕様でよいですね。　理解しました。
ありがとうございます。

**Comment by kmuto** [comment]
爆誕させたエスケープ不要の `@<cmd>$〜$` あるいは `@<cmd>|〜|` 記法で対処できるはず。
