### ISSUE TITLE
ReVIEW.loggerが冗長にすぎる

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#975]
ログ系はできるだけloggerに統一ということで取り込んだ機能ですが、デフォルトのは冗長すぎる気がします。
デフォルト設定を変えることはできるでしょうか（そもそもこれの切り替えはどうやるのを想定していたんでしたっけ…）。

**Comment by takahashim** [comment]
https://github.com/kmuto/review/blob/d893e1431a1daf42a36470f728c8202774174d11/lib/review/logger.rb#L7 この辺で`ReVIEW::Logger.new()`したときには「ログレベル: メッセージ」だけにしてるつもりだったんですが、なんか変な使い方になってるんですかね…

コードの挙動はまだ確認できてないです。

**Comment by kdmsnr** [comment]
手元で動かした限り #962 みたいには出ませんでした。

```
:
[1] [2] (./book.aux) )
Output written on book.dvi (4 pages, 2868 bytes).
Transcript written on book.log.
INFO: dvipdfmx -d 5 book.dvi
book.dvi -> book.pdf
:
```

**Comment by kmuto** [comment]
おや… Linuxだからかなぁ。

**Comment by kmuto** [comment]
macでもダメだな、
```
formatter: ->(severity, _datetime, _progname, msg) { "#{severity}: #{msg}\n" }
```
が効かないみたい。試しにlogger.formatter = proc... で直接指定したら短くなりました。

**Comment by kdmsnr** [comment]
formatter は Ruby 2.4 からの引数ですかね。
http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html#method-c-new
http://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html#method-c-new

**Comment by kmuto** [comment]
おぉ、なるほど。ありがとうございます。
今までずっと「なんか長いなー」と思っていたのはバグだったのか…

**Comment by takahashim** [comment]
なんと、そういうオチだったんですね…。
